.TH JAM 1 "March 13, 2002" "Darwin"
.na
.nh
.SH NAME
jam
\- a program construction tool
.SH DESCRIPTION
.B Jam
is a command-line tool for building software. The version of 
.B jam 
included with Mac OS X has been
heavily modified for use with Project Builder. If you want to use 
.B jam 
for your own purposes, download
the standard distribution from http://www.perforce.com/.