	{ "!", _BANG },
	{ "!=", _BANG_EQUALS },
	{ "&&", _AMPERAMPER },
	{ "(", _LPAREN },
	{ ")", _RPAREN },
	{ "+=", _PLUS_EQUALS },
	{ ":", _COLON },
	{ ";", _SEMIC },
	{ "<", _LANGLE },
	{ "<=", _LANGLE_EQUALS },
	{ "=", _EQUALS },
	{ ">", _RANGLE },
	{ ">=", _RANGLE_EQUALS },
	{ "?=", _QUESTION_EQUALS },
	{ "actions", ACTIONS },
	{ "bind", BIND },
	{ "case", CASE },
	{ "default", DEFAULT },
	{ "deferred", DEFERRED },                 /* Apple Dec 2000 */
	{ "else", ELSE },
	{ "commitdeferred", COMMITDEFERRED },     /* Apple Dec 2000 */
	{ "existing", EXISTING },
	{ "export", EXPORT },                     /* Apple Nov 2000 */
	{ "exportvars", EXPORTVARS },             /* Apple Nov 2000 */
	{ "for", FOR },
	{ "if", IF },
	{ "ignore", IGNORE },
	{ "in", IN },
	{ "include", INCLUDE },
	{ "local", LOCAL },
	{ "on", ON },
	{ "piecemeal", PIECEMEAL },
	{ "quietly", QUIETLY },
	{ "rule", RULE },
	{ "switch", SWITCH },
	{ "together", TOGETHER },
	{ "updated", UPDATED },
	{ "{", _LBRACE },
	{ "||", _BARBAR },
	{ "}", _RBRACE },
