.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek and the American National Standards Committee X3,
.\" on Information Processing Systems.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)printf.3	8.1 (Berkeley) 6/4/93
.\" $FreeBSD: src/lib/libc/stdio/printf.3,v 1.58 2004/10/16 16:00:01 stefanf Exp $
.\"
.Dd March 11, 2005
.Dt PRINTF_L 3
.Os
.Sh NAME
.Nm printf_l , fprintf_l , sprintf_l , snprintf_l , asprintf_l ,
.Nm vprintf_l , vfprintf_l , vsprintf_l , vsnprintf_l , vasprintf_l
.Nd formatted output conversion
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In stdio.h
.In xlocale.h
.Ft int
.Fn printf_l "locale_t loc" "const char * restrict format" ...
.Ft int
.Fn fprintf_l "FILE * restrict stream" "locale_t loc" "const char * restrict format" ...
.Ft int
.Fn sprintf_l "char * restrict str" "locale_t loc" "const char * restrict format" ...
.Ft int
.Fn snprintf_l "char * restrict str" "size_t size" "locale_t loc" "const char * restrict format" ...
.Ft int
.Fn asprintf_l "char **ret" "locale_t loc" "const char *format" ...
.In stdarg.h
.Ft int
.Fn vprintf_l "locale_t loc" "const char * restrict format" "va_list ap"
.Ft int
.Fn vfprintf_l "FILE * restrict stream" "locale_t loc" "const char * restrict format" "va_list ap"
.Ft int
.Fn vsprintf_l "char * restrict str" "locale_t loc" "const char * restrict format" "va_list ap"
.Ft int
.Fn vsnprintf_l "char * restrict str" "size_t size" "locale_t loc" "const char * restrict format" "va_list ap"
.Ft int
.Fn vasprintf_l "char **ret" "locale_t loc" "const char *format" "va_list ap"
.Sh DESCRIPTION
The
.Fn printf_l ,
.Fn fprintf_l ,
.Fn sprintf_l ,
.Fn snprintf_l ,
.Fn asprintf_l ,
.Fn vprintf_l ,
.Fn vfprintf_l ,
.Fn vsprintf_l ,
.Fn vsnprintf_l ,
and
.Fn vasprintf_l
functions are extended locale versions of the
.Fn printf ,
.Fn fprintf ,
.Fn sprintf ,
.Fn snprintf ,
.Fn asprintf ,
.Fn vprintf ,
.Fn vfprintf ,
.Fn vsprintf ,
.Fn vsnprintf ,
and
.Fn vasprintf
functions, respectively.
Refer to their manual pages for details.
Also, see
.Xr xlocale 3 for more information about extended locales.
.Sh SEE ALSO
.Xr printf 3 ,
.Xr xlocale 3
