LIBRARY GLU
VERSION LIBRARY_VERSION
EXPORTS

bezierPatchDelete
bezierPatchDeleteList
bezierPatchDraw
bezierPatchEval
bezierPatchEvalNormal
bezierPatchInsert
bezierPatchListDraw
bezierPatchMake
bezierPatchMake2
bezierPatchPrint
bezierPatchPrintList
bezierPatchMeshBeginStrip
bezierPatchMeshDelDeg
bezierPatchMeshDelete
bezierPatchMeshDraw
bezierPatchMeshEndStrip
bezierPatchMeshEval
bezierPatchMeshInsertUV
bezierPatchMeshListCollect
bezierPatchMeshListDelDeg
bezierPatchMeshListDelete
bezierPatchMeshListDraw
bezierPatchMeshListEval
bezierPatchMeshListInsert
bezierPatchMeshListNumTriangles
bezierPatchMeshListPrint
bezierPatchMeshListReverse
bezierPatchMeshListTotalStrips
bezierPatchMeshListTotalVert
bezierPatchMeshMake
bezierPatchMeshMake2
bezierPatchMeshNumTriangles
bezierPatchMeshPrint
bezierPatchMeshPutPatch
drawStrips
gluBeginCurve
gluBeginSurface
gluBeginTrim
gluDeleteNurbsRenderer
gluDeleteNurbsTessellatorEXT
gluEndCurve
gluEndSurface
gluEndTrim
gluGetNurbsProperty
gluLoadSamplingMatrices
gluNewNurbsRenderer
gluNurbsCallback
gluNurbsCallbackData
gluNurbsCallbackDataEXT
gluNurbsCurve
gluNurbsProperty
gluNurbsSurface
gluPwlCurve
glu_LOD_eval_list
__gl_dictListDelete
__gl_dictListDeleteDict
__gl_dictListInsertBefore
__gl_dictListNewDict
__gl_dictListSearch
__gl_edgeEval
__gl_edgeIntersect
__gl_edgeSign
__gl_transEval
__gl_transSign
__gl_vertCCW
__gl_vertLeq
__gl_memInit
__gl_meshAddEdgeVertex
; __gl_meshCheckMesh
__gl_meshConnect
__gl_meshDelete
__gl_meshDeleteMesh
__gl_meshMakeEdge
__gl_meshNewMesh
__gl_meshSplice
__gl_meshSplitEdge
__gl_meshUnion
__gl_meshZapFace
__gl_projectPolygon
__gl_pqHeapDelete
__gl_pqHeapDeletePriorityQ
__gl_pqHeapExtractMin
__gl_pqHeapInit
__gl_pqHeapInsert
__gl_pqHeapNewPriorityQ
__gl_pqSortDelete
__gl_pqSortDeletePriorityQ
__gl_pqSortExtractMin
__gl_pqSortInit
__gl_pqSortInsert
__gl_pqSortIsEmpty
__gl_pqSortMinimum
__gl_pqSortNewPriorityQ
__gl_renderBoundary
__gl_renderCache
__gl_renderMesh
__gl_computeInterior
__gl_noBeginData
__gl_noCombineData
__gl_noEdgeFlagData
__gl_noEndData
__gl_noErrorData
__gl_noVertexData
gluBeginPolygon
; gluDeleteMesh
gluDeleteTess
gluEndPolygon
gluGetTessProperty
gluNewTess
gluNextContour
gluTessBeginContour
gluTessBeginPolygon
gluTessCallback
gluTessEndContour
gluTessEndPolygon
gluTessNormal
gluTessProperty
gluTessVertex
__gl_meshDiscardExterior
__gl_meshSetWindingNumber
__gl_meshTessellateInterior
__gl_meshTessellateMonoRegion
gluErrorString
; __glNURBSErrorString
; __glTessErrorString
; bitmapBuild2DMipmaps
; fastBuild2DMipmaps
gluBuild1DMipmapLevels
gluBuild1DMipmaps
gluBuild2DMipmapLevels
gluBuild2DMipmaps
gluBuild3DMipmapLevels
gluBuild3DMipmaps
gluScaleImage
gluScaleImage3D
; __gluInvertMatrixd
; __gluMakeIdentityd
; __gluMakeIdentityf
; __gluMultMatricesd
; __gluMultMatrixVecd
gluLookAt
gluOrtho2D
gluPerspective
gluPickMatrix
gluProject
gluUnProject
gluUnProject4
gluCylinder
gluDeleteQuadric
gluDisk
gluNewQuadric
gluPartialDisk
gluQuadricCallback
gluQuadricDrawStyle
gluQuadricNormals
gluQuadricOrientation
gluQuadricTexture
gluSphere
gluCheckExtension
gluGetString

/* $XFree86: xc/lib/GLU/GLU-def.cpp,v 1.1 2001/02/13 19:19:11 dawes Exp $ */
