.Dd December 5, 2007
.Dt GEM 1
.Os
.Sh NAME
.Nm gem, update_rubygems
.Nd RubyGems Package Manager
.Sh SYNOPSIS
.Nm gem 
.Ar command 
.Op Ar arguments... 
.Op Ar options...
.Nm update_rubygems
.Sh DESCRIPTION
RubyGems is a sophisticated package manager for the Ruby programming language, that consists of the
.Nm gem
command line program.
.Pp
For more information about the
.Nm gem
program, you can use its
.Fl -help
flag. There is also online documentation available at "http://docs.rubygems.org".
.Pp
The
.Nm update_rubygems
program is a tool used to update the RubyGems distribution.
.Pp
.Sh SEE ALSO
.Xr ruby 1
.Sh AUTHORS
RubyGems was originally developed at RubyConf 2003 by Rich Kilmer, Chad Fowler, David Black, Paul Brannan and Jim Weirch, and has received a lot of contributions since then. RubyGems is now principally developed and maintained by Eric Hodel. You can obtain the RubyGems sources at http://rubyforge.org/projects/rubygems/. 
