.\" Man page for man (and the former manpath)
.\"
.\" Copyright (c) 1990, 1991, John W. Eaton.
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the man 1.0
.\" distribution.  
.\"
.\" John W. Eaton
.\" jwe@che.utexas.edu
.\" Department of Chemical Engineering
.\" The University of Texas at Austin
.\" Austin, Texas  78712
.\"
.\" Many changes - aeb
.\"
.TH man 1 "September 2, 1995"
.LO 1
.SH ИМЕ
man \- форматиране и извеждане на страници от онлайн ръководството
.br
manpath \- установяване на пътя за търсене на страници от ръководството за
конкретния потребител
.SH СИНТАКСИС
.B man 
.RB [ \-acdfFhkKtwW ]
.RB [ --path ] 
.RB [ \-m 
.IR система ] 
.RB [ \-p 
.IR текст ] 
.RB [ \-C 
.IR конфигурационен_файл ] 
.RB [ \-M 
.IR път ]
.RB [ \-P
.IR програма ] 
.RB [ \-S 
.IR списък_от_секции ] 
.RI [ секция ] 
.I "име ..."

.SH ОПИСАНИЕ
.B man
форматира и извежда страници от онлайн ръководството. Ако е указана
.IR секция ,
.B man
търси само в тази секция на ръководството.
.I име
обикновенно е име на страница от ръководството, т.е. по принцип име на
команда, функция или файл. Ако обаче
.I име
съдържа наклонена черта
.RB ( / ),
.B man 
го възприема като име на файл, така че можете да изпълните
.B "man ./foo.5"
или дори
.B "man /cd/foo/bar.1.gz\fR.\fP"
.PP
По-надолу е описано къде
.B man
търси страниците от ръководството.
 
.SH ОПЦИИ
.TP
.B \-\^C " конфигурационен_файл"
Указва кой конфигурационен файл да се използва. Подразбира се
.BR @man_config_file@ .
(Вижте
.BR man.conf (5)).
.TP
.B \-\^M " път"
Списък на директории, разделени с двоеточие, в които да се търсят страници от
ръководството. Празен списък e същото като да не се укаже
.BR \-M .
Вижте
.BR "ПЪТ ЗА ТЪРСЕНЕ НА СТРАНИЦИ ОТ РЪКОВОДСТВОТО" .
.TP
.B \-\^P " програма"
Програма която да се ползва за показване на страниците. Тази опция е с
по-висок приоритет от променливата на обкръжението
.BR MANPAGER ,
която пък е с по-висок приоритет от
.BR PAGER .
По подразбиране
.B man
използва
.BR "@pager@" .
.TP
.B \-\^S " списък_от_секции"
Списък от секции, разделени с двоеточие, в които да се търсят страници от
ръководството. Тази опция е с по-висок приоритет от променливата на
обкръжението
.BR MANSECT .
.TP
.B \-\^a
Извеждане на всички намерени страници. По подразбиране
.B man
извежда само първата намерена страница.
.TP
.B \-\^c
Форматиране наново на оригиналната страница дори ако съществува актуална
готова страница. Това има смисъл ако готовата страница е повредена или
форматирана за екран с различен брой редове.
.TP
.B \-\^d
Извеждане не на страници, а на диагностична информация за изпълнението на
.BR man .
.TP
.B \-\^D
Извеждане и на страниците, и на диагностична информация.
.TP
.B \-\^f
Еквивалент на
.BR whatis .
.TP
.BR \-\^F " или " \-\-preformat
Само форматиране, без извеждане.
.TP
.B \-\^h
Извеждане само на помощно съобщение.
.TP
.B \-\^k
Еквивалент на
.BR apropos .
.TP
.B \-\^K
Търсене на указан текст във *всички* страници. Внимание: това най\-вероятно
ще е много бавно, така че е добре е да се укаже секция. (Само за да
придобиете представа, на моята машина търсенето в 500 страници отнема около
минута).
.TP
.B \-\^m " система"
Търсене в алтернативен набор от страници, отговарящи на указаната система.
.TP
.B \-\^p " текст"
Списък от команди за предварителна обработка, които да се стартират преди
.B nroff
или
.BR troff .
Не всички системи разполагат с пълен набор от средства за предварителна
обработка. Някои от командите и буквите, използвани за извикването им, са:
eqn (e), grap (g), pic (p), tbl (t), vgrind (v), refer (r).
Тази опция е с по-висок приоритет от променливата на обкръжението
.BR MANROFFSEQ .
.TP
.B \-\^t
Използване на
.B @troff@
за форматиране страницата и изпращане на резултата на стандартния изход.
Възможно е да се наложи използването на допълнителен филтър преди страницата
да се отпечата.
.TP
.B \-\^w \fRили\fP \-\-path
Извеждане не на страниците, а на местонахождението на файловете, които биха
били форматирани или изведени. Ако не е указан аргумент, извеждане (на
стандартния изход) на директориите, в които
.B man
търси страници от ръководството. Ако командата
.B manpath
сочи към man, то "manpath" е еквивалент на "man --path".
.TP
.B \-\^W
Като \-\^w, но имената на файловете се извеждат по един на ред и без
допълнителна информация. Използва се за команди като
.ft CW
.BR "man -aW man | xargs ls -l" .
.ft

.SH "ГОТОВИ СТРАНИЦИ"
За да икономисва време при форматирането на страниците, man се опитва да
съхранява форматираните страници и впоследствие да ги използва готови. По
традиция готовите ("cat") версии на страниците от ДИРЕКТОРИЯ/manX се
съхраняват в ДИРЕКТОРИЯ/catX, но в
.BR @man_config_file@
може да се укаже друго съответствие (съответствия). Готовите страници не се
съхраняват ако необходимата за това директория липсва или man.conf съдържа
директивата NOCACHE.
.PP
Възможно е
.B man
да се присвои на потребителя man. Тогава, ако cat директорията е с потребител
man и права за достъп 0755 (достъпна за запис само от man), и ако cat
файловете са с потребител man и права за достъп 0644 или 0444 (достъпни за
запис само от man или забранени за запис), никой обикновен потребител не може
да променя готови страници или да помества други файлове в cat директорията.
Ако
.B man
не е присвоен на потребителя man и всички потребители трябва да могат да
създават cat страници, то cat директориите трябва да са с права за достъп
0777.
.PP
Опцията
.B \-c
задължително форматира наново оригиналната страница, дори ако съществува
актуална готова страница.


.SH "ПЪТ ЗА ТЪРСЕНЕ НА СТРАНИЦИ ОТ РЪКОВОДСТВОТО"
.B man
използва сложен алгоритъм за търсене на страници от ръководството, базиран на
подадените опции, конфигурационния файл
.B @man_config_file@ 
и някои вградени конвенции и евристики.
.PP
Първо, ако аргумента
.I име
подаден на
.B man
съдържа наклонена черта
.RB ( / ),
.B man
го възприема като име на файл и не провежда никакво търсене.
.PP
В нормалния случай обаче, когато
.I име
не съдържа наклонена черта,
.B man
претърсва разнообразни директории за файл, който би могъл да е страница от
ръководството за указаното
.IR име .
.PP
Ако зададете опцията
.BI "-M " път,
то
.I път
е списъка от директории, които
.B man 
претърсва.
.PP
Ако не зададете
.BR -M ,
но дадете стойност на променливата от обкръжението
.BR MANPATH ,
тази стойност е списъка от директории, които
.B man
претърсва.
.PP
Ако не укажете явен път за търсене чрез
.B -M
или
.BR MANPATH ,
.B man
съставя свой собствен списък от директории за търсене, базиран на
съдържанието на конфигурационния файл
.BR @man_config_file@ .
Директивите
.B MANPATH
в конфигурационния файл указват отделните директории, които да се включат в
пътя за търсене.
.PP
Освен това
.B MANPATH_MAP
директивите добавят директории към пътя за търсене на страници в зависимост
от пътя за търсене на команди, т.е. на променливата от обкръжението
.BR PATH .
За всяка директория, която е в пътя за търсене на команди,
.B MANPATH_MAP
директивата указва директория, която да бъде добавена към пътя за търсене на
страници.
.B man
взема стойността на променливата
.B PATH
и добавя съответните директории към пътя за търсене на страници. По този
начин, при правилно използване на
.BR MANPATH_MAP ,
когато изпълните командата
.BR "man xyz" ,
ще получите страницата от ръководството за програмата, която би била
стартирана, ако се изпълни командата
.BR xyz .
.PP
В допълнение, за всяка директория от пътя за търсене на команди ("командна
директория"), за която
.I липсва
.B MANPATH_MAP 
директива,
.B man
автоматично търси директория за страници "наблизо", по\-точно поддиректория
на командната директория или на нейната родителска директория.
.PP
Търсенето на директории "наблизо" може да се изключи с директивата
.B NOAUTOPATH
в
.BR @man_config_file@ .
.PP
Във всяка от директориите, описани по\-горе,
.B man
търси файл наречен
.IB име . секция\fR,
с незадължителен суфикс номера на секцията, и евентуално със суфикс за
компресия. Ако не намери факъв файл,
.B man
търси във всички поддиректории, ако
има такива, с имена
.BI man N
или
.BI cat N\fR,
където
.I N
е номера на секцията.
Ако файла е в поддиректория
.BI cat N\fR,
.B man
приема, че това е файл с готова форматирана страница. В противен случай
.B man
приема че файла е неформатиран. И в двата случая, ако името на файла завършва
с известен на
.B man
суфикс за компресия, например
.BR .gz ,
.B man
приема, че файла е компресиран.
.PP
Ако искате да видите дали (или къде)
.B man
би намерил дадена страница от ръководството, използвайте опцията
.BR "--path " ( -w ).

.SH ОБКРЪЖЕНИЕ
.TP
.B MANPATH
Път за търсене на страници от ръководството. Тази променлива е с по\-висок
приоритет от конфигурационноя файл и автоматичния път за търсене,
но с по\-нисък от опцията
.BR -M .
Вижте
.BR "ПЪТ ЗА ТЪРСЕНЕ НА СТРАНИЦИ ОТ РЪКОВОДСТВОТО" .
.TP
.B MANPL
Дължина на страницата. По подразбиране цялата страница от ръководството
заема една единствена (дълга) форматирана страница.
.TP
.B MANROFFSEQ
Набор от команди за предварителна обработка, които да се стартират преди
.B nroff
или
.BR troff .
По подразбиране, преди
.B nroff
страниците се обработват с tbl.
.TP
.B MANSECT
Набор от секции на ръководството, в които да се търси.
.TP
.B MANWIDTH
Ширина на страницата. По подразбиране се използва ширината на екрана.
.TP
.B MANPAGER
Ако
.B MANPAGER
има стойност, тя се ползва като име на програма, с която страниците да се
извеждат. В противен случай се ползва
.BR PAGER .
Ако и тя няма стойност, ползва се
.BR @pager@ .
.TP
.B LANG
Поддиректория, в която man най-напред да търси страниците от ръководството.
Така командата `LANG=bg man 1 foo' ще накара man да търси страницата за foo
първо в .../bg/man1/foo.1, и ако не я намери там, в .../man1/foo.1 (... е
директория от пътя за търсене).
.TP
.B "NLSPATH, LC_MESSAGES, LANG"
Променливите от обкръжението
.B NLSPATH
и
.B LC_MESSAGES
(или
.BR LANG ,
ако LC_MESSAGES няма стойност) играят роля при търсенето на каталога със
съобщения на man (английските съобщения са компилирани в самия man и не
изискват каталог).
Забележка: програми, викани служебно от man, например
.BR col(1) ,
също използват LC_CTYPE.
.TP
.B PATH
Помага да се състави пътя за търсене на страници от ръководството. Вижте
.BR "ПЪТ ЗА ТЪРСЕНЕ НА СТРАНИЦИ ОТ РЪКОВОДСТВОТО" .
.TP
.B SYSTEM
Подразбиращо се имe на алтернативна система за опцията
.BR \-m .
.SH "ВИЖТЕ СЪЩО"
apropos(1), whatis(1), less(1), groff(1), man.conf(5).
.SH ГРЕШКИ
Опцията
.B \-t
работи само ако е инсталирана програмата troff или подобна.
.br
Ако вместо знак за пренасяне на нов ред виждате (мигащо) \e255 или <AD>,
задайте в обкръжението `LESSCHARSET=latin1'.
.SH ПОЛЕЗНИ СЪВЕТИ
Ако добавите реда

  (global-set-key [(f1)] (lambda () (interactive) (manual-entry (current-word))))

към вашия
.IR .emacs 
файл, натискането на F1 ще ви дава страница с помощ за библиотечната функция,
на която е позициониран курсора.
.LP
За да получите чисто текстова версия на страница от ръководството, без
обратни наклонени черти и подчертавания, пробвайте:

  # man foo | col -b > foo.mantxt

