.\" @(#)man.conf
.TH MAN.CONF 5 "21 август 2005"
.SH ИМЕ
man.conf \- конфигурационни данни за man
.SH ОПИСАНИЕ
.LP
Този файл се чете от
.BR man (1)
и съдържа: (а) информация как да се създаде пътят за търсене 
на страници от ръководството; (б) пълните имена на различни 
програми като nroff, eqn, tbl и т.н., използвани от man; (в) 
списък на декомпресиращи програми за файлове с определени 
разширения. Различен от стандартния конфигурационен файл 
може да бъде указан с:
.LP
.RS
man -C private_man.conf ...
.RE
.LP
Имената на командите могат да включват и съответни опции.  
grotty(1) включва често използвани опции за nroff.  
Например, вместо подразбиращия се ред:
.LP
.RS
.nf
NROFF /usr/bin/groff -mandoc -Tlatin1
.fi
.RE
.LP
можете за използвате:
.LP
.RS
.nf
NROFF /usr/bin/groff -mandoc -Tlatin1 -P-u -P-b
.fi
.RE
.LP
за да забраните подчертаването и зачертаването.
.SH ФАЙЛОВЕ
.I "@man_config_file@"
.SH "АВТОР/ПОДДРЪЖКА"
Първоначалният автор на 
.BR man 
е John W. Eaton. Federico Lucifredi <flucifredi@acm.org> 
осъществява текущо поддръжката на пакета.
.SH ПРЕВОД
Димитър Жеков, Александър Шопов <ash@contact.bg>
.SH "ВИЖТЕ СЪЩО"
.BR col (1),
.BR (g)eqn (1),
.BR (g)pic (1),
.BR groff (1),
.BR grotty (1),
.BR (g)refer (1),
.BR (g)tbl (1),
.BR less (1), 
.BR man (1),
.BR compress (1),
.BR gzip (1).
