.\" @(#)man.conf
.TH MAN.CONF 5 "30 Mar 1994"
.SH ИМЕ
man.conf \- конфигурационни данни за man
.SH ОПИСАНИЕ
.LP
Този файл се чете от
.BR man (1)
и съдържа: (а) информация как да се създаде пътя за търсене на страници от
ръководството (б) пълните имена на различни програми като nroff, eqn, tbl и
т.н., използвани от man, и (в) списък на декомпресиращи програми за файлове с
определени разширения. Алтернативна версия на файла може да бъде указана с:
.LP
.RS
man -C private_man.conf ...
.RE
.LP
Имената на командите могат да включват и опции. grotty(1) включва често
използвани опции за nroff. Например вместо подразбиращия се ред:
.LP
.RS
.nf
NROFF /usr/bin/groff -mandoc -Tlatin1
.fi
.RE
.LP
можете за използвате:
.LP
.RS
.nf
NROFF /usr/bin/groff -mandoc -Tlatin1 -P-u -P-b
.fi
.RE
.LP
за да забраните подчертаването и зачертаването.
.SH ФАИЛОВЕ
.I "@man_config_file@"
.SH "ВИЖТЕ СЪЩО"
col(1), (g)eqn(1), (g)pic(1), groff(1), grotty(1), (g)refer(1), (g)tbl(1),
less(1), man (1) and compress(1), gzip(1).

