.\" Man page for whatis
.\"
.\" Copyright (c) 1990, 1991, John W. Eaton.
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the man 1.0
.\" distribution.  
.\"
.\" John W. Eaton
.\" jwe@che.utexas.edu
.\" Department of Chemical Engineering
.\" The University of Texas at Austin
.\" Austin, Texas  78712
.\"
.TH whatis 1 "Jan 5, 1991"
.LO 1
.SH ИМЕ
whatis \- търсене на цели думи в базата данни на whatis
.SH СИНТАКСИС
.BI whatis
ключова_дума ...
.SH ОПИСАНИE
whatis търси ключови думи в база данни от файлове, съдържащи кратки описания
на системните команди, и извежда резултата на стандартния изход. Извеждат се
само намерените цели думи.

Базата данни на whatis се създава с командата @makewhatis@.
.SH "ВИЖТЕ СЪЩО"
apropos(1), man(1).
