.\" Copyright (c) 2012-2025, Apple Inc.  All rights reserved.
.\"
.Dd November 21, 2025
.Dt LTOP 1
.Os "macOS"
.Sh NAME
.Nm ltop
.Nd Display ledger information for processes on the system
.Sh SYNOPSIS
.Nm ltop
.Bk -words
.Fl h
.Pp
.Nm ltop
.Op Fl dLN
.Op Fl g Ar group
.Op Fl p Ar pid
.Op Fl r Ar resource
.Op Ar interval
.Ek
.Sh DESCRIPTION
.Nm ltop
displays the contents of system ledgers maintained by the kernel for each process in the system.
Ledgers are a general accounting mechanism that the kernel uses to track and limit things like CPU time and memory usage.
.Pp
If the optional
.Ar interval
is specified, then
.Nm
will display the ledger contents every interval seconds.
.Pp
The options are as follows:
.Bl -tag -width indent
.\" ==========
.It Fl d
In conjunction with
.Ar interval ,
display the rate of change for each value, as compared to the previous sample displayed.
.\" ==========
.It Fl L
Display template info.
Shows which resources are tracked, and lists the associated units.
.\" ==========
.It Fl g Ar group
Only display info for the ledgers associated with
.Ar group .
Group topology can be seen via the
.Fl L
option.
.\" ==========
.It Fl p Ar pid
Only display info for process
.Ar pid .
.\" ==========
.It Fl N
Filter out entries where credits, debits, and balance are all zero.
.\" ==========
.It Fl r Ar resource
Only display info for ledger resource
.Ar resource .
Resources are ledgers tracked by the kernel, such as memory or CPU usage.
Available resources can be listed via the
.Fl L
option.
.\" ==========
.El
.Sh SEE ALSO
.Xr top 1
