#!/bin/sh
#
# network configuration has changed
#
logger -i -p daemon.debug -t enable-network "process network configuration change"

. /etc/rc.common
CheckForNetwork
if [ "${NETWORKUP}" = "-NO-" ]; then exit 0; fi

if [ -x /System/Library/StartupItems/NetworkTime/NetworkTime ]; then
	/System/Library/StartupItems/NetworkTime/NetworkTime start
fi

if [ -x /System/Library/StartupItems/NIS/NIS ]; then
	/System/Library/StartupItems/NIS/NIS start
fi

if [ -x /System/Library/StartupItems/NFS/NFS ]; then
	/System/Library/StartupItems/NFS/NFS start
fi

exit 1
