
verbose "Test test_002.exp: level [info level]"
verbose "szTestName: [set szTestName]"
verbose "lTestName : $lTestName"
pass
namespace ::Common {
    if [info exists i] {
	if {[expr $i % 2]} {
	    verbose "    Remainder is 1 >$i<"
	    incr i
	    pass "karel"
	    return
	} else {
	    verbose "    Zero remainder >$i<"
	    fail "pieter"
	    incr i
	}
	verbose "         === End: $env(SHELL)"
    } else {
	verbose "#### i doesn't exists"
    }
}
