#
# Procedures and other definitions for application:
#
#             testSession
#



proc popQueue {args} {
    global szDefaultQueue

    if {[llength $args] == 1} {
	set Queue [lindex $args 0]
	if {[string compare [infoWhich $Queue] ""] == 0} {
	    error "NOT a queue >$args<"
	} else {
	    eval [concat [infoWhich $Queue] pop]
	}
    } else {
	if {[info exist szDefaultQueue]} {
	    eval [concat $szDefaultQueue pop]
	} else {
	    error "NO default queue"
	}
    }
}
