[def "[cmd diameter] [arg length]"]
[def "[cmd diam] [arg length]"]

Specifies the diameter of the [cmd circle] element, as an alternative
way to specify its [cmd radius].

Effective if and only if the radius was not specified. I.e. if both
diameter and radius are specified then the radius infomration has
precendence.

This attribute has no default, because the defaults are taken from the
radius.
