.\"
.\"     @(#)IPConfigurationHelper.8
.\"
.Dd January 24, 2024
.Dt IPCONFIGURATIONHELPER 8
.Os "Mac OS X"
.Sh NAME
.Nm IPConfigurationHelper
.Nd parsing helper for configd
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
.Nm
is a an XPCService that launches on-demand upon request from the IPConfiguration agent of the configd daemon.
.Pp
The IPConfiguration agent runs as the root user inside of configd, whereas
.Nm
doesn't run as a privileged user.
It handles the downloading and/or parsing of system configuration data acquired from the network.
.Pp
See the configd man page for more information on what IPConfiguration does.
.Sh SEE ALSO
.Xr configd 8
.Sh HISTORY
IPConfigurationHelper first appeared in macOS 15.0.
