//   NOTE: this is a machine generated file--editing not recommended
//
// sm_vdatypes.h - class definitions for ASN.1 module VdaEnhancedTypes
//
//   This file was generated by snacc on Wed Jun 27 16:40:55 2001
//   UBC snacc by Mike Sample
//   A couple of enhancements made by IBM European Networking Center

#ifndef _sm_vdatypes_h_
#define _sm_vdatypes_h_


//------------------------------------------------------------------------------
// class declarations:

class BigIntegerStr;

//------------------------------------------------------------------------------
// class definitions:

/* [UNIVERSAL 2] IMPLICIT OCTET STRING */
class BigIntegerStr: public AsnOcts
{
public:
			BigIntegerStr(): AsnOcts() {}
			BigIntegerStr (const char *str): AsnOcts (str) {}
			BigIntegerStr (const char *str, const size_t len): AsnOcts (str, len) {}
			BigIntegerStr (const AsnOcts &o): AsnOcts (o) {}
  BigIntegerStr		&operator = (const BigIntegerStr &o)	{ ReSet (o); return *this; }
  BigIntegerStr		&operator = (const char *str)	{ ReSet (str); return *this; }
  virtual AsnType	*Clone() const;

  virtual AsnType	*Copy() const;

  AsnLen		BEnc (BUF_TYPE b);
  void			BDec (BUF_TYPE b, AsnLen &bytesDecoded, ENV_TYPE env);
  int			BEncPdu (BUF_TYPE b, AsnLen &bytesEncoded);
  int			BDecPdu (BUF_TYPE b, AsnLen &bytesDecoded);

};


//------------------------------------------------------------------------------
// externs for value defs

//------------------------------------------------------------------------------

#endif /* conditional include of sm_vdatypes.h */
