LIBRARY XI
VERSION LIBRARY_VERSION
EXPORTS
 XAllowDeviceEvents
 XChangeDeviceControl
 XChangeDeviceDontPropagateList
 XChangeDeviceKeyMapping
 XChangeFeedbackControl
 XChangeKeyboardDevice
 XChangePointerDevice
 XCloseDevice
 XDeviceBell
 XFreeDeviceControl
 XFreeDeviceList
 XFreeDeviceMotionEvents
 XFreeDeviceState
 XFreeFeedbackList
 XGetDeviceButtonMapping
 XGetDeviceControl
 XGetDeviceDontPropagateList
 XGetDeviceFocus
 XGetDeviceKeyMapping
 XGetDeviceModifierMapping
 XGetDeviceMotionEvents
 XGetExtensionVersion
 XGetFeedbackControl
 XGetSelectedExtensionEvents
 XGrabDevice
 XGrabDeviceButton
 XGrabDeviceKey
 XListInputDevices
 XOpenDevice
 XQueryDeviceState
 XSelectExtensionEvent
 XSendExtensionEvent
 XSetDeviceButtonMapping
 XSetDeviceFocus
 XSetDeviceMode
 XSetDeviceModifierMapping
 XSetDeviceValuators
 XUngrabDevice
 XUngrabDeviceButton
 XUngrabDeviceKey
 _xibadclass
 _xibaddevice
 _xibadevent
 _xibadmode
 _xidevicebusy
/* $Xorg: Xi-def.cpp,v 1.3 2000/08/17 19:45:58 cpqbld Exp $ */
