ServiceTypes = {
"accessone" : "Strix Systems 5S/AccessOne protocol" ,
"accountedge" : "MYOB AccountEdge" ,
"acrobatsrv" : "Adobe Acrobat" ,
"actionitems" : "ActionItems" ,
"addressbook" : "Address-O-Matic" ,
"adobe-vc" : "Adobe Version Cue" ,
"aecoretech" : "Apple Application Engineering Services" ,
"afpovertcp" : "Apple File Sharing" ,
"airprojector" : "AirProjector" ,
"animolmd" : "Animo License Manager" ,
"animobserver" : "Animo Batch Server" ,
"apple-ausend" : "Apple Audio Units" ,
"apple-midi" : "Apple MIDI" ,
"apple-sasl" : "Apple Password Server" ,
"applerdbg" : "Apple Remote Debug Services (OpenGL Profiler)" ,
"aquamon" : "AquaMon" ,
"asr" : "Apple Software Restore" ,
"async" : "address-o-sync" ,
"axis-video" : "Axis Video Cameras" ,
"auth" : "Authentication Service" ,
"beep" : "Xgrid Technology Preview" ,
"bfagent" : "BuildForge Agent" ,
"bigbangchess" : "Big Bang Chess" ,
"bigbangmancala" : "Big Bang Mancala" ,
"bootps" : "Bootstrap Protocol Server" ,
"bousg" : "Bag Of Unusual Strategy Games" ,
"bsqdea" : "Backup Simplicity" ,
"cheat" : "The Cheat" ,
"chess" : "Project Gridlock" ,
"chfts" : "Fluid Theme Server" ,
"clipboard" : "Clipboard Sharing" ,
"clscts" : "Oracle CLS Cluster Topology Service" ,
"collection" : "Published Collection Object" ,
"contactserver" : "Now Contact" ,
"corroboree" : "Corroboree Server" ,
"cpnotebook2" : "NoteBook 2" ,
"cuseeme" : "Conferencing Protocol" ,
"cvspserver" : "CVS PServer" ,
"cw-codetap" : "CodeWarrior HTI Xscale PowerTAP" ,
"cw-dpitap" : "CodeWarrior HTI DPI PowerTAP" ,
"cw-oncetap" : "CodeWarrior HTI OnCE PowerTAP" ,
"cw-powertap" : "CodeWarrior HTI COP PowerTAP" ,
"cytv" : "CyTV" ,
"daap" : "Digital Audio Access Protocol (iTunes)" ,
"dacp" : "Digital Audio Control Protocol (iTunes)" ,
"difi" : "EyeHome" ,
"distcc" : "Distributed Compiler" ,
"dns-llq" : "DNS Long-Lived Queries" ,
"dns-sd" : "DNS Service Discovery" ,
"dns-update" : "DNS Dynamic Update Service" ,
"domain" : "Domain Name Server" ,
"dossier" : "Vortimac Dossier Protocol" ,
"dpap" : "Digital Photo Access Protocol (iPhoto)" ,
"dropcopy" : "DropCopy" ,
"earphoria" : "Earphoria" ,
"ebms" : "ebXML Messaging" ,
"ecms" : "Northrup Grumman/Mission Systems/ESL Data Flow Protocol" ,
"ebreg" : "ebXML Registry" ,
"ecbyesfsgksc" : "Net Monitor Anti-Piracy Service" ,
"eheap" : "Interactive Room Software Infrastructure (Event Sharing)" ,
"embrace" : "DataEnvoy" ,
"eppc" : "Remote AppleEvents" ,
"eventserver" : "Now Up-to-Date" ,
"example" : "Example Service Type" ,
"exec" : "Remote Process Execution" ,
"facespan" : "FaceSpan" ,
"fairview" : "Fairview Device Identification" ,
"faxstfx" : "FAXstf" ,
"feed-sharing" : "NetNewsWire 2.0" ,
"fish" : "Fish" ,
"fjork" : "Fjork" ,
"fmpro-internal" : "FileMaker Pro" ,
"fontagentnode" : "FontAgent Pro" ,
"freehand" : "FreeHand MusicPad Pro Interface Protocol" ,
"ftp" : "File Transfer" ,
"ftpcroco" : "Crocodile FTP Server" ,
"fv-cert" : "Fairview Certificate" ,
"fv-key" : "Fairview Key" ,
"fv-time" : "Fairview Time/Date" ,
"gbs-smp" : "SnapMail" ,
"gbs-stp" : "SnapTalk" ,
"gforce-ssmp" : "G-Force Control via SoundSpectrum's SSMP TCP Protocol" ,
"glrdrvmon" : "OpenGL Driver Monitor" ,
"gpnp" : "Grid Plug and Play" ,
"grillezvous" : "Roxio ToastAnywhere(tm) Recorder Sharing" ,
"guid" : "Special service type for resolving by GUID (Globally Unique Identifier)" ,
"h323" : "H.323 Real-time audio, video and data communication call setup protocol" ,
"hmcp" : "Home Media Control Protocol" ,
"http" : "World Wide Web HTML-over-HTTP" ,
"hotwayd" : "Hotwayd" ,
"hydra" : "SubEthaEdit" ,
"iax" : "Inter Asterisk eXchange, ease-of-use NAT friendly open VoIP protocol" ,
"ibiz" : "iBiz Server" ,
"ica-networking" : "Image Capture Networking" ,
"ichalkboard" : "iChalk" ,
"ichat" : "iChat 1.0" ,
"iconquer" : "iConquer" ,
"ifolder" : "Published iFolder" ,
"ihouse" : "Idle Hands iHouse Protocol" ,
"ilynx" : "iLynX" ,
"imap" : "Internet Message Access Protocol" ,
"imidi" : "iMidi" ,
"ipbroadcaster" : "IP Broadcaster" ,
"ipp" : "IPP (Internet Printing Protocol)" ,
"irmc" : "Intego Remote Management Console" ,
"isparx" : "iSparx" ,
"ispq-vc" : "iSpQ VideoChat" ,
"ishare" : "iShare" ,
"isticky" : "iSticky" ,
"istorm" : "iStorm" ,
"iwork" : "iWork Server" ,
"jeditx" : "Jedit X" ,
"jini" : "Jini Service Discovery" ,
"kerberos" : "Kerberos" ,
"kerberos-adm" : "Kerberos Administration" ,
"lan2p" : "Lan2P Peer-to-Peer Network Protocol" ,
"ldap" : "Lightweight Directory Access Protocol" ,
"liaison" : "Liaison" ,
"logicnode" : "Logic Pro Distributed Audio" ,
"login" : "Remote Login a la Telnet" ,
"lontalk" : "LonTalk over IP (ANSI 852)" ,
"lonworks" : "Echelon LNS Remote Client" ,
"macfoh-remote" : "MacFOH Remote" ,
"macminder" : "Mac Minder" ,
"mbconsumer" : "MediaBroker++ Consumer" ,
"mbproducer" : "MediaBroker++ Producer" ,
"mbserver" : "MediaBroker++ Server" ,
"mimer" : "Mimer SQL Engine" ,
"moneyworks" : "MoneyWorks Gold and MoneyWorks Datacentre network service" ,
"moodring" : "Bonjour Mood Ring tutorial program" ,
"mp3sushi" : "MP3 Sushi" ,
"mysync" : "MySync Protocol" ,
"mttp" : "MenuTunes Sharing" ,
"ncbroadcast" : "Network Clipboard Broadcasts" ,
"ncdirect" : "Network Clipboard Direct Transfers" ,
"ncsyncserver" : "Network Clipboard Sync Server" ,
"net-assistant" : "Apple Remote Desktop" ,
"newton-dock" : "Escale" ,
"nfs" : "Network File System - Sun Microsystems" ,
"nssocketport" : "DO over NSSocketPort" ,
"ntp" : "Network Time Protocol" ,
"ntx" : "Tenasys" ,
"odabsharing" : "OD4Contact" ,
"omni-bookmark" : "OmniWeb" ,
"openbase" : "OpenBase SQL" ,
"p2pchat" : "Peer-to-Peer Chat (Sample Java Bonjour application)" ,
"pdl-datastream" : "Printer Page Description Language Data Stream (vendor-specific)" ,
"pgpkey-hkp" : "Horowitz Key Protocol (HKP)" ,
"pgpkey-https" : "PGP Keyserver using HTTP/1.1" ,
"pgpkey-https" : "PGP Keyserver using HTTPS" ,
"pgpkey-ldap" : "PGP Keyserver using LDAP" ,
"pgpkey-mailto" : "PGP Key submission using SMTP" ,
"poch" : "Parallel OperatiOn and Control Heuristic (Pooch)" ,
"pop3" : "Post Office Protocol - Version 3" ,
"postgresql" : "PostgreSQL Server" ,
"powereasy-erp" : "PowerEasy ERP" ,
"powereasy-pos" : "PowerEasy Point of Sale" ,
"presence" : "iChat AV" ,
"printer" : "Spooler " ,
"ptnetprosrv2" : "PTNetPro Service" ,
"ptp" : "Picture Transfer Protocol" ,
"ptp-req" : "PTP Initiation Request Protocol" ,
"qttp" : "QuickTime Transfer Protocol" ,
"quinn" : "Quinn Game Server" ,
"raop" : "Remote Audio Output Protocol (AirTunes)" ,
"rce" : "PowerCard" ,
"realplayfavs" : "RealPlayer Shared Favorites" ,
"renderpipe" : "ARTvps RenderDrive/PURE Renderer Protocol" ,
"rendezvouspong" : "RendezvousPong" ,
"riousbprint" : "Remote I/O USB Printer Protocol" ,
"rfb" : "Remote Frame Buffer (used by VNC)" ,
"roku-rcp" : "Roku Control Protocol" ,
"rsync" : "Rsync" ,
"rtsp" : "Real Time Streaming Protocol" ,
"rubygems" : "RubyGems GemServer" ,
"safarimenu" : "Safari Menu" ,
"sallingclicker" : "Salling Clicker Service" ,
"schick" : "Schick" ,
"scone" : "Scone" ,
"sdsharing" : "Speed Download" ,
"see" : "SubEthaEdit 2" ,
"seeCard" : "seeCard" ,
"serendipd" : "serendiPd Shared Patches for Pure Data" ,
"servermgr" : "Mac OS X Server Admin" ,
"services" : "DNS Service Discovery" ,
"sftp-ssh" : "Secure File Transfer Protocol over SSH" ,
"shell" : "like exec, but automatic authentication is performed as for login server." ,
"shipsgm" : "Swift Office Ships" ,
"shipsinvit" : "Swift Office Ships" ,
"shoutcast" : "Nicecast" ,
"sip" : "Session Initiation Protocol, signalling protocol for VoIP" ,
"skype" : "Skype" ,
"slimcli" : "SliMP3 Server Command-Line Interface" ,
"slimhttp" : "SliMP3 Server Web Interface" ,
"soap" : "Simple Object Access Protocol" ,
"spearcat" : "sPearCat Host Discovery" ,
"spike" : "Shared Clipboard Protocol" ,
"spincrisis" : "Spin Crisis" ,
"spl-itunes" : "launchTunes" ,
"spr-itunes" : "netTunes" ,
"ssh" : "SSH Remote Login Protocol" ,
"ssscreenshare" : "Screen Sharing" ,
"strateges" : "Strateges" ,
"sge-exec" : "Sun Grid Engine (Execution Host)" ,
"sge-qmaster" : "Sun Grid Engine (Master)" ,
"stickynotes" : "Sticky Notes" ,
"submission" : "Message Submission" ,
"supple" : "Supple Service protocol" ,
"swcards" : "Signwave Card Sharing Protocol" ,
"sxqdea" : "Synchronize! Pro X" ,
"sybase-tds" : "Sybase Server" ,
"syncqdea" : "Synchronize! X Plus 2.0" ,
"teamlist" : "ARTIS Team Task" ,
"teleport" : "teleport" ,
"telnet" : "Telnet" ,
"tftp" : "Trivial File Transfer" ,
"ticonnectmgr" : "TI Connect Manager Discovery Service" ,
"timbuktu" : "Timbuktu" ,
"tinavigator" : "TI Navigator Hub 1.0 Discovery Service" ,
"tivo-hme" : "TiVo Home Media Engine Protocol" ,
"tivo-music" : "TiVo Music Protocol" ,
"tivo-photos" : "TiVo Photos Protocol" ,
"tivo-videos" : "TiVo Videos Protocol" ,
"tryst" : "Tryst" ,
"uddi" : "Universal Description, Discovery and Integration" ,
"uddi-inq" : "Universal Description, Discovery and Integration Inquiry" ,
"uddi-pub" : "Universal Description, Discovery and Integration Publishing" ,
"uddi-sub" : "Universal Description, Discovery and Integration Subscription" ,
"uddi-sec" : "Universal Description, Discovery and Integration Security" ,
"upnp" : "Universal Plug and Play" ,
"utest" : "uTest" ,
"volley" : "Volley" ,
"vos" : "Virtual Object System (using VOP/TCP)" ,
"vue4rendercow" : "VueProRenderCow" ,
"webdav" : "World Wide Web Distributed Authoring and Versioning" ,
"whamb" : "Whamb" ,
"wired" : "Wired Server" ,
"workstation" : "Workgroup Manager" ,
"wormhole" : "Roku Cascade Wormhole Protocol" ,
"workgroup" : "Novell collaboration workgroup" ,
"ws" : "Web Services" ,
"xgrid" : "Xgrid" ,
"xmpp-client" : "XMPP Client Connection" ,
"xmpp-server" : "XMPP Server Connection" ,
"xsanclient" : "Xsan Client" ,
"xsanserver" : "Xsan Server" ,
"xsansystem" : "Xsan System" ,
"xserveraid" : "XServe Raid" ,
"xsync" : "Xserve RAID Synchronization" ,
"xtimelicence" : "xTime License" ,
"xtshapro" : "xTime Project" ,
"xul-http" : "XUL (XML User Interface Language) transported over HTTP" ,
}
