/* config.h.  Generated automatically by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader 2.13.  */
/*

acconfig.h - template used by autoheader to create config.h.in
config.h.in - used by autoconf to create config.h
config.h - created by autoconf; contains defines generated by autoconf

*/


/* Define if you have the <openssl/engine.h> header file.  */
#define HAVE_OPENSSL_ENGINE_H 1

/* Define if you have the <openssl/err.h> header file.  */
#define HAVE_OPENSSL_ERR_H 1

#ifndef HAVE_SNPRINTF
#define HAVE_LOCAL_SNPRINTF
#define snprintf lrad_snprintf
#endif

#ifndef HAVE_VSNPRINTF
#define HAVE_LOCAL_SNPRINTF
#define vsnprintf lrad_vsnprintf
#endif
