.\" -*- nroff -*-
.TH AMAVISD-AGENT 8 amavisd-agent
.\" 
.\" # This is amavisd-agent, a demo program to display
.\" # SNMP-like counters updated by amavisd-new.
.\" #
.\" # Author: Mark Martinec <mark.martinec@ijs.si>
.\" # Copyright (C) 2004  Mark Martinec,  All Rights Reserved.
.\" #
.\" # Redistribution and use in source and binary forms, with or without
.\" # modification, are permitted provided that the following conditions are met:
.\" #
.\" # * Redistributions of source code must retain the above copyright notice,
.\" #   this list of conditions and the following disclaimer.
.\" # * Redistributions in binary form must reproduce the above copyright notice,
.\" #   this list of conditions and the following disclaimer in the documentation
.\" #   and/or other materials provided with the distribution.
.\" # * Neither the name of the author, nor the name of the "Jozef Stefan"
.\" #   Institute, nor the names of contributors may be used to endorse or
.\" #   promote products derived from this software without specific prior
.\" #   written permission.
.\" #
.\" # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" # "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" # LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\" # PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
.\" # OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\" # EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" # PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
.\" # OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" # WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\" # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" #
.\" #(the license above is the new BSD license, and pertains to this program only)
.\" #
.\" # Patches and problem reports are welcome.
.\" # The latest version of this program is available at:
.\" #   http://www.ijs.si/software/amavisd/
.\" 
.\" $Id: amavisd-agent.8,v 1.1 2006/07/19 22:29:05 dasenbro Exp $
.SH NAME
amavisd-agent \- Amavisd agent
.SH SYNOPSIS
.B amavisd-agent
.SH DESCRIPTION
.I Amavisd-agent
SNMP-like counters updated by amavisd-new.
.PP
.SH OPTIONS
.TP
.BI " Debug"
Debug option.
.SH FILES
.TP
.B N/A
.SH SEE ALSO
.PP
\fB\fR
