.\"	from: @(#)amavisd.8
.\"
.Dd February 25, 2010
.Dt AMAVISD 8
.Os
.Sh NAME
.Nm amavisd
.Nd Interface between Mail Transfer Agent (MTA) and virus scanner & content filters
.Sh SYNOPSIS
.Nm
.Op Fl hV
.Op Fl u Ar user-id
.Op Fl g Ar group-id
.Op Fl c Ar config-file
.Op Fl i Ar instance-name
.Op Fl m Ar max-servers
.br
.Op Fl p Ar listen-port-or-socket
.Op Fl L Ar lock-file
.Op Fl P Ar pid-file
.Op Fl H Ar home-dir
.Op Fl D Ar db-home-dir
.Op Fl Q Ar quarantine-dir
.Op Fl R Ar chroot-dir
.Op Fl S Ar helpers-home-dir
.Op Fl T Ar tempbase-dir
.Op start | stop | reload | debug | debug-sa | foreground | showkeys {domains} | testkeys {domains} | genrsa file-name [nbits] convert-keysfile file-name
.Sh DESCRIPTION
.Nm
is a high-performance interface between Mail Transfer Agent (MTA) and virus scanners and/or junk-mail scanners.
.Pp
This is the amavisd-new incarnation of amavisd. It is a performance-enhanced and feature-enriched version of the original amavisd program.
.Pp
Amavisd works as a SMTP proxy. Email is fed to it through SMTP, processed, and then fed back to the MTA through a new SMTP connection. There is no buffering to disk by amavis, it will report that the transfer was sucessfull only after the forwarding MTA has accepted the message.
.Sh OPTIONS
The following options can be used with
.Nm :
.Bl -tag -width indent
.It Fl u Ar user-id
Run using this user id.
.It Fl g Ar group-id
Run using this group id.
.It Fl c Ar config-file
Use the specified configuration file instead of the default
.Pa /etc/amavisd.conf
.It Fl i Ar instance-name
.It Fl m Ar max-servers
Maximum number of pre-forked children
.It Fl p Ar listen-port-or-socket
Listen on specified local TCP port(s) instead of the default
.Pa 10024,10026
.It Fl L Ar lock-file
Use the specified lock file instead of the default
.Pa /var/amavis/amavisd.lock
.It Fl P Ar pid-file
Use the specified PID file instead of the default
.Pa /var/amavis/amavisd.pid
.It Fl H Ar home-dir
Use the specified home directory instead of the default
.Pa /var/amavis
.It Fl D Ar db-home-dir
Use the specified directory for for bdb, nanny, cache, snmp and databases instead of the default
.Pa /var/amavis/db
.It Fl Q Ar quarantine-dir
Use the specified quarantine directory instead of the default
.Pa /var/virusmails
.It Fl R Ar chroot-dir
Use the specified chroot directory instead of the default
.Pa /var/amavis
.It Fl S Ar helpers-home-dir
Use the specified chroot directory instead of the default
.Pa /var/amavis
.It Fl T Ar tempbase-dir
Use the specified temporary directory instead of the default
.Pa /var/amavis/tmp
.El
.Sh FILES
.Bl -tag -width /etc/amavisd.conf -compact
.It Pa /etc/amavisd.conf
.It Pa /var/db
.It Pa /var/tmp
.It Pa /var/amavis
.It Pa /var/amavis/amavisd.lock
.It Pa /var/amavis/amavisd.pid
.It Pa /var/virusmails
.Nm
configuration file
.El
.Sh "SEE ALSO"
.Xr postfix 1
.Xr spamassassin 1
.Xr clamd 8
