.TH distccd 1 "2 July 2002"
.SH NAME
distccd \- distributed C/C++ compiler server
.SH SYNOPSIS
.B distccd
.SH DESCRIPTION
This manual page is intentionally left almost blank.  
.PP
.I distccd 
may be used either from inetd or as a stand-alone server.  For a brief
summary of command-line options, type
.PP
.I distccd --help
.PP
See the User Manual (available as HTML, Info, PS, and PDF) for more
information.  The manual and other documentation is available from
.I http://distcc.samba.org/
.SH AUTHOR
distcc was written by Martin Pool <http://sourcefrog.net/mbp/>
.SH LICENCE
You are free to use distcc.  It may be copied, modified or distributed
only under the terms of the GNU General Public Licence version 2 or
later.  A copy of the GPL is included in the file COPYING.
.SH SEE ALSO
distcc(1), ccache(1), gcc(1), make(1)
.I http://distcc.samba.org/
