/* src/include/autoconf.h.  Generated by configure.  */
/* src/include/autoconf.h.in.  Generated automatically from configure.in by autoheader 2.13.  */
/*

acconfig.h - template used by autoheader to create config.h.in
config.h.in - used by autoconf to create config.h
config.h - created by autoconf; contains defines generated by autoconf

*/


/* Define if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* #undef _ALL_SOURCE */
#endif

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef gid_t */

/* Define if you have <sys/wait.h> that is POSIX.1 compatible.  */
#define HAVE_SYS_WAIT_H 1

/* Define to `long' if <sys/types.h> doesn't define.  */
/* #undef off_t */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef pid_t */

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef uid_t */

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
#define WORDS_BIGENDIAN 1

/* style of gethost*_r functions */
#define GNUSTYLE 1
#define SYSVSTYLE 2
#define BSDSTYLE 3
#define GETHOSTBYADDRRSTYLE BSDSTYLE
#define GETHOSTBYNAMERSTYLE BSDSTYLE

/* style of ctime_r function */
#define POSIXSTYLE 1
#define SOLARISSTYLE 2
#define CTIMERSTYLE POSIXSTYLE

/* Do we have the crypt function ? */
#define HAVE_CRYPT 1

/* Include support for Ascend binary filter attributes */
#define ASCEND_BINARY 1

/* socklen_t is generally 'int' on systems which don't use it */
/* #undef socklen_t */

/* uint8_t should be the canonical 'octet' for network traffic */
/* #undef uint8_t */

/* uint16_t should be the canonical '2 octets' for network traffic */
/* #undef uint16_t */

/* uint32_t should be the canonical 'network integer' */
/* #undef uint32_t */

/* Include SNMP subagent */
/* #undef WITH_SNMP */

/* Define if you have the <ucd-snmp/asn1.h>, <ucd-snmp/snmp_impl.h> and <ucd-snmp/snmp.h> header file.  */
/* #undef HAVE_UCD_SNMP_ASN1_SNMP_SNMPIMPL_H */

/* Define if you have the <asn1.h>, <snmp_impl.h> and <snmp.h> header file.  */
/* #undef HAVE_ASN1_SNMP_SNMPIMPL_H */

/* Define if you have the snmp library (-lsnmp).  */
/* #undef HAVE_LIBSNMP */

/* define this if we have the <regex.h> header file */
#define HAVE_REGEX_H 1

/* define this if we have REG_EXTENDED (from <regex.h>) */
#define HAVE_REG_EXTENDED 1

/* define to something if you don't have ut_xtime in struct utmpx */
#define ut_xtime ut_tv.tv_sec

/* define if you have OSFC2 authentication */
/* #undef OSFC2 */

/* define if you have OSFSIA authentication */
/* #undef OSFSIA */

/* define if you have IP_PKTINFO (Linux) */
/* #undef HAVE_IP_PKTINFO */

/* define if you want udpfromto */
/* #undef WITH_UDPFROMTO */

/* Define if you have the closefrom function.  */
/* #undef HAVE_CLOSEFROM */

/* Define if you have the ctime_r function.  */
#define HAVE_CTIME_R 1

/* Define if you have the gethostname function.  */
#define HAVE_GETHOSTNAME 1

/* Define if you have the getopt_long function.  */
#define HAVE_GETOPT_LONG 1

/* Define if you have the getusershell function.  */
#define HAVE_GETUSERSHELL 1

/* Define if you have the gmtime_r function.  */
#define HAVE_GMTIME_R 1

/* Define if you have the inet_aton function.  */
#define HAVE_INET_ATON 1

/* Define if you have the inet_ntop function.  */
#define HAVE_INET_NTOP 1

/* Define if you have the inet_pton function.  */
#define HAVE_INET_PTON 1

/* Define if you have the initgroups function.  */
#define HAVE_INITGROUPS 1

/* Define if you have the localtime_r function.  */
#define HAVE_LOCALTIME_R 1

/* Define if you have the lockf function.  */
#define HAVE_LOCKF 1

/* Define if you have the pthread_sigmask function.  */
#define HAVE_PTHREAD_SIGMASK 1

/* Define if you have the setlinebuf function.  */
#define HAVE_SETLINEBUF 1

/* Define if you have the setsid function.  */
#define HAVE_SETSID 1

/* Define if you have the setvbuf function.  */
#define HAVE_SETVBUF 1

/* Define if you have the sigaction function.  */
#define HAVE_SIGACTION 1

/* Define if you have the sigprocmask function.  */
#define HAVE_SIGPROCMASK 1

/* Define if you have the snprintf function.  */
#define HAVE_SNPRINTF 1

/* Define if you have the strcasecmp function.  */
#define HAVE_STRCASECMP 1

/* Define if you have the strncasecmp function.  */
#define HAVE_STRNCASECMP 1

/* Define if you have the strsep function.  */
#define HAVE_STRSEP 1

/* Define if you have the strsignal function.  */
#define HAVE_STRSIGNAL 1

/* Define if you have the vsnprintf function.  */
#define HAVE_VSNPRINTF 1

/* Define if you have the <arpa/inet.h> header file.  */
#define HAVE_ARPA_INET_H 1

/* Define if you have the <crypt.h> header file.  */
/* #undef HAVE_CRYPT_H */

/* Define if you have the <dirent.h> header file.  */
#define HAVE_DIRENT_H 1

/* Define if you have the <dlfcn.h> header file.  */
#define HAVE_DLFCN_H 1

/* Define if you have the <errno.h> header file.  */
#define HAVE_ERRNO_H 1

/* Define if you have the <fcntl.h> header file.  */
#define HAVE_FCNTL_H 1

/* Define if you have the <getopt.h> header file.  */
#define HAVE_GETOPT_H 1

/* Define if you have the <inttypes.h> header file.  */
#define HAVE_INTTYPES_H 1

/* Define if you have the <malloc.h> header file.  */
/* #undef HAVE_MALLOC_H */

/* Define if you have the <ndir.h> header file.  */
/* #undef HAVE_NDIR_H */

/* Define if you have the <netdb.h> header file.  */
#define HAVE_NETDB_H 1

/* Define if you have the <netinet/in.h> header file.  */
#define HAVE_NETINET_IN_H 1

/* Define if you have the <openssl/crypto.h> header file.  */
#define HAVE_OPENSSL_CRYPTO_H 1

/* Define if you have the <openssl/engine.h> header file.  */
#define HAVE_OPENSSL_ENGINE_H 1

/* Define if you have the <openssl/err.h> header file.  */
#define HAVE_OPENSSL_ERR_H 1

/* Define if you have the <openssl/ssl.h> header file.  */
#define HAVE_OPENSSL_SSL_H 1

/* Define if you have the <prot.h> header file.  */
/* #undef HAVE_PROT_H */

/* Define if you have the <pthread.h> header file.  */
#define HAVE_PTHREAD_H 1

/* Define if you have the <resource.h> header file.  */
/* #undef HAVE_RESOURCE_H */

/* Define if you have the <semaphore.h> header file.  */
#define HAVE_SEMAPHORE_H 1

/* Define if you have the <sia.h> header file.  */
/* #undef HAVE_SIA_H */

/* Define if you have the <siad.h> header file.  */
/* #undef HAVE_SIAD_H */

/* Define if you have the <signal.h> header file.  */
#define HAVE_SIGNAL_H 1

/* Define if you have the <stdint.h> header file.  */
#define HAVE_STDINT_H 1

/* Define if you have the <stdio.h> header file.  */
#define HAVE_STDIO_H 1

/* Define if you have the <sys/dir.h> header file.  */
/* #undef HAVE_SYS_DIR_H */

/* Define if you have the <sys/fcntl.h> header file.  */
#define HAVE_SYS_FCNTL_H 1

/* Define if you have the <sys/ndir.h> header file.  */
/* #undef HAVE_SYS_NDIR_H */

/* Define if you have the <sys/prctl.h> header file.  */
/* #undef HAVE_SYS_PRCTL_H */

/* Define if you have the <sys/security.h> header file.  */
/* #undef HAVE_SYS_SECURITY_H */

/* Define if you have the <sys/select.h> header file.  */
#define HAVE_SYS_SELECT_H 1

/* Define if you have the <sys/socket.h> header file.  */
#define HAVE_SYS_SOCKET_H 1

/* Define if you have the <sys/stat.h> header file.  */
#define HAVE_SYS_STAT_H 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <sys/types.h> header file.  */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <sys/wait.h> header file.  */
#define HAVE_SYS_WAIT_H 1

/* Define if you have the <syslog.h> header file.  */
#define HAVE_SYSLOG_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the <utmp.h> header file.  */
#define HAVE_UTMP_H 1

/* Define if you have the <utmpx.h> header file.  */
#define HAVE_UTMPX_H 1

/* Define if you have the nsl library (-lnsl).  */
/* #undef HAVE_LIBNSL */

/* Define if you have the resolv library (-lresolv).  */
#define HAVE_LIBRESOLV 1

/* Define if you have the socket library (-lsocket).  */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the crypto library (-lcrypto). */
#define HAVE_LIBCRYPTO 1

/* Define to 1 if you have the ssl library (-lssl). */
#define HAVE_LIBSSL 1

/* Some versions of glibc need this defined for pread/pwrite. */
/* #undef _GNU_SOURCE */

