.Dd May 23, 2002
.Dt ip6 8
.Os
.Sh NAME
.Nm ip6
.Nd Enable or disable IPv6 on active interfaces
.Sh SYNOPSIS
.Nm
.Op Fl ax
.Op Fl ud interface
.Sh DESCRIPTION
.Nm
can be used to start up or shut down IPv6 on active interfaces. 
When IPv6 is enabled on an interface the protocol is attached to the
interface, at which point the default settings in the kernel allow it 
to acquire a link-local address and accept router advertisements. 
Disabling detaches the protocol from the interface.
.Pp
Possible options are:
.Bl -tag -width xxx
.It Fl a
Start IPv6 on all interfaces.
.It Fl x
Stop IPv6 on all interfaces.
.It Fl u [interface]
Start IPv6 on interface.
.It Fl d [interface]
Stop IPv6 on interface.
.El
.Pp
.Sh REQUIREMENTS
You need support for IPv6 in your kernel. This is provided beginning 
with Darwin Kernel Version 6.0.
.Pp
.Sh CONFIGURATION
The default IPv6 configuration for an interface assigns a link-local 
address to it and sets the interface to receive router advertisements. 
No further configuration is necessary for basic functionality. 
However, various settings can be modified by using sysctl.
Pp
.Sh SEE ALSO
.Xr stf 4 ,
IPv6 Documentation at
.Pa http://www.netbsd.org/Documentation/network/ipv6/ ,
RFC 3068.
