Project = fpr
Install_Dir = /usr/bin

CFILES = fpr.c
MANPAGES = fpr.1

Extra_CC_Flags = -Wall -Werror -mdynamic-no-pic
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
