---
abstract: 'Log4j implementation for Perl'
author:
  - 'Mike Schilli <m@perlmeister.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Log4perl
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: 0.82
  Test::More: 0.45
resources:
  repository: http://github.com/mschilli/log4perl
  x_MailingList: mailto:log4perl-devel@lists.sourceforge.net
version: 1.40
