# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/AQnrcGnc70/asia.  Olson data version 2010b
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Asia::Dhaka;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Asia::Dhaka::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY,
59611139900,
DateTime::TimeZone::NEG_INFINITY,
59611161600,
21700,
0,
'LMT'
    ],
    [
59611139900,
61244100400,
59611161100,
61244121600,
21200,
0,
'HMT'
    ],
    [
61244100400,
61263624600,
61244123800,
61263648000,
23400,
0,
'BURT'
    ],
    [
61263624600,
61273045800,
61263644400,
61273065600,
19800,
0,
'IST'
    ],
    [
61273045800,
61559544600,
61273069200,
61559568000,
23400,
0,
'BURT'
    ],
    [
61559544600,
62174455200,
61559566200,
62174476800,
21600,
0,
'DACT'
    ],
    [
62174455200,
63366429600,
62174476800,
63366451200,
21600,
0,
'BDT'
    ],
    [
63366429600,
63381114000,
63366451200,
63381135600,
21600,
0,
'BDT'
    ],
    [
63381114000,
63397962000,
63381139200,
63397987200,
25200,
1,
'BDST'
    ],
    [
63397962000,
63405738000,
63397983600,
63405759600,
21600,
0,
'BDT'
    ],
    [
63405738000,
63424227600,
63405763200,
63424252800,
25200,
1,
'BDST'
    ],
    [
63424227600,
63437274000,
63424249200,
63437295600,
21600,
0,
'BDT'
    ],
    [
63437274000,
63455763600,
63437299200,
63455788800,
25200,
1,
'BDST'
    ],
    [
63455763600,
63468896400,
63455785200,
63468918000,
21600,
0,
'BDT'
    ],
    [
63468896400,
63487386000,
63468921600,
63487411200,
25200,
1,
'BDST'
    ],
    [
63487386000,
63500432400,
63487407600,
63500454000,
21600,
0,
'BDT'
    ],
    [
63500432400,
63518922000,
63500457600,
63518947200,
25200,
1,
'BDST'
    ],
    [
63518922000,
63531968400,
63518943600,
63531990000,
21600,
0,
'BDT'
    ],
    [
63531968400,
63550458000,
63531993600,
63550483200,
25200,
1,
'BDST'
    ],
    [
63550458000,
63563504400,
63550479600,
63563526000,
21600,
0,
'BDT'
    ],
    [
63563504400,
63581994000,
63563529600,
63582019200,
25200,
1,
'BDST'
    ],
    [
63581994000,
63595126800,
63582015600,
63595148400,
21600,
0,
'BDT'
    ],
    [
63595126800,
63613616400,
63595152000,
63613641600,
25200,
1,
'BDST'
    ],
    [
63613616400,
63626662800,
63613638000,
63626684400,
21600,
0,
'BDT'
    ],
    [
63626662800,
63645152400,
63626688000,
63645177600,
25200,
1,
'BDST'
    ],
    [
63645152400,
63658198800,
63645174000,
63658220400,
21600,
0,
'BDT'
    ],
    [
63658198800,
63676688400,
63658224000,
63676713600,
25200,
1,
'BDST'
    ],
    [
63676688400,
63689734800,
63676710000,
63689756400,
21600,
0,
'BDT'
    ],
    [
63689734800,
63708224400,
63689760000,
63708249600,
25200,
1,
'BDST'
    ],
    [
63708224400,
63721357200,
63708246000,
63721378800,
21600,
0,
'BDT'
    ],
    [
63721357200,
63739846800,
63721382400,
63739872000,
25200,
1,
'BDST'
    ],
    [
63739846800,
63752893200,
63739868400,
63752914800,
21600,
0,
'BDT'
    ],
    [
63752893200,
63771382800,
63752918400,
63771408000,
25200,
1,
'BDST'
    ],
];

sub olson_version { '2010b' }

sub has_dst_changes { 13 }

sub _max_year { 2020 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}

sub _last_offset { 21600 }

my $last_observance = bless( {
  'format' => 'BD%sT',
  'gmtoff' => '6:00',
  'local_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 733408,
    'local_rd_secs' => 0,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 733408,
    'utc_rd_secs' => 0,
    'utc_year' => 2010
  }, 'DateTime' ),
  'offset_from_std' => 0,
  'offset_from_utc' => 21600,
  'until' => [],
  'utc_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 733407,
    'local_rd_secs' => 64800,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 733407,
    'utc_rd_secs' => 64800,
    'utc_year' => 2009
  }, 'DateTime' )
}, 'DateTime::TimeZone::OlsonDB::Observance' )
;
sub _last_observance { $last_observance }

my $rules = [
  bless( {
    'at' => '23:00',
    'from' => '2010',
    'in' => 'Mar',
    'letter' => 'S',
    'name' => 'Dhaka',
    'offset_from_std' => 3600,
    'on' => '31',
    'save' => '1:00',
    'to' => 'max',
    'type' => undef
  }, 'DateTime::TimeZone::OlsonDB::Rule' ),
  bless( {
    'at' => '0:00',
    'from' => '2010',
    'in' => 'Nov',
    'letter' => '',
    'name' => 'Dhaka',
    'offset_from_std' => 0,
    'on' => '1',
    'save' => '0',
    'to' => 'max',
    'type' => undef
  }, 'DateTime::TimeZone::OlsonDB::Rule' )
]
;
sub _rules { $rules }


1;

