.\" Man page for apropos 
.\"
.\" Copyright (c) 1990, 1991, John W. Eaton.
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the man 1.0
.\" distribution.  
.\"
.\" John W. Eaton
.\" jwe@che.utexas.edu
.\" Department of Chemical Engineering
.\" The University of Texas at Austin
.\" Austin, Texas  78712
.\"
.\" edited and translated to danish by Bo Vagner Hoejer 1996
.\" email bo@petshop.ping.dk - bo@image.dk
.\"
.TH apropos 1 "15. Januar 1991" "da" "Linux brugerkommandoer" 
.LO 1
.SH NAVN
apropos \- gennemsøg 'whatis' databasen for tekststrenge
.SH SYNTAKS
.BI apropos
nøgleord ...
.SH BESKRIVELSE
apropos gennemsøger et set af databasefiler, som indeholder korte beskrivelser 
af systemets kommandoer, efter nøgleordet og udskriver resultatet paa standard 
udskriftsenheden.
.SH "SE OGSÅ"
whatis(1), man(1).
