INSTALL_PERMISSIONS = 0555  # If set, 'install' chmod's executable to this
install-daemon:
	install -d $(DSTROOT)/usr/sbin
	install -c -m 555 "$(DSTROOT)/sbin/rtsol" "$(DSTROOT)/usr/sbin/rtsold"

install-man-page:
	install -d "$(DSTROOT)/usr/share/man/man8"
	install -c -m 644 rtsol.8 "$(DSTROOT)/usr/share/man/man8/rtsol.8"
	install -c -m 644 rtsol.8 "$(DSTROOT)/usr/share/man/man8/rtsold.8"

