#!/bin/bash 
RH=ftp.ccil.org
p=`\
echo dir /pub/esr/fetchmail/f\*src.rpm \
   | ftp $RH \
   | grep /pub/esr/fetchmail/fetchmail-[45] \
   | tail -1`
#p='-rw-r--r-- 1 23 wheel 478424 Dec 18 03:54 /pub/esr/fetchmail/fetchmail-4.7.1-1.src.rpm'
#echo $p | sed -e "s=^.^/pub=pub="
p1=`echo $p | sed -e "s=^.*/pub=pub="`
#echo $p1
#basename  $p1
#dirname $p1
d=`dirname $p1`
f=`basename $p1`
cd /work/incoming
email=$LOGNAME\@`hostname`
ftp -n <<ZZ
open $RH
user anonymous $email
cd /$d
get $f
bye
ZZ
rpm -K $f >/dev/null 2>&1 \
   || {
         rpm -K $f 2>&1 | mail $email -s "error getting $f"
         exit 
      }
rpm --rebuild  $f 2>&1 |\
   mail $email -s "Rebuilding $f"
