#
# Generated by the Apple Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = pb_makefiles

PROJECTVERSION = 2.8
PROJECT_TYPE = Bundle

GLOBAL_RESOURCES = aggregate.make app.make build.make bundle.make\
                   commands-MACOS.make\
                   common.make compatibility.make\
                   depend.make flags.make framework.make\
                   implicitrules.make install.make installhdrs.make\
                   installsrc.make javapackage.make javawrapper.make library.make\
                   palette.make prebuild.make recursion.make\
                   reinstall.make subproj.make tool.make versions.make\
                   wrapped-common.make platform-variables.make\
                   platform-variables-extra.make

CFILES = clonehdrs.c dotdotify.c newer.c readdir.c fastcp.c frameworkFlags.c ofileListTool.c

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble BUGS.rtf\
            platform.make \
            next-cvs.make next-cvs_project_version.sh


MAKEFILEDIR = .
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = bundle.make
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)
BUNDLE_EXTENSION = bundle


PDO_UNIX_PB_LDFLAGS = -nopdolib


NEXTSTEP_OBJCPLUS_COMPILER = /usr/bin/cc
WINDOWS_OBJCPLUS_COMPILER = $(DEVDIR)/gcc
PDO_UNIX_OBJCPLUS_COMPILER = $(NEXTDEV_BIN)/gcc
NEXTSTEP_JAVA_COMPILER = /usr/bin/javac
WINDOWS_JAVA_COMPILER = $(JDKBINDIR)/javac.exe
PDO_UNIX_JAVA_COMPILER = $(NEXTDEV_BIN)/javac

include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
