#	$Id: NCR.MP-RAS.3.x,v 1.1.1.2 2002/03/12 18:00:04 zarzycki Exp $
define(`confMAPDEF', `-DNDBM -DMAP_REGEX')
define(`confENVDEF', `-DNCR_MP_RAS3')
define(`confOPTIMIZE', `-O2')
define(`confLIBS', `-lsocket -lnsl -lelf -lc89')
define(`confMBINDIR', `/usr/ucblib')
define(`confSBINDIR', `/usr/ucbetc')
define(`confUBINDIR', `/usr/ucb')
define(`confEBINDIR', `/usr/ucblib')
define(`confSTDIR', `/var/ucblib')
define(`confINSTALL', `/usr/ucb/install')
define(`confDEPEND_TYPE', `NCR')
