Project = notifyutil
Install_Dir = /usr/bin

CFILES = notifyutil.c
MANPAGES = notifyutil.1

Extra_CC_Flags = -Wall -mdynamic-no-pic
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
