Project = uname
Install_DIr = /usr/bin

CFILES = uname.c
MANPAGES = uname.1

Extra_CC_Flags = -Wall -mdynamic-no-pic
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
