# Subordinate to stats.exp.

# If not called by stats.exp, quit now.
if { ![info exists STATS_TEST] } {
    return
}

switch $STATS_TEST {
    pass { pass "pass test" }
    fail { fail "fail test" }
    xpass { xpass "xpass test" }
    xfail { xfail "xfail test" }
    untested { untested "untested test" }
    unresolved { unresolved "unresolved test" }
    unsupported { unsupported "unsupported test" }
}