#define PACKAGE_NAME "jq"
#define PACKAGE_TARNAME "jq"
#define PACKAGE_VERSION "1.7.1-apple"
#define PACKAGE_STRING "jq 1.7.1-apple"
#define PACKAGE_BUGREPORT "https://github.com/jqlang/jq/issues"
#define PACKAGE_URL "https://jqlang.github.io/jq"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
#define STDC_HEADERS 1
#define _ALL_SOURCE 1
#define _DARWIN_C_SOURCE 1
#define _GNU_SOURCE 1
#define _HPUX_ALT_XOPEN_SOCKET_API 1
#define _NETBSD_SOURCE 1
#define _OPENBSD_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#define __STDC_WANT_IEC_60559_EXT__ 1
#define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#define __STDC_WANT_LIB_EXT2__ 1
#define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#define _TANDEM_SOURCE 1
#define __EXTENSIONS__ 1
#define PACKAGE "jq"
#define VERSION ""
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_MEMMEM 1
#define USE_DECNUM 1
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define HAVE_PTHREAD 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define HAVE_ISATTY 1
#define HAVE_STRPTIME 1
#define HAVE_STRFTIME 1
#define HAVE_SETENV 1
#define HAVE_TIMEGM 1
#define HAVE_GMTIME_R 1
#define HAVE_GMTIME 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LOCALTIME 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_TM_TM_GMT_OFF 1
#define HAVE_SETLOCALE 1
#define HAVE_PTHREAD_KEY_CREATE 1
#define HAVE_PTHREAD_ONCE 1
#define HAVE_ATEXIT 1
#define HAVE_ACOS 1
#define HAVE_ACOSH 1
#define HAVE_ASIN 1
#define HAVE_ASINH 1
#define HAVE_ATAN2 1
#define HAVE_ATAN 1
#define HAVE_ATANH 1
#define HAVE_CBRT 1
#define HAVE_CEIL 1
#define HAVE_COPYSIGN 1
#define HAVE_COS 1
#define HAVE_COSH 1
#define HAVE_ERF 1
#define HAVE_ERFC 1
#define HAVE___EXP10 1
#define HAVE_EXP2 1
#define HAVE_EXP 1
#define HAVE_EXPM1 1
#define HAVE_FABS 1
#define HAVE_FDIM 1
#define HAVE_FLOOR 1
#define HAVE_FMA 1
#define HAVE_FMAX 1
#define HAVE_FMIN 1
#define HAVE_FMOD 1
#define HAVE_FREXP 1
#define HAVE_HYPOT 1
#define HAVE_J0 1
#define HAVE_J1 1
#define HAVE_JN 1
#define HAVE_LDEXP 1
#define HAVE_LGAMMA 1
#define HAVE_LOG10 1
#define HAVE_LOG1P 1
#define HAVE_LOG2 1
#define HAVE_LOG 1
#define HAVE_LOGB 1
#define HAVE_MODF 1
#define HAVE_LGAMMA_R 1
#define HAVE_NEARBYINT 1
#define HAVE_NEXTAFTER 1
#define HAVE_NEXTTOWARD 1
#define HAVE_POW 1
#define HAVE_REMAINDER 1
#define HAVE_RINT 1
#define HAVE_ROUND 1
#define HAVE_SCALB 1
#define HAVE_SCALBLN 1
#define HAVE_SCALBN 1
#define HAVE_ILOGB 1
#define HAVE_SIN 1
#define HAVE_SINH 1
#define HAVE_SQRT 1
#define HAVE_TAN 1
#define HAVE_TANH 1
#define HAVE_TGAMMA 1
#define HAVE_TRUNC 1
#define HAVE_Y0 1
#define HAVE_Y1 1
#define HAVE_YN 1
#define HAVE___THREAD 1
#define IEEE_8087 1
#define HAVE_LIBONIG 1
