
The legal values are all those accepted by
[uri \
     http://www.tcl.tk/man/tcl8.5/TkLib/GetDash.htm \
     Tk_GetDash],

and additionally all which are listed below:

[list_begin definitions]
[def "[const solid], empty string"]		Draw solid line.
[def "[const dash], [const dashed], [const -]"]	Draw a dashed line.
[def "[const dot], [const dotted], [const .]"]	Draw a dotted line.
[def "[const dash-dot], [const -.]"]	  	Draw a dash-dotted line
[def "[const dash-dot-dot], [const -..]"]	Draw a dash-dot-dotted line.
[list_end]
