#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = file_cmds

PROJECTVERSION = 2.8
PROJECT_TYPE = Aggregate
ifneq ($(shell tconf --test TARGET_OS_EMBEDDED),YES)
#libcrypto missing
MTREE=mtree
endif

TOOLS = chflags chmod chown cksum compress cp dd df du install ipcrm ipcs ln ls\
        mkdir mkfifo mknod $(MTREE) mv pathchk pax rm rmdir rmt shar stat\
        touch

OTHERSRCS = PROJECT Makefile.preamble Makefile Makefile.postamble

MAKEFILEDIR = $(MAKEFILEPATH)/pb_makefiles
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = aggregate.make
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)

OTHER_LDFLAGS += -dead_strip
NEXTSTEP_PB_CFLAGS = -mdynamic-no-pic -no-cpp-precomp -I "$(SDKROOT)/System/Library/Frameworks/System.framework/PrivateHeaders" -include TargetConditionals.h
ifneq ($(SDKROOT),)
OTHER_CFLAGS  += -isysroot "$(SDKROOT)"
OTHER_LDFLAGS += -Wl,-syslibroot,"$(SDKROOT)"
endif

NEXTSTEP_BUILD_OUTPUT_DIR = /tmp/$(NAME)/Build

NEXTSTEP_OBJCPLUS_COMPILER = /usr/bin/cc
WINDOWS_OBJCPLUS_COMPILER = $(DEVDIR)/gcc
PDO_UNIX_OBJCPLUS_COMPILER = $(NEXTDEV_BIN)/gcc
NEXTSTEP_JAVA_COMPILER = /usr/bin/javac
WINDOWS_JAVA_COMPILER = $(JDKBINDIR)/javac.exe
PDO_UNIX_JAVA_COMPILER = $(NEXTDEV_BIN)/javac

include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
