# This is a list of toolchains that are supported on this board.
set_board_info target_install {arm-elf thumb-elf}
set_board_info sim "arm-elf-sid"

# SID does not emulate the FPU
process_multilib_options "-msoft-float"
set_board_info sim,defaultendian "-EL"

# Load the generic configuration for this board. This will define a basic set
# of routines needed by the tool to communicate with the board.
load_generic_config "sid"
