.\" Copyright (c) 1998 Andries Brouwer
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the man 1.0
.\" distribution.
.\" Ελληνική μετάφραση από Λ. Δημητρουλάκη edimitro@tee.gr, Ιούλιος 2003  
.TH hman 1 "19 Ιανουαρίου 1998"
.LO 1
.SH ΟΝΟΜΑ
hman \- πλοήγηση στις ηλεκτρονικές σελίδες εγχειριδίου
.SH ΣΥΝΟΨΗ
.B hman
[ -P \fIφυλλομετρητής\fP ] [ -H \fIυπολογιστής_υπηρεσίσς\fP ] [ \fIενότητα\fP ] \fIόνομα\fP
.br
.B hman
[ -P \fIφυλλομετρητής\fP ] [ -H \fIυπολογιστής_υπηρεσίας\fP ] [ \fIενότητα\fP ] [ ευρετήριο ]
.SH ΠΕΡΙΓΡΑΦΗ
Το σενάριο 
.B hman
είναι μιά διεπαφή προς τη man2html(1) που σου επιτρέπει να εισάγεις αιτήσεις
σελίδων εγχειριδίου στη γραμμή διαταγών, 
και να βλέπεις την έξοδο στο φυλλομετρητή της προτίμησής σου.
Η συμπεριφορά θυμίζει τη 
.BR man (1)
ώστε πολλοί μπορεί να θελήσουν να δώσουν στην 
.B hman
το ψευδώνημο
.BR man .
Αν ο εν χρήσει φυλλομετρητής είναι ο netscape, 
και αν τρέχει ήδη,
τότε το σενάριο
.B hman
θα μεταβιβάσει την αίτηση σ' αυτόν.

.SH ΕΠΙΛΟΓΕΣ
.TP
.B \-\^P " φυλλομετρητής"
Προσδιορίζει το φυλλομετρητή (όπως lynx, xmosaic, arena, chimera,
netscape, amaya, ...) που θα χρησιμοποιηθεί. 
Αυτή η επιλογή υπερισχύει της μεταβλητής περιβάλλοντος
.BR MANHTMLPAGER .
Η προεπιλογή είναι η μη-httpd έκδοση του
.BR lynx .
.TP
.B \-\^H " υπολογιστής_υπηρεσίας"
Προσδιορίζει από ποιόν υπολογιστή θα πάρει τις σελίδες εγχειριδίου.
Αυτή η επιλογή υπερισχύει της μεταβλητής περιβάλλοντος
.BR MANHTMLHOST .
Η προεπιλογή είναι
.BR localhost .

.SH ΠΕΡΙΒΑΛΛΟΝ
.TP
.B  MANHTMLPAGER
Ο προεπιλεγόμενος φυλλομετρητής, 
προκύπτει από τη χρήση αυτής της μεταβλητής περιβάλλοντος.
.TP
.B  MANHTMLHOST
Ο προεπιλεγόμενος υπολογιστής υπηρεσίας, 
προκύπτει από τη χρήση αυτής της μεταβλητής περιβάλλοντος.

.SH "ΒΛΕΠΕ ΕΠΙΣΗΣ"
.BR man (1),
.BR man2html (1),
.BR arena (1),
.BR lynx (1),
.BR netscape (1),
.BR xmosaic (1),
.BR glimpse (1)

http://www.mcom.com/newsref/std/x-remote.html
