// © 2022 and later: Unicode, Inc. and others.
// License & terms of use: http://www.unicode.org/copyright.html
//
// Internal static data tables used by uresbund.cpp
// WARNING: This file is mechanically generated by the CLDR-to-ICU tool
// (see tools/cldr/cldr-to-icu/src/main/java/org/unicode/tool/cldrtoicu/generator/ResourcFallbackCodeGenerator.java).
// DO NOT HAND EDIT!!!

#ifdef INCLUDED_FROM_URESBUND_CPP

//======================================================================
// Default script table
const char scriptCodeChars[] =
    "Aghb\0Ahom\0Arab\0Aran\0Armi\0Armn\0Avst\0Bamu\0Bass\0Beng\0Brah\0"
    "Cakm\0Cans\0Cari\0Cham\0Cher\0Chrs\0Copt\0Cprt\0Cyrl\0Deva\0Egyp\0"
    "Ethi\0Geor\0Gong\0Gonm\0Goth\0Grek\0Gujr\0Guru\0Hans\0Hant\0Hebr\0"
    "Hluw\0Hmng\0Hmnp\0Ital\0Jpan\0Kali\0Kana\0Kawi\0Khar\0Khmr\0Kits\0"
    "Knda\0Kore\0Lana\0Laoo\0Lepc\0Lina\0Lisu\0Lyci\0Lydi\0Mand\0Mani\0"
    "Medf\0Merc\0Mlym\0Mong\0Mroo\0Mymr\0Narb\0Nkoo\0Nshu\0Ogam\0Olck\0"
    "Orkh\0Orya\0Osge\0Ougr\0Pauc\0Phli\0Phnx\0Plrd\0Prti\0Rohg\0Runr\0"
    "Samr\0Sarb\0Saur\0Sgnw\0Sinh\0Sogd\0Sora\0Soyo\0Syrc\0Tale\0Talu\0"
    "Taml\0Tang\0Tavt\0Telu\0Tfng\0Thaa\0Thai\0Tibt\0Tnsa\0Toto\0Ugar\0"
    "Vaii\0Wcho\0Xpeo\0Xsux\0Yiii\0";

const char dsLocaleIDChars[] =
    "ab\0abq\0adp\0ady\0ae\0aeb\0aho\0ain\0ajt\0akk\0alt\0am\0apc\0"
    "apd\0ar\0arc\0arq\0ars\0ary\0arz\0as\0ase\0av\0avl\0awa\0az_IQ\0"
    "az_IR\0az_RU\0ba\0bal\0bap\0bax\0bcq\0be\0bej\0ber\0bfq\0bft\0"
    "bfy\0bg\0bgc\0bgn\0bgx\0bhb\0bhi\0bho\0bji\0bjj\0blt\0bn\0bo\0"
    "bpy\0bqi\0bra\0brh\0brx\0bsq\0bst\0btv\0bua\0byn\0ccp\0ce\0chm\0"
    "chr\0cja\0cjm\0ckb\0cmg\0cop\0cr\0crh\0crj\0crk\0crl\0crm\0csw\0"
    "ctd\0cu\0cv\0dar\0dcc\0dgl\0dmf\0doi\0drh\0drs\0dty\0dv\0dz\0"
    "egy\0eky\0el\0esg\0ett\0fa\0fia\0fub\0gan\0gbm\0gbz\0gez\0ggn\0"
    "gjk\0gju\0glk\0gmv\0gof\0gom\0gon\0got\0grc\0grt\0gu\0gvr\0gwc\0"
    "gwt\0ha_CM\0ha_SD\0hak\0haz\0hdy\0he\0hi\0hlu\0hmd\0hmn\0hnd\0"
    "hne\0hnj\0hno\0hoc\0hoj\0hsn\0hy\0ii\0inh\0iu\0iw\0ja\0ji\0jml\0"
    "ka\0kaa\0kaw\0kbd\0kby\0kdt\0kfr\0kfy\0khb\0khn\0kht\0khw\0kjg\0"
    "kk\0kk_AF\0kk_CN\0kk_IR\0kk_MN\0km\0kn\0ko\0koi\0kok\0kqy\0krc\0"
    "kru\0ks\0ktb\0ku_LB\0kum\0kv\0kvx\0kxc\0kxl\0kxm\0kxp\0ky\0ky_CN\0"
    "kzh\0lab\0lad\0lah\0lbe\0lcp\0lep\0lez\0lif\0lis\0lki\0lmn\0lo\0"
    "lrc\0luz\0lwl\0lzh\0mag\0mai\0man_GN\0mde\0mdf\0mdx\0mfa\0mgp\0"
    "mid\0mk\0mki\0ml\0mn\0mn_CN\0mni\0mnw\0mr\0mrd\0mrj\0mro\0ms_CC\0"
    "mtr\0mvy\0mwr\0mww\0my\0mym\0myv\0myz\0mzn\0nan\0ne\0new\0nnp\0"
    "nod\0noe\0non\0nqo\0nsk\0nst\0oj\0ojs\0or\0oru\0os\0osa\0ota\0"
    "otk\0oui\0pa\0pa_PK\0pal\0peo\0phl\0phn\0pka\0pnt\0ppa\0pra\0"
    "prd\0ps\0raj\0rhg\0rif\0rjs\0rkt\0rmt\0ru\0rue\0ryu\0sa\0sah\0"
    "sat\0saz\0sck\0scl\0sd\0sd_IN\0sdh\0sga\0sgw\0shi\0shn\0shu\0"
    "si\0skr\0smp\0sog\0sou\0sr\0srb\0srx\0swb\0swv\0syl\0syr\0ta\0"
    "taj\0tcy\0tdd\0tdg\0tdh\0te\0tg\0tg_PK\0th\0thl\0thq\0thr\0ti\0"
    "tig\0tkt\0trw\0tsd\0tsf\0tsj\0tt\0tts\0txg\0txo\0tyv\0udi\0udm\0"
    "ug\0ug_KZ\0ug_MN\0uga\0uk\0unr\0unr_NP\0unx\0ur\0ur_IN\0ur_PK\0"
    "uz_AF\0uz_CN\0vai\0wal\0wbq\0wbr\0wni\0wsg\0wtm\0wuu\0xco\0xcr\0"
    "xlc\0xld\0xmf\0xmn\0xmr\0xna\0xnr\0xpr\0xsa\0xsr\0yi\0yue\0yue_CN\0"
    "zdj\0zgh\0zh\0zh_AU\0zh_BN\0zh_GB\0zh_GF\0zh_HK\0zh_ID\0zh_MO\0"
    "zh_MY\0zh_PA\0zh_PF\0zh_PH\0zh_SR\0zh_TH\0zh_TW\0zh_US\0zh_VN\0"
    "zhx\0zkt\0";

const int32_t defaultScriptTable[] = {
    0, 95,  // ab -> Cyrl
    3, 95,  // abq -> Cyrl
    7, 475,  // adp -> Tibt
    11, 95,  // ady -> Cyrl
    15, 30,  // ae -> Avst
    18, 10,  // aeb -> Arab
    22, 5,  // aho -> Ahom
    26, 195,  // ain -> Kana
    30, 10,  // ajt -> Arab
    34, 510,  // akk -> Xsux
    38, 95,  // alt -> Cyrl
    42, 110,  // am -> Ethi
    45, 10,  // apc -> Arab
    49, 10,  // apd -> Arab
    53, 10,  // ar -> Arab
    56, 20,  // arc -> Armi
    60, 10,  // arq -> Arab
    64, 10,  // ars -> Arab
    68, 10,  // ary -> Arab
    72, 10,  // arz -> Arab
    76, 45,  // as -> Beng
    79, 400,  // ase -> Sgnw
    83, 95,  // av -> Cyrl
    86, 10,  // avl -> Arab
    90, 100,  // awa -> Deva
    94, 10,  // az_IQ -> Arab
    100, 10,  // az_IR -> Arab
    106, 95,  // az_RU -> Cyrl
    112, 95,  // ba -> Cyrl
    115, 10,  // bal -> Arab
    119, 100,  // bap -> Deva
    123, 35,  // bax -> Bamu
    127, 110,  // bcq -> Ethi
    131, 95,  // be -> Cyrl
    134, 10,  // bej -> Arab
    138, 460,  // ber -> Tfng
    142, 440,  // bfq -> Taml
    146, 10,  // bft -> Arab
    150, 100,  // bfy -> Deva
    154, 95,  // bg -> Cyrl
    157, 100,  // bgc -> Deva
    161, 10,  // bgn -> Arab
    165, 135,  // bgx -> Grek
    169, 100,  // bhb -> Deva
    173, 100,  // bhi -> Deva
    177, 100,  // bho -> Deva
    181, 110,  // bji -> Ethi
    185, 100,  // bjj -> Deva
    189, 450,  // blt -> Tavt
    193, 45,  // bn -> Beng
    196, 475,  // bo -> Tibt
    199, 45,  // bpy -> Beng
    203, 10,  // bqi -> Arab
    207, 100,  // bra -> Deva
    211, 10,  // brh -> Arab
    215, 100,  // brx -> Deva
    219, 40,  // bsq -> Bass
    223, 110,  // bst -> Ethi
    227, 100,  // btv -> Deva
    231, 95,  // bua -> Cyrl
    235, 110,  // byn -> Ethi
    239, 55,  // ccp -> Cakm
    243, 95,  // ce -> Cyrl
    246, 95,  // chm -> Cyrl
    250, 75,  // chr -> Cher
    254, 10,  // cja -> Arab
    258, 70,  // cjm -> Cham
    262, 10,  // ckb -> Arab
    266, 420,  // cmg -> Soyo
    270, 85,  // cop -> Copt
    274, 60,  // cr -> Cans
    277, 95,  // crh -> Cyrl
    281, 60,  // crj -> Cans
    285, 60,  // crk -> Cans
    289, 60,  // crl -> Cans
    293, 60,  // crm -> Cans
    297, 60,  // csw -> Cans
    301, 350,  // ctd -> Pauc
    305, 95,  // cu -> Cyrl
    308, 95,  // cv -> Cyrl
    311, 95,  // dar -> Cyrl
    315, 10,  // dcc -> Arab
    319, 10,  // dgl -> Arab
    323, 275,  // dmf -> Medf
    327, 100,  // doi -> Deva
    331, 290,  // drh -> Mong
    335, 110,  // drs -> Ethi
    339, 100,  // dty -> Deva
    343, 465,  // dv -> Thaa
    346, 475,  // dz -> Tibt
    349, 105,  // egy -> Egyp
    353, 190,  // eky -> Kali
    357, 135,  // el -> Grek
    360, 125,  // esg -> Gonm
    364, 180,  // ett -> Ital
    368, 10,  // fa -> Arab
    371, 10,  // fia -> Arab
    375, 10,  // fub -> Arab
    379, 150,  // gan -> Hans
    383, 100,  // gbm -> Deva
    387, 10,  // gbz -> Arab
    391, 110,  // gez -> Ethi
    395, 100,  // ggn -> Deva
    399, 10,  // gjk -> Arab
    403, 10,  // gju -> Arab
    407, 10,  // glk -> Arab
    411, 110,  // gmv -> Ethi
    415, 110,  // gof -> Ethi
    419, 100,  // gom -> Deva
    423, 455,  // gon -> Telu
    427, 130,  // got -> Goth
    431, 90,  // grc -> Cprt
    435, 45,  // grt -> Beng
    439, 140,  // gu -> Gujr
    442, 100,  // gvr -> Deva
    446, 10,  // gwc -> Arab
    450, 10,  // gwt -> Arab
    454, 10,  // ha_CM -> Arab
    460, 10,  // ha_SD -> Arab
    466, 150,  // hak -> Hans
    470, 10,  // haz -> Arab
    474, 110,  // hdy -> Ethi
    478, 160,  // he -> Hebr
    481, 100,  // hi -> Deva
    484, 165,  // hlu -> Hluw
    488, 365,  // hmd -> Plrd
    492, 170,  // hmn -> Hmng
    496, 10,  // hnd -> Arab
    500, 100,  // hne -> Deva
    504, 175,  // hnj -> Hmnp
    508, 10,  // hno -> Arab
    512, 100,  // hoc -> Deva
    516, 100,  // hoj -> Deva
    520, 150,  // hsn -> Hans
    524, 25,  // hy -> Armn
    527, 515,  // ii -> Yiii
    530, 95,  // inh -> Cyrl
    534, 60,  // iu -> Cans
    537, 160,  // iw -> Hebr
    540, 185,  // ja -> Jpan
    543, 160,  // ji -> Hebr
    546, 100,  // jml -> Deva
    550, 115,  // ka -> Geor
    553, 95,  // kaa -> Cyrl
    557, 200,  // kaw -> Kawi
    561, 95,  // kbd -> Cyrl
    565, 10,  // kby -> Arab
    569, 470,  // kdt -> Thai
    573, 100,  // kfr -> Deva
    577, 100,  // kfy -> Deva
    581, 435,  // khb -> Talu
    585, 100,  // khn -> Deva
    589, 300,  // kht -> Mymr
    593, 10,  // khw -> Arab
    597, 235,  // kjg -> Laoo
    601, 95,  // kk -> Cyrl
    604, 10,  // kk_AF -> Arab
    610, 10,  // kk_CN -> Arab
    616, 10,  // kk_IR -> Arab
    622, 10,  // kk_MN -> Arab
    628, 210,  // km -> Khmr
    631, 220,  // kn -> Knda
    634, 225,  // ko -> Kore
    637, 95,  // koi -> Cyrl
    641, 100,  // kok -> Deva
    645, 110,  // kqy -> Ethi
    649, 95,  // krc -> Cyrl
    653, 100,  // kru -> Deva
    657, 15,  // ks -> Aran
    660, 110,  // ktb -> Ethi
    664, 10,  // ku_LB -> Arab
    670, 95,  // kum -> Cyrl
    674, 95,  // kv -> Cyrl
    677, 10,  // kvx -> Arab
    681, 110,  // kxc -> Ethi
    685, 100,  // kxl -> Deva
    689, 470,  // kxm -> Thai
    693, 10,  // kxp -> Arab
    697, 95,  // ky -> Cyrl
    700, 10,  // ky_CN -> Arab
    706, 10,  // kzh -> Arab
    710, 245,  // lab -> Lina
    714, 160,  // lad -> Hebr
    718, 10,  // lah -> Arab
    722, 95,  // lbe -> Cyrl
    726, 470,  // lcp -> Thai
    730, 240,  // lep -> Lepc
    734, 95,  // lez -> Cyrl
    738, 100,  // lif -> Deva
    742, 250,  // lis -> Lisu
    746, 10,  // lki -> Arab
    750, 455,  // lmn -> Telu
    754, 235,  // lo -> Laoo
    757, 10,  // lrc -> Arab
    761, 10,  // luz -> Arab
    765, 470,  // lwl -> Thai
    769, 150,  // lzh -> Hans
    773, 100,  // mag -> Deva
    777, 100,  // mai -> Deva
    781, 310,  // man_GN -> Nkoo
    788, 10,  // mde -> Arab
    792, 95,  // mdf -> Cyrl
    796, 110,  // mdx -> Ethi
    800, 10,  // mfa -> Arab
    804, 100,  // mgp -> Deva
    808, 265,  // mid -> Mand
    812, 95,  // mk -> Cyrl
    815, 10,  // mki -> Arab
    819, 285,  // ml -> Mlym
    822, 95,  // mn -> Cyrl
    825, 290,  // mn_CN -> Mong
    831, 45,  // mni -> Beng
    835, 300,  // mnw -> Mymr
    839, 100,  // mr -> Deva
    842, 100,  // mrd -> Deva
    846, 95,  // mrj -> Cyrl
    850, 295,  // mro -> Mroo
    854, 10,  // ms_CC -> Arab
    860, 100,  // mtr -> Deva
    864, 10,  // mvy -> Arab
    868, 100,  // mwr -> Deva
    872, 175,  // mww -> Hmnp
    876, 300,  // my -> Mymr
    879, 110,  // mym -> Ethi
    883, 95,  // myv -> Cyrl
    887, 265,  // myz -> Mand
    891, 10,  // mzn -> Arab
    895, 150,  // nan -> Hans
    899, 100,  // ne -> Deva
    902, 100,  // new -> Deva
    906, 500,  // nnp -> Wcho
    910, 230,  // nod -> Lana
    914, 100,  // noe -> Deva
    918, 380,  // non -> Runr
    922, 310,  // nqo -> Nkoo
    926, 60,  // nsk -> Cans
    930, 480,  // nst -> Tnsa
    934, 60,  // oj -> Cans
    937, 60,  // ojs -> Cans
    941, 335,  // or -> Orya
    944, 10,  // oru -> Arab
    948, 95,  // os -> Cyrl
    951, 340,  // osa -> Osge
    955, 10,  // ota -> Arab
    959, 330,  // otk -> Orkh
    963, 345,  // oui -> Ougr
    967, 145,  // pa -> Guru
    970, 15,  // pa_PK -> Aran
    976, 355,  // pal -> Phli
    980, 505,  // peo -> Xpeo
    984, 10,  // phl -> Arab
    988, 360,  // phn -> Phnx
    992, 50,  // pka -> Brah
    996, 135,  // pnt -> Grek
    1000, 100,  // ppa -> Deva
    1004, 205,  // pra -> Khar
    1008, 10,  // prd -> Arab
    1012, 10,  // ps -> Arab
    1015, 100,  // raj -> Deva
    1019, 375,  // rhg -> Rohg
    1023, 460,  // rif -> Tfng
    1027, 100,  // rjs -> Deva
    1031, 45,  // rkt -> Beng
    1035, 10,  // rmt -> Arab
    1039, 95,  // ru -> Cyrl
    1042, 95,  // rue -> Cyrl
    1046, 195,  // ryu -> Kana
    1050, 100,  // sa -> Deva
    1053, 95,  // sah -> Cyrl
    1057, 325,  // sat -> Olck
    1061, 395,  // saz -> Saur
    1065, 100,  // sck -> Deva
    1069, 10,  // scl -> Arab
    1073, 10,  // sd -> Arab
    1076, 100,  // sd_IN -> Deva
    1082, 10,  // sdh -> Arab
    1086, 320,  // sga -> Ogam
    1090, 110,  // sgw -> Ethi
    1094, 460,  // shi -> Tfng
    1098, 300,  // shn -> Mymr
    1102, 10,  // shu -> Arab
    1106, 405,  // si -> Sinh
    1109, 10,  // skr -> Arab
    1113, 385,  // smp -> Samr
    1117, 410,  // sog -> Sogd
    1121, 470,  // sou -> Thai
    1125, 95,  // sr -> Cyrl
    1128, 415,  // srb -> Sora
    1132, 100,  // srx -> Deva
    1136, 10,  // swb -> Arab
    1140, 100,  // swv -> Deva
    1144, 45,  // syl -> Beng
    1148, 425,  // syr -> Syrc
    1152, 440,  // ta -> Taml
    1155, 100,  // taj -> Deva
    1159, 220,  // tcy -> Knda
    1163, 430,  // tdd -> Tale
    1167, 100,  // tdg -> Deva
    1171, 100,  // tdh -> Deva
    1175, 455,  // te -> Telu
    1178, 95,  // tg -> Cyrl
    1181, 10,  // tg_PK -> Arab
    1187, 470,  // th -> Thai
    1190, 100,  // thl -> Deva
    1194, 100,  // thq -> Deva
    1198, 100,  // thr -> Deva
    1202, 110,  // ti -> Ethi
    1205, 110,  // tig -> Ethi
    1209, 100,  // tkt -> Deva
    1213, 10,  // trw -> Arab
    1217, 135,  // tsd -> Grek
    1221, 100,  // tsf -> Deva
    1225, 475,  // tsj -> Tibt
    1229, 95,  // tt -> Cyrl
    1232, 470,  // tts -> Thai
    1236, 445,  // txg -> Tang
    1240, 485,  // txo -> Toto
    1244, 95,  // tyv -> Cyrl
    1248, 0,  // udi -> Aghb
    1252, 95,  // udm -> Cyrl
    1256, 10,  // ug -> Arab
    1259, 95,  // ug_KZ -> Cyrl
    1265, 95,  // ug_MN -> Cyrl
    1271, 490,  // uga -> Ugar
    1275, 95,  // uk -> Cyrl
    1278, 45,  // unr -> Beng
    1282, 100,  // unr_NP -> Deva
    1289, 45,  // unx -> Beng
    1293, 15,  // ur -> Aran
    1296, 15,  // ur_IN -> Aran
    1302, 15,  // ur_PK -> Aran
    1308, 10,  // uz_AF -> Arab
    1314, 95,  // uz_CN -> Cyrl
    1320, 495,  // vai -> Vaii
    1324, 110,  // wal -> Ethi
    1328, 455,  // wbq -> Telu
    1332, 100,  // wbr -> Deva
    1336, 10,  // wni -> Arab
    1340, 120,  // wsg -> Gong
    1344, 100,  // wtm -> Deva
    1348, 150,  // wuu -> Hans
    1352, 80,  // xco -> Chrs
    1356, 65,  // xcr -> Cari
    1360, 255,  // xlc -> Lyci
    1364, 260,  // xld -> Lydi
    1368, 115,  // xmf -> Geor
    1372, 270,  // xmn -> Mani
    1376, 280,  // xmr -> Merc
    1380, 305,  // xna -> Narb
    1384, 100,  // xnr -> Deva
    1388, 370,  // xpr -> Prti
    1392, 390,  // xsa -> Sarb
    1396, 100,  // xsr -> Deva
    1400, 160,  // yi -> Hebr
    1403, 155,  // yue -> Hant
    1407, 150,  // yue_CN -> Hans
    1414, 10,  // zdj -> Arab
    1418, 460,  // zgh -> Tfng
    1422, 150,  // zh -> Hans
    1425, 155,  // zh_AU -> Hant
    1431, 155,  // zh_BN -> Hant
    1437, 155,  // zh_GB -> Hant
    1443, 155,  // zh_GF -> Hant
    1449, 155,  // zh_HK -> Hant
    1455, 155,  // zh_ID -> Hant
    1461, 155,  // zh_MO -> Hant
    1467, 150,  // zh_MY -> Hans
    1473, 155,  // zh_PA -> Hant
    1479, 155,  // zh_PF -> Hant
    1485, 155,  // zh_PH -> Hant
    1491, 155,  // zh_SR -> Hant
    1497, 155,  // zh_TH -> Hant
    1503, 155,  // zh_TW -> Hant
    1509, 150,  // zh_US -> Hans
    1515, 155,  // zh_VN -> Hant
    1521, 315,  // zhx -> Nshu
    1525, 215,  // zkt -> Kits
};

//======================================================================
// Parent locale table
const char parentLocaleChars[] =
    "ar_Latn\0as_Latn\0az_Arab\0az_Cyrl\0bal_Latn\0ber_Latn\0blt_Latn\0"
    "bm_Nkoo\0bn_Latn\0bs_Cyrl\0byn_Latn\0cu_Glag\0dje_Arab\0dyo_Arab\0"
    "el_Latn\0en_001\0en_150\0en_AD\0en_AF\0en_AG\0en_AI\0en_AL\0en_AM\0"
    "en_AO\0en_AR\0en_AT\0en_AU\0en_AW\0en_AX\0en_AZ\0en_BA\0en_BB\0"
    "en_BD\0en_BE\0en_BF\0en_BG\0en_BH\0en_BJ\0en_BL\0en_BM\0en_BN\0"
    "en_BO\0en_BQ\0en_BR\0en_BS\0en_BW\0en_BY\0en_BZ\0en_CC\0en_CD\0"
    "en_CF\0en_CG\0en_CH\0en_CI\0en_CK\0en_CM\0en_CR\0en_CU\0en_CV\0"
    "en_CX\0en_CY\0en_CZ\0en_DE\0en_DG\0en_DK\0en_DM\0en_DO\0en_DZ\0"
    "en_Dsrt\0en_EC\0en_EE\0en_EG\0en_EH\0en_ER\0en_ES\0en_ET\0en_FI\0"
    "en_FJ\0en_FK\0en_FM\0en_FO\0en_FR\0en_GA\0en_GB\0en_GD\0en_GE\0"
    "en_GF\0en_GG\0en_GH\0en_GI\0en_GL\0en_GM\0en_GN\0en_GP\0en_GQ\0"
    "en_GR\0en_GT\0en_GY\0en_HK\0en_HN\0en_HR\0en_HT\0en_HU\0en_IC\0"
    "en_ID\0en_IE\0en_IL\0en_IM\0en_IN\0en_IO\0en_IQ\0en_IS\0en_IT\0"
    "en_JE\0en_JM\0en_JO\0en_KE\0en_KG\0en_KH\0en_KI\0en_KM\0en_KN\0"
    "en_KW\0en_KY\0en_KZ\0en_LA\0en_LB\0en_LC\0en_LI\0en_LK\0en_LR\0"
    "en_LS\0en_LT\0en_LU\0en_LV\0en_LY\0en_MA\0en_MC\0en_MD\0en_ME\0"
    "en_MF\0en_MG\0en_MK\0en_ML\0en_MM\0en_MN\0en_MO\0en_MQ\0en_MR\0"
    "en_MS\0en_MT\0en_MU\0en_MV\0en_MW\0en_MY\0en_MZ\0en_NA\0en_NC\0"
    "en_NE\0en_NF\0en_NG\0en_NI\0en_NL\0en_NO\0en_NP\0en_NR\0en_NU\0"
    "en_NZ\0en_OM\0en_PE\0en_PF\0en_PG\0en_PK\0en_PL\0en_PM\0en_PN\0"
    "en_PS\0en_PT\0en_PW\0en_QA\0en_RE\0en_RO\0en_RS\0en_RU\0en_RW\0"
    "en_SB\0en_SC\0en_SD\0en_SE\0en_SG\0en_SH\0en_SI\0en_SJ\0en_SK\0"
    "en_SL\0en_SM\0en_SN\0en_SO\0en_SS\0en_ST\0en_SV\0en_SX\0en_SY\0"
    "en_SZ\0en_Shaw\0en_TC\0en_TD\0en_TF\0en_TG\0en_TH\0en_TJ\0en_TK\0"
    "en_TL\0en_TM\0en_TN\0en_TO\0en_TT\0en_TV\0en_TZ\0en_UA\0en_UG\0"
    "en_UY\0en_UZ\0en_VA\0en_VC\0en_VE\0en_VG\0en_VN\0en_VU\0en_WF\0"
    "en_WS\0en_YE\0en_YT\0en_ZA\0en_ZM\0en_ZW\0es_419\0es_AG\0es_AI\0"
    "es_AR\0es_AW\0es_BB\0es_BL\0es_BM\0es_BO\0es_BQ\0es_BR\0es_BS\0"
    "es_BZ\0es_CA\0es_CL\0es_CO\0es_CR\0es_CU\0es_CW\0es_DM\0es_DO\0"
    "es_EC\0es_FK\0es_GD\0es_GF\0es_GL\0es_GP\0es_GT\0es_GY\0es_HN\0"
    "es_HT\0es_KN\0es_KY\0es_LC\0es_MF\0es_MQ\0es_MS\0es_MX\0es_NI\0"
    "es_PA\0es_PE\0es_PM\0es_PR\0es_PY\0es_SR\0es_SV\0es_SX\0es_TC\0"
    "es_TT\0es_US\0es_UY\0es_VC\0es_VE\0es_VG\0es_VI\0ff_Adlm\0ff_Arab\0"
    "fr_HT\0gu_Latn\0ha_Arab\0he_Latn\0hi_Latn\0ht\0iu_Latn\0ja_Latn\0"
    "kk_Arab\0kn_Latn\0ks_Deva\0ku_Arab\0ky_Arab\0ky_Latn\0ml_Arab\0"
    "ml_Latn\0mn_Mong\0mni_Mtei\0mr_Latn\0ms_Arab\0nb\0nn\0no\0or_Latn\0"
    "pa_Arab\0pa_Latn\0pt_AO\0pt_CH\0pt_CV\0pt_FR\0pt_GQ\0pt_GW\0pt_LU\0"
    "pt_MO\0pt_MZ\0pt_PT\0pt_ST\0pt_TL\0rej_Rjng\0root\0ru_Latn\0sa_Latn\0"
    "sat_Deva\0sd_Deva\0sd_Khoj\0sd_Sind\0shi_Latn\0so_Arab\0sr_Latn\0"
    "sw_Arab\0ta_Latn\0te_Latn\0tg_Arab\0ug_Cyrl\0ur_Latn\0uz_Arab\0"
    "uz_Cyrl\0vai_Latn\0wo_Arab\0yi_Latn\0yo_Arab\0yue_Hans\0zh_Hant\0"
    "zh_Hant_HK\0zh_Hant_MO\0zh_Latn\0";

const int32_t parentLocaleTable[] = {
    0, 2073,  // ar_Latn -> root
    8, 2073,  // as_Latn -> root
    16, 2073,  // az_Arab -> root
    24, 2073,  // az_Cyrl -> root
    32, 2073,  // bal_Latn -> root
    41, 2073,  // ber_Latn -> root
    50, 2073,  // blt_Latn -> root
    59, 2073,  // bm_Nkoo -> root
    67, 2073,  // bn_Latn -> root
    75, 2073,  // bs_Cyrl -> root
    83, 2073,  // byn_Latn -> root
    92, 2073,  // cu_Glag -> root
    100, 2073,  // dje_Arab -> root
    109, 2073,  // dyo_Arab -> root
    118, 2073,  // el_Latn -> root
    133, 126,  // en_150 -> en_001
    140, 133,  // en_AD -> en_150
    146, 126,  // en_AF -> en_001
    152, 126,  // en_AG -> en_001
    158, 126,  // en_AI -> en_001
    164, 133,  // en_AL -> en_150
    170, 126,  // en_AM -> en_001
    176, 126,  // en_AO -> en_001
    182, 126,  // en_AR -> en_001
    188, 133,  // en_AT -> en_150
    194, 126,  // en_AU -> en_001
    200, 126,  // en_AW -> en_001
    206, 126,  // en_AX -> en_001
    212, 126,  // en_AZ -> en_001
    218, 133,  // en_BA -> en_150
    224, 126,  // en_BB -> en_001
    230, 126,  // en_BD -> en_001
    236, 133,  // en_BE -> en_150
    242, 126,  // en_BF -> en_001
    248, 133,  // en_BG -> en_150
    254, 126,  // en_BH -> en_001
    260, 126,  // en_BJ -> en_001
    266, 126,  // en_BL -> en_001
    272, 126,  // en_BM -> en_001
    278, 126,  // en_BN -> en_001
    284, 126,  // en_BO -> en_001
    290, 126,  // en_BQ -> en_001
    296, 126,  // en_BR -> en_001
    302, 126,  // en_BS -> en_001
    308, 126,  // en_BW -> en_001
    314, 133,  // en_BY -> en_150
    320, 126,  // en_BZ -> en_001
    326, 126,  // en_CC -> en_001
    332, 126,  // en_CD -> en_001
    338, 126,  // en_CF -> en_001
    344, 126,  // en_CG -> en_001
    350, 133,  // en_CH -> en_150
    356, 126,  // en_CI -> en_001
    362, 126,  // en_CK -> en_001
    368, 126,  // en_CM -> en_001
    374, 126,  // en_CR -> en_001
    380, 126,  // en_CU -> en_001
    386, 126,  // en_CV -> en_001
    392, 126,  // en_CX -> en_001
    398, 126,  // en_CY -> en_001
    404, 133,  // en_CZ -> en_150
    410, 133,  // en_DE -> en_150
    416, 126,  // en_DG -> en_001
    422, 133,  // en_DK -> en_150
    428, 126,  // en_DM -> en_001
    434, 126,  // en_DO -> en_001
    440, 126,  // en_DZ -> en_001
    446, 2073,  // en_Dsrt -> root
    454, 126,  // en_EC -> en_001
    460, 133,  // en_EE -> en_150
    466, 126,  // en_EG -> en_001
    472, 126,  // en_EH -> en_001
    478, 126,  // en_ER -> en_001
    484, 133,  // en_ES -> en_150
    490, 126,  // en_ET -> en_001
    496, 133,  // en_FI -> en_150
    502, 126,  // en_FJ -> en_001
    508, 126,  // en_FK -> en_001
    514, 126,  // en_FM -> en_001
    520, 133,  // en_FO -> en_150
    526, 133,  // en_FR -> en_150
    532, 126,  // en_GA -> en_001
    538, 126,  // en_GB -> en_001
    544, 126,  // en_GD -> en_001
    550, 133,  // en_GE -> en_150
    556, 126,  // en_GF -> en_001
    562, 126,  // en_GG -> en_001
    568, 126,  // en_GH -> en_001
    574, 126,  // en_GI -> en_001
    580, 133,  // en_GL -> en_150
    586, 126,  // en_GM -> en_001
    592, 126,  // en_GN -> en_001
    598, 126,  // en_GP -> en_001
    604, 126,  // en_GQ -> en_001
    610, 133,  // en_GR -> en_150
    616, 126,  // en_GT -> en_001
    622, 126,  // en_GY -> en_001
    628, 126,  // en_HK -> en_001
    634, 126,  // en_HN -> en_001
    640, 133,  // en_HR -> en_150
    646, 126,  // en_HT -> en_001
    652, 133,  // en_HU -> en_150
    658, 126,  // en_IC -> en_001
    664, 126,  // en_ID -> en_001
    670, 126,  // en_IE -> en_001
    676, 126,  // en_IL -> en_001
    682, 126,  // en_IM -> en_001
    688, 126,  // en_IN -> en_001
    694, 126,  // en_IO -> en_001
    700, 126,  // en_IQ -> en_001
    706, 133,  // en_IS -> en_150
    712, 133,  // en_IT -> en_150
    718, 126,  // en_JE -> en_001
    724, 126,  // en_JM -> en_001
    730, 126,  // en_JO -> en_001
    736, 126,  // en_KE -> en_001
    742, 126,  // en_KG -> en_001
    748, 126,  // en_KH -> en_001
    754, 126,  // en_KI -> en_001
    760, 126,  // en_KM -> en_001
    766, 126,  // en_KN -> en_001
    772, 126,  // en_KW -> en_001
    778, 126,  // en_KY -> en_001
    784, 126,  // en_KZ -> en_001
    790, 126,  // en_LA -> en_001
    796, 126,  // en_LB -> en_001
    802, 126,  // en_LC -> en_001
    808, 133,  // en_LI -> en_150
    814, 126,  // en_LK -> en_001
    820, 126,  // en_LR -> en_001
    826, 126,  // en_LS -> en_001
    832, 133,  // en_LT -> en_150
    838, 133,  // en_LU -> en_150
    844, 133,  // en_LV -> en_150
    850, 126,  // en_LY -> en_001
    856, 126,  // en_MA -> en_001
    862, 133,  // en_MC -> en_150
    868, 133,  // en_MD -> en_150
    874, 133,  // en_ME -> en_150
    880, 126,  // en_MF -> en_001
    886, 126,  // en_MG -> en_001
    892, 133,  // en_MK -> en_150
    898, 126,  // en_ML -> en_001
    904, 126,  // en_MM -> en_001
    910, 126,  // en_MN -> en_001
    916, 126,  // en_MO -> en_001
    922, 126,  // en_MQ -> en_001
    928, 126,  // en_MR -> en_001
    934, 126,  // en_MS -> en_001
    940, 126,  // en_MT -> en_001
    946, 126,  // en_MU -> en_001
    952, 126,  // en_MV -> en_001
    958, 126,  // en_MW -> en_001
    964, 126,  // en_MY -> en_001
    970, 126,  // en_MZ -> en_001
    976, 126,  // en_NA -> en_001
    982, 126,  // en_NC -> en_001
    988, 126,  // en_NE -> en_001
    994, 126,  // en_NF -> en_001
    1000, 126,  // en_NG -> en_001
    1006, 126,  // en_NI -> en_001
    1012, 133,  // en_NL -> en_150
    1018, 133,  // en_NO -> en_150
    1024, 126,  // en_NP -> en_001
    1030, 126,  // en_NR -> en_001
    1036, 126,  // en_NU -> en_001
    1042, 126,  // en_NZ -> en_001
    1048, 126,  // en_OM -> en_001
    1054, 126,  // en_PE -> en_001
    1060, 126,  // en_PF -> en_001
    1066, 126,  // en_PG -> en_001
    1072, 126,  // en_PK -> en_001
    1078, 133,  // en_PL -> en_150
    1084, 126,  // en_PM -> en_001
    1090, 126,  // en_PN -> en_001
    1096, 126,  // en_PS -> en_001
    1102, 133,  // en_PT -> en_150
    1108, 126,  // en_PW -> en_001
    1114, 126,  // en_QA -> en_001
    1120, 126,  // en_RE -> en_001
    1126, 133,  // en_RO -> en_150
    1132, 133,  // en_RS -> en_150
    1138, 133,  // en_RU -> en_150
    1144, 126,  // en_RW -> en_001
    1150, 126,  // en_SB -> en_001
    1156, 126,  // en_SC -> en_001
    1162, 126,  // en_SD -> en_001
    1168, 133,  // en_SE -> en_150
    1174, 126,  // en_SG -> en_001
    1180, 126,  // en_SH -> en_001
    1186, 133,  // en_SI -> en_150
    1192, 126,  // en_SJ -> en_001
    1198, 133,  // en_SK -> en_150
    1204, 126,  // en_SL -> en_001
    1210, 126,  // en_SM -> en_001
    1216, 126,  // en_SN -> en_001
    1222, 126,  // en_SO -> en_001
    1228, 126,  // en_SS -> en_001
    1234, 126,  // en_ST -> en_001
    1240, 126,  // en_SV -> en_001
    1246, 126,  // en_SX -> en_001
    1252, 126,  // en_SY -> en_001
    1258, 126,  // en_SZ -> en_001
    1264, 2073,  // en_Shaw -> root
    1272, 126,  // en_TC -> en_001
    1278, 126,  // en_TD -> en_001
    1284, 126,  // en_TF -> en_001
    1290, 126,  // en_TG -> en_001
    1296, 126,  // en_TH -> en_001
    1302, 126,  // en_TJ -> en_001
    1308, 126,  // en_TK -> en_001
    1314, 126,  // en_TL -> en_001
    1320, 126,  // en_TM -> en_001
    1326, 126,  // en_TN -> en_001
    1332, 126,  // en_TO -> en_001
    1338, 126,  // en_TT -> en_001
    1344, 126,  // en_TV -> en_001
    1350, 126,  // en_TZ -> en_001
    1356, 133,  // en_UA -> en_150
    1362, 126,  // en_UG -> en_001
    1368, 126,  // en_UY -> en_001
    1374, 126,  // en_UZ -> en_001
    1380, 133,  // en_VA -> en_150
    1386, 126,  // en_VC -> en_001
    1392, 126,  // en_VE -> en_001
    1398, 126,  // en_VG -> en_001
    1404, 126,  // en_VN -> en_001
    1410, 126,  // en_VU -> en_001
    1416, 126,  // en_WF -> en_001
    1422, 126,  // en_WS -> en_001
    1428, 126,  // en_YE -> en_001
    1434, 126,  // en_YT -> en_001
    1440, 126,  // en_ZA -> en_001
    1446, 126,  // en_ZM -> en_001
    1452, 126,  // en_ZW -> en_001
    1465, 1458,  // es_AG -> es_419
    1471, 1458,  // es_AI -> es_419
    1477, 1458,  // es_AR -> es_419
    1483, 1458,  // es_AW -> es_419
    1489, 1458,  // es_BB -> es_419
    1495, 1458,  // es_BL -> es_419
    1501, 1458,  // es_BM -> es_419
    1507, 1458,  // es_BO -> es_419
    1513, 1458,  // es_BQ -> es_419
    1519, 1458,  // es_BR -> es_419
    1525, 1458,  // es_BS -> es_419
    1531, 1458,  // es_BZ -> es_419
    1537, 1458,  // es_CA -> es_419
    1543, 1458,  // es_CL -> es_419
    1549, 1458,  // es_CO -> es_419
    1555, 1458,  // es_CR -> es_419
    1561, 1458,  // es_CU -> es_419
    1567, 1458,  // es_CW -> es_419
    1573, 1458,  // es_DM -> es_419
    1579, 1458,  // es_DO -> es_419
    1585, 1458,  // es_EC -> es_419
    1591, 1458,  // es_FK -> es_419
    1597, 1458,  // es_GD -> es_419
    1603, 1458,  // es_GF -> es_419
    1609, 1458,  // es_GL -> es_419
    1615, 1458,  // es_GP -> es_419
    1621, 1458,  // es_GT -> es_419
    1627, 1458,  // es_GY -> es_419
    1633, 1458,  // es_HN -> es_419
    1639, 1458,  // es_HT -> es_419
    1645, 1458,  // es_KN -> es_419
    1651, 1458,  // es_KY -> es_419
    1657, 1458,  // es_LC -> es_419
    1663, 1458,  // es_MF -> es_419
    1669, 1458,  // es_MQ -> es_419
    1675, 1458,  // es_MS -> es_419
    1681, 1458,  // es_MX -> es_419
    1687, 1458,  // es_NI -> es_419
    1693, 1458,  // es_PA -> es_419
    1699, 1458,  // es_PE -> es_419
    1705, 1458,  // es_PM -> es_419
    1711, 1458,  // es_PR -> es_419
    1717, 1458,  // es_PY -> es_419
    1723, 1458,  // es_SR -> es_419
    1729, 1458,  // es_SV -> es_419
    1735, 1458,  // es_SX -> es_419
    1741, 1458,  // es_TC -> es_419
    1747, 1458,  // es_TT -> es_419
    1753, 1458,  // es_US -> es_419
    1759, 1458,  // es_UY -> es_419
    1765, 1458,  // es_VC -> es_419
    1771, 1458,  // es_VE -> es_419
    1777, 1458,  // es_VG -> es_419
    1783, 1458,  // es_VI -> es_419
    1789, 2073,  // ff_Adlm -> root
    1797, 2073,  // ff_Arab -> root
    1811, 2073,  // gu_Latn -> root
    1819, 2073,  // ha_Arab -> root
    1827, 2073,  // he_Latn -> root
    1835, 688,  // hi_Latn -> en_IN
    1843, 1805,  // ht -> fr_HT
    1846, 2073,  // iu_Latn -> root
    1854, 2073,  // ja_Latn -> root
    1862, 2073,  // kk_Arab -> root
    1870, 2073,  // kn_Latn -> root
    1878, 2073,  // ks_Deva -> root
    1886, 2073,  // ku_Arab -> root
    1894, 2073,  // ky_Arab -> root
    1902, 2073,  // ky_Latn -> root
    1910, 2073,  // ml_Arab -> root
    1918, 2073,  // ml_Latn -> root
    1926, 2073,  // mn_Mong -> root
    1934, 2073,  // mni_Mtei -> root
    1943, 2073,  // mr_Latn -> root
    1951, 2073,  // ms_Arab -> root
    1959, 1965,  // nb -> no
    1962, 1965,  // nn -> no
    1968, 2073,  // or_Latn -> root
    1976, 2073,  // pa_Arab -> root
    1984, 2073,  // pa_Latn -> root
    1992, 2046,  // pt_AO -> pt_PT
    1998, 2046,  // pt_CH -> pt_PT
    2004, 2046,  // pt_CV -> pt_PT
    2010, 2046,  // pt_FR -> pt_PT
    2016, 2046,  // pt_GQ -> pt_PT
    2022, 2046,  // pt_GW -> pt_PT
    2028, 2046,  // pt_LU -> pt_PT
    2034, 2046,  // pt_MO -> pt_PT
    2040, 2046,  // pt_MZ -> pt_PT
    2052, 2046,  // pt_ST -> pt_PT
    2058, 2046,  // pt_TL -> pt_PT
    2064, 2073,  // rej_Rjng -> root
    2078, 2073,  // ru_Latn -> root
    2086, 2073,  // sa_Latn -> root
    2094, 2073,  // sat_Deva -> root
    2103, 2073,  // sd_Deva -> root
    2111, 2073,  // sd_Khoj -> root
    2119, 2073,  // sd_Sind -> root
    2127, 2073,  // shi_Latn -> root
    2136, 2073,  // so_Arab -> root
    2144, 2073,  // sr_Latn -> root
    2152, 2073,  // sw_Arab -> root
    2160, 2073,  // ta_Latn -> root
    2168, 2073,  // te_Latn -> root
    2176, 2073,  // tg_Arab -> root
    2184, 2073,  // ug_Cyrl -> root
    2192, 2073,  // ur_Latn -> root
    2200, 2073,  // uz_Arab -> root
    2208, 2073,  // uz_Cyrl -> root
    2216, 2073,  // vai_Latn -> root
    2225, 2073,  // wo_Arab -> root
    2233, 2073,  // yi_Latn -> root
    2241, 2073,  // yo_Arab -> root
    2249, 2073,  // yue_Hans -> root
    2258, 2073,  // zh_Hant -> root
    2277, 2266,  // zh_Hant_MO -> zh_Hant_HK
    2288, 2073,  // zh_Latn -> root
};


#endif  // INCLUDED_FROM_URESBUND_CPP
