Project = nl
Install_Dir = /usr/bin

CFILES = nl.c
MANPAGES = nl.1

Extra_CC_Flags = -Wall \
	-D__FBSDID=__RCSID
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
