MODULES = \
    setuptools-41.0.1 \
    altgraph-0.10.2 \
    modulegraph-0.10.4 \
    macholib-1.5.1 \
    bdist_mpkg-0.5.0 \
    py2app-0.7.3 \
    numpy-1.8.0rc1 \
    xattr-0.6.4 \
    bonjour-py-0.3 \
    scipy-0.13.0b1 \
    pytz-2013.7 \
    six-1.12.0 \
    future-0.17.1 \
    python-dateutil-1.5 \
    pyparsing-2.0.1 \
    matplotlib-1.3.1 \
    cffi-1.14.3 \
    pycparser-2.19 \
    asn1crypto-0.24.0 \
    enum34-1.1.6 \
    ipaddress-1.0.22 \
    cryptography-2.9.2 \
    pyOpenSSL-19.0.0 \
    wheel-0.33.1 \
    recertifi-0.11.0
