/^h5 =/s/$/ pldtrace.h/
/-o miniperl/a
.
.,.+1c
	$(CC) $(CLDFLAGS) -o miniperl \
	    miniperlmain$(OBJ_EXT) opmini$(OBJ_EXT) perl$(OBJ_EXT) \
	    $(filter-out op$(OBJ_EXT),$(obj)) $(libs)
.
/-o perl/s//-mdynamic-no-pic &/
/perl installperl/i
	# fix 64-bit sizes
	ed - lib/Config_heavy.pl < $(SRCROOT)/fix/Config_heavy.pl.ed
.
g,//$,d
w
