Project = comm
Install_Dir = /usr/bin

CFILES = comm.c
MANPAGES = comm.1

Extra_CC_Flags = -Wall \
	-D__FBSDID=__RCSID
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
