--- #YAML:1.0
name:               Lingua-EN-Inflect
version:            1.895
abstract:           Convert singular to plural. Select "a" or "an".
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    version:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
