#ifndef __CYGWIN__
LIBRARY X11
#else
LIBRARY libX11
#endif
VERSION LIBRARY_VERSION
EXPORTS
#if !defined(__CYGWIN__) && !defined(__UNIXOS2__)
 _Xdebug_p=_Xdebug CONSTANT
 _XCreateMutex_fn_p=_XCreateMutex_fn CONSTANT
 _XFreeMutex_fn_p=_XFreeMutex_fn CONSTANT
 _XLockMutex_fn_p=_XLockMutex_fn CONSTANT
 _XUnlockMutex_fn_p=_XUnlockMutex_fn CONSTANT
 _Xglobal_lock_p=_Xglobal_lock CONSTANT
 _XFlushIt
 XActivateScreenSaver
 XAddConnectionWatch
 XAddExtension
 XAddHost
 XAddHosts
 XAddPixel
 XAddToExtensionList
 XAddToSaveSet
 XAllPlanes
 XAllocClassHint
 XAllocColor
 XAllocColorCells
 XAllocColorPlanes
 XAllocIconSize
 XAllocNamedColor
 XAllocSizeHints
 XAllocStandardColormap
 XAllocWMHints
 XAllowEvents
 XAutoRepeatOff
 XAutoRepeatOn
 XBaseFontNameListOfFontSet
 XBell
 XBitmapBitOrder
 XBitmapPad
 XBitmapUnit
 XBlackPixel
 XBlackPixelOfScreen
 XCellsOfScreen
 XChangeActivePointerGrab
 XChangeGC
 XChangeKeyboardControl
 XChangeKeyboardMapping
 XChangePointerControl
 XChangeProperty
 XChangeSaveSet
 XChangeWindowAttributes
 XCheckIfEvent
 XCheckMaskEvent
 XCheckTypedEvent
 XCheckTypedWindowEvent
 XCheckWindowEvent
 XCirculateSubwindows
 XCirculateSubwindowsDown
 XCirculateSubwindowsUp
 XClearArea
 XClearWindow
 XClipBox
 XCloseDisplay
 XCloseIM
 XCloseOM
 XConfigureWindow
 XConnectionNumber
 XContextDependentDrawing
 XContextualDrawing
 XConvertCase
 XConvertSelection
 XCopyArea
 XCopyColormapAndFree
 XCopyGC
 XCopyPlane
 XCreateBitmapFromData
 XCreateColormap
 XCreateFontCursor
 XCreateFontSet
 XCreateGC
 XCreateGlyphCursor
 XCreateIC
 XCreateImage
 XCreateOC
 XCreatePixmap
 XCreatePixmapCursor
 XCreatePixmapFromBitmapData
 XCreateRegion
 XCreateSimpleWindow
 XCreateWindow
 XDefaultColormap
 XDefaultColormapOfScreen
 XDefaultDepth
 XDefaultDepthOfScreen
 XDefaultGC
 XDefaultGCOfScreen
 XDefaultRootWindow
 XDefaultScreen
 XDefaultScreenOfDisplay
 XDefaultString
 XDefaultVisual
 XDefaultVisualOfScreen
 XDefineCursor
 XDeleteContext
 XDeleteModifiermapEntry
 XDeleteProperty
 XDestroyIC
 XDestroyImage
 XDestroyOC
 XDestroyRegion
 XDestroySubwindows
 XDestroyWindow
 XDirectionalDependentDrawing
 XDisableAccessControl
 XDisplayCells
 XDisplayHeight
 XDisplayHeightMM
 XDisplayKeycodes
 XDisplayMotionBufferSize
 XDisplayName
 XDisplayOfIM
 XDisplayOfOM
 XDisplayOfScreen
 XDisplayPlanes
 XDisplayString
 XDisplayWidth
 XDisplayWidthMM
 XDoesBackingStore
 XDoesSaveUnders
 XDrawArc
 XDrawArcs
 XDrawImageString
 XDrawImageString16
 XDrawLine
 XDrawLines
 XDrawPoint
 XDrawPoints
 XDrawRectangle
 XDrawRectangles
 XDrawSegments
 XDrawString
 XDrawString16
 XDrawText
 XDrawText16
 XEHeadOfExtensionList
 XESetBeforeFlush
 XESetCloseDisplay
 XESetCopyGC
 XESetCreateFont
 XESetCreateGC
 XESetError
 XESetErrorString
 XESetEventToWire
 XESetFlushGC
 XESetFreeFont
 XESetFreeGC
 XESetPrintErrorValues
 XESetWireToError
 XESetWireToEvent
 XEmptyRegion
 XEnableAccessControl
 XEqualRegion
 XEventMaskOfScreen
 XEventsQueued
 XExtendedMaxRequestSize
 XExtentsOfFontSet
 XFetchBuffer
 XFetchBytes
 XFetchName
 XFillArc
 XFillArcs
 XFillPolygon
 XFillRectangle
 XFillRectangles
 XFilterEvent
 XFindContext
 XFindOnExtensionList
 XFlush
 XFlushGC
 XFontsOfFontSet
 XForceScreenSaver
 XFree
 XFreeColormap
 XFreeColors
 XFreeCursor
 XFreeExtensionList
 XFreeFont
 XFreeFontInfo
 XFreeFontNames
 XFreeFontPath
 XFreeFontSet
 XFreeGC
 XFreeModifiermap
 XFreePixmap
 XFreeStringList
 XGContextFromGC
 XGeometry
 XGetAtomName
 XGetAtomNames
 XGetClassHint
 XGetCommand
 XGetDefault
 XGetErrorDatabaseText
 XGetErrorText
 XGetFontPath
 XGetFontProperty
 XGetGCValues
 XGetGeometry
 XGetICValues
 XGetIMValues
 XGetIconName
 XGetIconSizes
 XGetImage
 XGetInputFocus
 XGetKeyboardControl
 XGetKeyboardMapping
 XGetModifierMapping
 XGetMotionEvents
 XGetNormalHints
 XGetOCValues
 XGetOMValues
 XGetPixel
 XGetPointerControl
 XGetPointerMapping
 XGetRGBColormaps
 XGetScreenSaver
 XGetSelectionOwner
 XGetSizeHints
 XGetStandardColormap
 XGetSubImage
 XGetTextProperty
 XGetTransientForHint
 XGetVisualInfo
 XGetWMClientMachine
 XGetWMColormapWindows
 XGetWMHints
 XGetWMIconName
 XGetWMName
 XGetWMNormalHints
 XGetWMProtocols
 XGetWMSizeHints
 XGetWindowAttributes
 XGetWindowProperty
 XGetZoomHints
 XGrabButton
 XGrabKey
 XGrabKeyboard
 XGrabPointer
 XGrabServer
 XHeightMMOfScreen
 XHeightOfScreen
 XIMOfIC
 XIconifyWindow
 XIfEvent
 XImageByteOrder
 XInitExtension
 XInitImage
 XInitThreads
 XInsertModifiermapEntry
 XInstallColormap
 XInternAtom
 XInternAtoms
 XInternalConnectionNumbers
 XIntersectRegion
 XKeycodeToKeysym
 XKeysymToKeycode
 XKeysymToString
 XKillClient
 XLastKnownRequestProcessed
 XListDepths
 XListExtensions
 XListFonts
 XListFontsWithInfo
 XListHosts
 XListInstalledColormaps
 XListPixmapFormats
 XListProperties
 XLoadFont
 XLoadQueryFont
 XLocaleOfFontSet
 XLocaleOfIM
 XLocaleOfOM
 XLockDisplay
 XLookupColor
 XLookupKeysym
 XLookupString
 XLowerWindow
 XMapRaised
 XMapSubwindows
 XMapWindow
 XMaskEvent
 XMatchVisualInfo
 XMaxCmapsOfScreen
 XMaxRequestSize
 XMinCmapsOfScreen
 XMoveResizeWindow
 XMoveWindow
 XNewModifiermap
 XNextEvent
 XNextRequest
 XNoOp
 XOMOfOC
 XOffsetRegion
 XOpenDisplay
 XOpenIM
 XOpenOM
 XParseColor
 XParseGeometry
 XPeekEvent
 XPeekIfEvent
 XPending
 XPlanesOfScreen
 XPointInRegion
 XPolygonRegion
 XProcessInternalConnection
 XProtocolRevision
 XProtocolVersion
 XPutBackEvent
 XPutImage
 XPutPixel
 XQLength
 XQueryBestCursor
 XQueryBestSize
 XQueryBestStipple
 XQueryBestTile
 XQueryColor
 XQueryColors
 XQueryExtension
 XQueryFont
 XQueryKeymap
 XQueryPointer
 XQueryTextExtents
 XQueryTextExtents16
 XQueryTree
 XRaiseWindow
 XReadBitmapFile
 XReadBitmapFileData
 XRebindKeysym
 XRecolorCursor
 XReconfigureWMWindow
 XRectInRegion
 XRefreshKeyboardMapping
 XRegisterIMInstantiateCallback
 XRemoveConnectionWatch
 XRemoveFromSaveSet
 XRemoveHost
 XRemoveHosts
 XReparentWindow
 XResetScreenSaver
 XResizeWindow
 XResourceManagerString
 XRestackWindows
 XRootWindow
 XRootWindowOfScreen
 XRotateBuffers
 XRotateWindowProperties
 XSaveContext
 XScreenCount
 XScreenNumberOfScreen
 XScreenOfDisplay
 XScreenResourceString
 XSelectInput
 XSendEvent
 XServerVendor
 XSetAccessControl
 XSetAfterFunction
 XSetArcMode
 XSetAuthorization
 XSetBackground
 XSetClassHint
 XSetClipMask
 XSetClipOrigin
 XSetClipRectangles
 XSetCloseDownMode
 XSetCommand
 XSetDashes
 XSetErrorHandler
 XSetFillRule
 XSetFillStyle
 XSetFont
 XSetFontPath
 XSetForeground
 XSetFunction
 XSetGraphicsExposures
 XSetICFocus
 XSetICValues
 XSetIMValues
 XSetIOErrorHandler
 XSetIconName
 XSetIconSizes
 XSetInputFocus
 XSetLineAttributes
 XSetLocaleModifiers
 XSetModifierMapping
 XSetNormalHints
 XSetOCValues
 XSetOMValues
 XSetPlaneMask
 XSetPointerMapping
 XSetRGBColormaps
 XSetRegion
 XSetScreenSaver
 XSetSelectionOwner
 XSetSizeHints
 XSetStandardColormap
 XSetStandardProperties
 XSetState
 XSetStipple
 XSetSubwindowMode
 XSetTSOrigin
 XSetTextProperty
 XSetTile
 XSetTransientForHint
 XSetWMClientMachine
 XSetWMColormapWindows
 XSetWMHints
 XSetWMIconName
 XSetWMName
 XSetWMNormalHints
 XSetWMProperties
 XSetWMProtocols
 XSetWMSizeHints
 XSetWindowBackground
 XSetWindowBackgroundPixmap
 XSetWindowBorder
 XSetWindowBorderPixmap
 XSetWindowBorderWidth
 XSetWindowColormap
 XSetZoomHints
 XShrinkRegion
 XStoreBuffer
 XStoreBytes
 XStoreColor
 XStoreColors
 XStoreName
 XStoreNamedColor
 XStringListToTextProperty
 XStringToKeysym
 XSubImage
 XSubtractRegion
 XSupportsLocale
 XSync
 XSynchronize
 XTextExtents
 XTextExtents16
 XTextPropertyToStringList
 XTextWidth
 XTextWidth16
 XTranslateCoordinates
 XUndefineCursor
 XUngrabButton
 XUngrabKey
 XUngrabKeyboard
 XUngrabPointer
 XUngrabServer
 XUninstallColormap
 XUnionRectWithRegion
 XUnionRegion
 XUnloadFont
 XUnlockDisplay
 XUnmapSubwindows
 XUnmapWindow
 XUnregisterIMInstantiateCallback
 XUnsetICFocus
 XVaCreateNestedList
 XVendorRelease
 XVisualIDFromVisual
 XWMGeometry
 XWarpPointer
 XWhitePixel
 XWhitePixelOfScreen
 XWidthMMOfScreen
 XWidthOfScreen
 XWindowEvent
 XWithdrawWindow
 XWriteBitmapFile
 XXorRegion
 XcmsAddColorSpace
 XcmsAddFunctionSet
 XcmsAllocColor
 XcmsAllocNamedColor
 XcmsCCCOfColormap
 XcmsCIELabClipL
 XcmsCIELabClipLab
 XcmsCIELabClipab
 XcmsCIELabQueryMaxC
 XcmsCIELabQueryMaxL
 XcmsCIELabQueryMaxLC
 XcmsCIELabQueryMinL
 XcmsCIELabToCIEXYZ
 XcmsCIELabWhiteShiftColors
 XcmsCIELuvClipL
 XcmsCIELuvClipLuv
 XcmsCIELuvClipuv
 XcmsCIELuvQueryMaxC
 XcmsCIELuvQueryMaxL
 XcmsCIELuvQueryMaxLC
 XcmsCIELuvQueryMinL
 XcmsCIELuvToCIEuvY
 XcmsCIELuvWhiteShiftColors
 XcmsCIEXYZToCIELab
 XcmsCIEXYZToCIEuvY
 XcmsCIEXYZToCIExyY
 XcmsCIEXYZToRGBi
 XcmsCIEuvYToCIELuv
 XcmsCIEuvYToCIEXYZ
 XcmsCIEuvYToTekHVC
 XcmsCIExyYToCIEXYZ
 XcmsClientWhitePointOfCCC
 XcmsConvertColors
 XcmsCreateCCC
 XcmsDefaultCCC
 XcmsDisplayOfCCC
 XcmsFormatOfPrefix
 XcmsFreeCCC
 XcmsLookupColor
 XcmsPrefixOfFormat
 XcmsQueryBlack
 XcmsQueryBlue
 XcmsQueryColor
 XcmsQueryColors
 XcmsQueryGreen
 XcmsQueryRed
 XcmsQueryWhite
 XcmsRGBToRGBi
 XcmsRGBiToCIEXYZ
 XcmsRGBiToRGB
 XcmsScreenNumberOfCCC
 XcmsScreenWhitePointOfCCC
 XcmsSetCCCOfColormap
 XcmsSetCompressionProc
 XcmsSetWhiteAdjustProc
 XcmsSetWhitePoint
 XcmsStoreColor
 XcmsStoreColors
 XcmsTekHVCClipC
 XcmsTekHVCClipV
 XcmsTekHVCClipVC
 XcmsTekHVCQueryMaxC
 XcmsTekHVCQueryMaxV
 XcmsTekHVCQueryMaxVC
 XcmsTekHVCQueryMaxVSamples
 XcmsTekHVCQueryMinV
 XcmsTekHVCToCIEuvY
 XcmsTekHVCWhiteShiftColors
 XcmsVisualOfCCC
 XmbDrawImageString
 XmbDrawString
 XmbDrawText
 XmbLookupString
 XmbResetIC
 XmbSetWMProperties
 XmbTextEscapement
 XmbTextExtents
 XmbTextListToTextProperty
 XmbTextPerCharExtents
 XmbTextPropertyToTextList
 Xpermalloc
 XrmCombineDatabase
 XrmCombineFileDatabase
 XrmDestroyDatabase
 XrmEnumerateDatabase
 XrmGetDatabase
 XrmGetFileDatabase
 XrmGetResource
 XrmGetStringDatabase
 XrmInitialize
 XrmLocaleOfDatabase
 XrmMergeDatabases
 XrmParseCommand
 XrmPermStringToQuark
 XrmPutFileDatabase
 XrmPutLineResource
 XrmPutResource
 XrmPutStringResource
 XrmQGetResource
 XrmQGetSearchList
 XrmQGetSearchResource
 XrmQPutResource
 XrmQPutStringResource
 XrmQuarkToString
 XrmSetDatabase
 XrmStringToBindingQuarkList
 XrmStringToQuark
 XrmStringToQuarkList
 XrmUniqueQuark
 XwcDrawImageString
 XwcDrawString
 XwcDrawText
 XwcFreeStringList
 XwcLookupString
 XwcResetIC
 XwcTextEscapement
 XwcTextExtents
 XwcTextListToTextProperty
 XwcTextPerCharExtents
 XwcTextPropertyToTextList
 _XAllocID
 _XAllocIDs
 _XAllocScratch
 _XAllocTemp
 _XAsyncErrorHandler
 _XConnectDisplay
 _XDeqAsyncHandler
 _XEatData
 _XError
#ifndef __UNIXOS2__
 _XFlushIt
#endif
 _XFlushGCCache
 _XFreeTemp
 _XGetAsyncData
 _XGetAsyncReply
 _XIOError
 _XInitImageFuncPtrs
 _XRead
;_XReadEvents
 _XReadPad
 _XRegisterFilterByMask
 _XRegisterFilterByType
 _XRegisterInternalConnection
 _XReply
 _XSend
 _XSetLastRequestRead
 _XUnknownNativeEvent
 _XUnregisterFilter
 _XUnregisterInternalConnection
 _XVIDtoVisual
#ifndef __UNIXOS2__
 _Xthread_init
 _Xthread_waiter
#endif
 XkbIgnoreExtension
 XkbOpenDisplay
 XkbQueryExtension
 XkbUseExtension
 XkbLibraryVersion
 XkbSetXlibControls
 XkbGetXlibControls
 XkbSetAtomFuncs
 XkbKeycodeToKeysym
 XkbKeysymToModifiers
 XkbLookupKeySym
 XkbLookupKeyBinding
 XkbTranslateKeyCode
 XkbTranslateKeySym
 XkbSetAutoRepeatRate
 XkbGetAutoRepeatRate
 XkbChangeEnabledControls
 XkbDeviceBell
 XkbForceDeviceBell
 XkbDeviceBellEvent
 XkbBell
 XkbForceBell
 XkbBellEvent
 XkbSelectEvents
 XkbSelectEventDetails
 XkbNoteMapChanges
 XkbNoteNameChanges
 XkbGetIndicatorState
 XkbGetIndicatorMap
 XkbSetIndicatorMap
 XkbGetNamedIndicator
 XkbGetNamedDeviceIndicator
 XkbSetNamedIndicator
 XkbSetNamedDeviceIndicator
 XkbLockModifiers
 XkbLatchModifiers
 XkbLockGroup
 XkbLatchGroup
 XkbSetServerInternalMods
 XkbSetIgnoreLockMods
 XkbVirtualModsToReal
 XkbComputeEffectiveMap
 XkbInitCanonicalKeyTypes
 XkbAllocKeyboard
 XkbFreeKeyboard
 XkbAllocClientMap
 XkbAllocServerMap
 XkbFreeClientMap
 XkbFreeServerMap
 XkbAddKeyType
 XkbAllocIndicatorMaps
 XkbFreeIndicatorMaps
 XkbGetMap
 XkbGetUpdatedMap
 XkbGetMapChanges
 XkbRefreshKeyboardMapping
 XkbGetKeyTypes
 XkbGetKeySyms
 XkbGetKeyActions
 XkbGetKeyBehaviors
 XkbGetVirtualMods
 XkbGetKeyExplicitComponents
 XkbGetKeyModifierMap
 XkbAllocControls
 XkbFreeControls
 XkbGetControls
 XkbSetControls
 XkbAllocCompatMap
 XkbFreeCompatMap
 XkbGetCompatMap
 XkbSetCompatMap
 XkbAllocNames
 XkbGetNames
 XkbSetNames
 XkbChangeNames
 XkbFreeNames
 XkbGetState
 XkbSetMap
 XkbChangeMap
 XkbSetDetectableAutoRepeat
 XkbGetDetectableAutoRepeat
 XkbSetAutoResetControls
 XkbGetAutoResetControls
 XkbCopyKeyType
 XkbCopyKeyTypes
 XkbResizeKeyType
 XkbResizeKeySyms
 XkbResizeKeyActions
 XkbChangeTypesOfKey
 XkbListComponents
 XkbFreeComponentList
 XkbGetKeyboard
 XkbGetKeyboardByName
 XkbAddDeviceLedInfo
 XkbResizeDeviceButtonActions
 XkbAllocDeviceInfo
 XkbFreeDeviceInfo
 XkbNoteDeviceChanges
 XkbGetDeviceInfo
 XkbGetDeviceInfoChanges
 XkbGetDeviceButtonActions
 XkbGetDeviceLedInfo
 XkbSetDeviceInfo
 XkbChangeDeviceInfo
 XkbSetDeviceLedInfo
 XkbSetDeviceButtonActions
 XkbToControl
 XkbSetDebuggingFlags
 XkbGetPerClientControls
 XkbSetPerClientControls
 XauDisposeAuth
 XauFileName
 XauGetBestAuthByAddr
 XauReadAuth
 XcmsCIELabColorSpace
 XcmsCIELuvColorSpace
 XcmsCIEuvYColorSpace
 XcmsCIExyYColorSpace
 XcmsCIEXYZColorSpace
 XcmsLinearRGBFunctionSet
 XcmsRGBColorSpace
 XcmsRGBiColorSpace
 XcmsTekHVCColorSpace
 XcmsUNDEFINEDColorSpace
 _XimParseStringFile	/* unspecified, retain slot for binary compat */
 XkbAddGeomColor
 XkbAddGeomDoodad
 XkbAddGeomKey
 XkbAddGeomKeyAlias
 XkbAddGeomOutline
 XkbAddGeomOverlay
 XkbAddGeomOverlayKey
 XkbAddGeomOverlayRow
 XkbAddGeomProperty
 XkbAddGeomRow
 XkbAddGeomSection
 XkbAddGeomShape
 XkbAllocGeomColors
 XkbAllocGeomDoodads
 XkbAllocGeometry
 XkbAllocGeomKeyAliases
 XkbAllocGeomKeys
 XkbAllocGeomOutlines
 XkbAllocGeomOverlayKeys
 XkbAllocGeomOverlayRows
 XkbAllocGeomOverlays
 XkbAllocGeomPoints
 XkbAllocGeomProps
 XkbAllocGeomRows
 XkbAllocGeomSectionDoodads
 XkbAllocGeomSections
 XkbAllocGeomShapes
 XkbApplyCompatMapToKey
 XkbApplyVirtualModChanges
 XkbComputeRowBounds
 XkbComputeSectionBounds
 XkbComputeShapeBounds
 XkbComputeShapeTop
 XkbFindOverlayForKey
 XkbFreeGeomColors
 XkbFreeGeomDoodads
 XkbFreeGeometry
 XkbFreeGeomKeyAliases
 XkbFreeGeomKeys
 XkbFreeGeomOutlines
 XkbFreeGeomOverlayKeys
 XkbFreeGeomOverlayRows
 XkbFreeGeomOverlays
 XkbFreeGeomPoints
 XkbFreeGeomProperties
 XkbFreeGeomRows
 XkbFreeGeomSections
 XkbFreeGeomShapes
 XkbGetGeometry
 XkbGetKeyVirtualModMap
 XkbGetNamedGeometry
 XkbKeyTypesForCoreSymbols
 XkbNoteControlsChanges
 XkbSetGeometry
 XkbTranslateKey
 XkbUpdateActionVirtualMods
 XkbUpdateKeyTypeVirtualMods
 XkbUpdateMapFromCore
 XkbXlibControlsImplemented
 Xutf8TextPropertyToTextList
 Xutf8TextListToTextProperty	 
#else
	XSaveContext   
	XFindContext   
	XDeleteContext   
	XListDepths   
	XrmParseCommand   
	Xpermalloc   
	_XrmInternalStringToQuark   
	XrmStringToQuark   
	XrmPermStringToQuark   
	XrmUniqueQuark   
	XrmQuarkToString   
	XAllocColorCells   
	XAllocColorPlanes   
	XAllowEvents   
	XAutoRepeatOn   
	XAutoRepeatOff   
	XSetWindowBackground   
	XSetWindowBorderWidth   
	XBell   
	XSetWindowBorder   
	XEnableAccessControl   
	XDisableAccessControl   
	XSetAccessControl   
	XSetCloseDownMode   
	XChangeActivePointerGrab   
	XSetWindowColormap   
	XChangeGC   
	XChangeKeyboardControl   
	XChangePointerControl   
	XChangeProperty   
	XChangeSaveSet   
	XAddToSaveSet   
	XRemoveFromSaveSet   
	XChangeWindowAttributes   
	XResizeWindow   
	XCheckIfEvent   
	XCheckMaskEvent   
	XCheckWindowEvent   
	XCheckTypedEvent   
	XCheckTypedWindowEvent   
	XCirculateSubwindows   
	XCirculateSubwindowsDown   
	XCirculateSubwindowsUp   
	XCloseDisplay   
	XClearWindow   
	XClearArea   
	XMoveResizeWindow   
	_XConnectDisplay   
	_XDisconnectDisplay   
	_XSendClientPrefix   
	XSetAuthorization   
	XConvertSelection   
	XCopyArea   
	XCopyColormapAndFree   
	XCopyGC   
	XCopyPlane   
	XCreateBitmapFromData   
	XCreateColormap   
	XCreatePixmapCursor   
	XCreateGC   
	_XUpdateGCCache   
	_XFlushGCCache   
	XFlushGC   
	XGContextFromGC   
	XCreateGlyphCursor   
	XCreatePixmapFromBitmapData   
	XCreatePixmap   
	XCreateSimpleWindow   
	XCreateFontCursor   
	XDefineCursor   
	XDeleteProperty   
	XDestroySubwindows   
	XDestroyWindow   
	XDisplayName   
	XDrawArc   
	XDrawArcs   
	XDrawLine   
	XDrawLines   
	XDrawPoint   
	XDrawPoints   
	XDrawRectangle   
	XDrawRectangles   
	XDrawSegments   
	XGetErrorText   
	XGetErrorDatabaseText   
	XSetErrorHandler   
	XSetIOErrorHandler   
	_XEventToWire   
	XFetchName   
	XGetIconName   
	XFillArc   
	XFillArcs   
	XFillPolygon   
	XFillRectangle   
	XFillRectangles   
	XFlush   
	XLoadQueryFont   
	XFreeFont   
	XQueryFont   
	XListFonts   
	XFreeFontNames   
	XListFontsWithInfo   
	XFreeFontInfo   
	XFreeColormap   
	XFreeColors   
	XFreeCursor   
	_XFreeExtData   
	XFreeGC   
	XFreePixmap   
	XActivateScreenSaver   
	XResetScreenSaver   
	XForceScreenSaver   
	XSetArcMode   
	XSetFillRule   
	XSetFillStyle   
	XSetGraphicsExposures   
	XSetSubwindowMode   
	XGeometry   
	XGetAtomName   
	XAllocNamedColor   
	XGetDefault   
	XGetFontPath   
	XFreeFontPath   
	XGetFontProperty   
	XGetGeometry   
	XAllocColor   
	XGetSizeHints   
	XGetWMHints   
	XGetZoomHints   
	XGetNormalHints   
	XGetIconSizes   
	XGetCommand   
	XGetTransientForHint   
	XGetClassHint   
	XGetInputFocus   
	XGetImage   
	XGetSubImage   
	XGetKeyboardControl   
	XGetMotionEvents   
	XGetPointerControl   
	XGetPointerMapping   
	XGetKeyboardMapping   
	XGetWindowProperty   
	XGetSelectionOwner   
	XGetScreenSaver   
	XGetStandardColormap   
	XGetWindowAttributes   
	XGrabButton   
	XGrabKey   
	XGrabKeyboard   
	XGrabPointer   
	XGrabServer   
	XAddHost   
	XRemoveHost   
	XAddHosts   
	XRemoveHosts   
	XIfEvent   
	XCreateImage   
	_XSetImage   
	_XInitImageFuncPtrs   
	XDrawImageString   
	XDrawImageString16   
	XInitExtension   
	XAddExtension   
	XEHeadOfExtensionList   
	XAddToExtensionList   
	XFindOnExtensionList   
	XESetCreateGC   
	XESetCopyGC   
	XESetFlushGC   
	XESetFreeGC   
	XESetCreateFont   
	XESetFreeFont   
	XESetCloseDisplay   
	XESetWireToEvent   
	XESetEventToWire   
	XESetWireToError   
	XESetError   
	XESetErrorString   
	XESetPrintErrorValues   
	XInstallColormap   
	XInternAtom   
	XKeycodeToKeysym   
	XKeysymToKeycode   
	XLookupKeysym   
	XRefreshKeyboardMapping   
	XLookupString   
	XRebindKeysym   
	XKeysymToString   
	XKillClient   
	XListHosts   
	XListInstalledColormaps   
	XListProperties   
	XListExtensions   
	XFreeExtensionList   
	XLoadFont   
	XLookupColor   
	XLowerWindow   
	XConnectionNumber   
	XRootWindow   
	XDefaultScreen   
	XDefaultRootWindow   
	XDefaultVisual   
	XDefaultGC   
	XBlackPixel   
	XWhitePixel   
	XAllPlanes   
	XQLength   
	XDisplayWidth   
	XDisplayHeight   
	XDisplayWidthMM   
	XDisplayHeightMM   
	XDisplayPlanes   
	XDisplayCells   
	XScreenCount   
	XServerVendor   
	XProtocolVersion   
	XProtocolRevision   
	XVendorRelease   
	XDisplayString   
	XDefaultDepth   
	XDefaultColormap   
	XBitmapUnit   
	XBitmapBitOrder   
	XBitmapPad   
	XImageByteOrder   
	XNextRequest   
	XLastKnownRequestProcessed   
	XScreenOfDisplay   
	XDefaultScreenOfDisplay   
	XDisplayOfScreen   
	XRootWindowOfScreen   
	XBlackPixelOfScreen   
	XWhitePixelOfScreen   
	XDefaultColormapOfScreen   
	XDefaultDepthOfScreen   
	XDefaultGCOfScreen   
	XDefaultVisualOfScreen   
	XWidthOfScreen   
	XHeightOfScreen   
	XWidthMMOfScreen   
	XHeightMMOfScreen   
	XPlanesOfScreen   
	XCellsOfScreen   
	XMinCmapsOfScreen   
	XMaxCmapsOfScreen   
	XDoesSaveUnders   
	XDoesBackingStore   
	XEventMaskOfScreen   
	XScreenNumberOfScreen   
	XDestroyImage   
	XGetPixel   
	XPutPixel   
	XSubImage   
	XAddPixel   
	XNoOp   
	XMapRaised   
	XMapSubwindows   
	XMapWindow   
	XMaskEvent   
	XMaxRequestSize   
	XResourceManagerString   
	XDisplayMotionBufferSize   
	XDisplayKeycodes   
	XVisualIDFromVisual   
	XGetModifierMapping   
	XSetModifierMapping   
	XNewModifiermap   
	XFreeModifiermap   
	XInsertModifiermapEntry   
	XDeleteModifiermapEntry   
	XMoveWindow   
	XNextEvent   
	XOpenDisplay   
	_XFreeDisplayStructure   
	XParseColor   
	XParseGeometry   
	XPeekEvent   
	XPeekIfEvent   
	XEventsQueued   
	XPending   
	XSetWindowBackgroundPixmap   
	XSetWindowBorderPixmap   
	XPolygonRegion   
	XDrawText   
	XDrawText16   
	XPutBackEvent   
	_XReverse_Bytes   
	XPutImage   
	XQueryBestSize   
	XQueryColor   
	XQueryColors   
	XQueryBestCursor   
	XQueryExtension   
	XQueryKeymap   
	XQueryPointer   
	XQueryBestStipple   
	XQueryTextExtents16   
	XQueryTextExtents   
	XQueryBestTile   
	XQueryTree   
	XRaiseWindow   
	XReadBitmapFile   
	XRecolorCursor   
	XConfigureWindow   
	XCreateRegion   
	XClipBox   
	XUnionRectWithRegion   
	XSetRegion   
	XDestroyRegion   
	XOffsetRegion   
	XShrinkRegion   
	XIntersectRegion   
	XUnionRegion   
	XSubtractRegion   
	XXorRegion   
	XEmptyRegion   
	XEqualRegion   
	XPointInRegion   
	XRectInRegion   
	XReparentWindow   
	XRestackWindows   
	XRotateWindowProperties   
	XScreenResourceString   
	XSelectInput   
	XSendEvent   
	XSetBackground   
	XSetClipRectangles   
	_XSetClipRectangles   
	XSetClipMask   
	XSetClipOrigin   
	XSetDashes   
	XSetFontPath   
	XSetFont   
	XSetForeground   
	XSetFunction   
	XSetSizeHints   
	XSetWMHints   
	XSetZoomHints   
	XSetNormalHints   
	XSetIconSizes   
	XSetCommand   
	XSetStandardProperties   
	XSetTransientForHint   
	XSetClassHint   
	XSetInputFocus   
	XSetLineAttributes   
	XSetPlaneMask   
	XSetPointerMapping   
	XChangeKeyboardMapping   
	XSetSelectionOwner   
	XSetScreenSaver   
	XSetState   
	XSetStipple   
	XSetStandardColormap   
	XSetTile   
	XSetTSOrigin   
	XRotateBuffers   
	XFetchBuffer   
	XFetchBytes   
	XStoreBuffer   
	XStoreBytes  
	XStoreColor   
	XStoreColors   
	XStoreNamedColor   
	XStoreName   
	XSetIconName   
	_XInitKeysymDB   
	XStringToKeysym   
	XSync   
	_XSyncFunction   
	XSynchronize   
	XSetAfterFunction   
	XDrawString   
	XDrawString16   
	XTextExtents   
	XTextWidth   
	XTextExtents16   
	XTextWidth16   
	XTranslateCoordinates   
	XUndefineCursor   
	XUngrabButton   
	XUngrabKeyboard   
	XUngrabKey   
	XUngrabPointer   
	XUngrabServer   
	XUninstallColormap   
	XUnloadFont   
	XUnmapSubwindows   
	XUnmapWindow   
	XGetVisualInfo   
	XMatchVisualInfo   
	XWarpPointer   
	XWindowEvent   
	XCreateWindow   
	_XProcessWindowAttributes   
	XWriteBitmapFile   
	_XFlush   
	_XEventsQueued   
	_XReadEvents   
	_XRead   
	_XReadPad   
	_XSend   
	_XAllocID   
	_XSetLastRequestRead   
	_XReply   
	_XEatData   
	_XEnq   
	_XUnknownWireEvent   
	_XUnknownNativeEvent   
	_XWireToEvent   
	_XDefaultIOError   
	_XDefaultError   
	_XDefaultWireError   
	_XError   
	_XIOError   
	_XAllocScratch   
	_XVIDtoVisual   
	XFree   
	_XGetHostname   
	_XScreenOfWindow   
	_XAllocIDs   
	_XAllocTemp   
	_XFreeTemp   
	XrmInitialize   
	XrmGetDatabase   
	XrmSetDatabase   
	XrmStringToQuarkList   
	XrmStringToBindingQuarkList   
	XrmCombineDatabase   
	XrmMergeDatabases   
	XrmQPutResource   
	XrmPutResource   
	XrmQPutStringResource   
	XrmPutStringResource   
	XrmPutLineResource   
	XrmGetStringDatabase   
	XrmGetFileDatabase   
	XrmCombineFileDatabase   
	XrmEnumerateDatabase   
	XrmPutFileDatabase   
	XrmQGetSearchList   
	XrmQGetSearchResource   
	XrmQGetResource   
	XrmGetResource   
	XrmLocaleOfDatabase   
	XrmDestroyDatabase   
	XGetGCValues   
	XGetWMSizeHints   
	XGetWMNormalHints   
	XGetRGBColormaps   
	XGetTextProperty   
	XGetWMName   
	XGetWMIconName   
	XGetWMClientMachine   
	XGetWMColormapWindows   
	XGetWMProtocols   
	XIconifyWindow   
	XListPixmapFormats   
	XAllocSizeHints   
	XAllocStandardColormap   
	XAllocWMHints   
	XAllocClassHint   
	XAllocIconSize   
	XReconfigureWMWindow   
	XSetWMSizeHints   
	XSetWMNormalHints   
	XSetRGBColormaps   
	XSetTextProperty   
	XSetWMName   
	XSetWMIconName   
	XSetWMClientMachine   
	XSetWMColormapWindows   
	XSetWMProperties   
	XSetWMProtocols   
	XStringListToTextProperty   
	XTextPropertyToStringList   
	XFreeStringList   
	XWMGeometry   
	XWithdrawWindow   
	XauDisposeAuth   
	XauGetBestAuthByAddr   
	XauFileName   
	XauReadAuth   
	XcmsCIELabToCIEXYZ   
	XcmsCIEXYZToCIELab   
	XcmsCIELabClipab   
	XcmsCIELabClipL   
	XcmsCIELabClipLab   
	XcmsCIELabQueryMinL   
	XcmsCIELabQueryMaxC   
	XcmsCIELabQueryMaxL   
	_XcmsCIELabQueryMaxLCRGB   
	XcmsCIELabQueryMaxLC   
	XcmsCIELabWhiteShiftColors   
	XcmsCIELuvToCIEuvY   
	XcmsCIEuvYToCIELuv   
	XcmsCIELuvClipuv   
	XcmsCIELuvClipL   
	XcmsCIELuvClipLuv   
	XcmsCIELuvQueryMinL   
	XcmsCIELuvQueryMaxC   
	XcmsCIELuvQueryMaxL   
	_XcmsCIELuvQueryMaxLCRGB   
	XcmsCIELuvQueryMaxLC   
	XcmsCIELuvWhiteShiftColors   
	XcmsCIEuvYToCIEXYZ   
	XcmsCIEXYZToCIEuvY   
	XcmsCIExyYToCIEXYZ   
	XcmsCIEXYZToCIExyY   
	XcmsTekHVCToCIEuvY   
	XcmsCIEuvYToTekHVC   
	_XcmsTekHVC_CheckModify   
	XcmsTekHVCClipC   
	XcmsTekHVCClipV   
	XcmsTekHVCClipVC   
	XcmsTekHVCQueryMinV   
	XcmsTekHVCQueryMaxC   
	XcmsTekHVCQueryMaxV   
	_XcmsTekHVCQueryMaxVCRGB   
	XcmsTekHVCQueryMaxVC   
	XcmsTekHVCQueryMaxVSamples   
	XcmsTekHVCWhiteShiftColors   
	XcmsAddColorSpace   
	XcmsAddFunctionSet   
	XcmsAllocNamedColor   
	XcmsAllocColor   
	XcmsCreateCCC   
	XcmsDefaultCCC   
	XcmsFreeCCC   
	_XcmsAddCmapRec   
	_XcmsCopyCmapRecAndFree   
	_XcmsDeleteCmapRec   
	XcmsCCCOfColormap   
	_XcmsCopyISOLatin1Lowered   
	_XcmsResolveColorString   
	_XcmsConvertColorsWithWhitePt   
	_XcmsEqualWhitePts   
	_XcmsDIConvertColors   
	_XcmsDDConvertColors   
	XcmsConvertColors   
	_XcmsRegFormatOfPrefix   
	XcmsFormatOfPrefix   
	_XcmsCopyPointerArray   
	_XcmsFreePointerArray   
	_XcmsPushPointerArray   
	_XcmsInitDefaultCCCs   
	_XcmsInitScrnInfo   
	_XcmsFreeIntensityMaps   
	_XcmsGetIntensityMap   
	_XcmsGetTableType0   
	_XcmsGetTableType1   
	_XcmsValueCmp   
	_XcmsIntensityCmp   
	_XcmsValueInterpolation   
	_XcmsIntensityInterpolation   
	_XcmsTableSearch   
	_XcmsMatVec   
	XcmsCIEXYZToRGBi   
	XcmsRGBiToCIEXYZ   
	XcmsRGBiToRGB   
	XcmsRGBToRGBi   
	_XcmsLRGB_InitScrnDefault   
	XcmsLookupColor   
	_XcmsCubeRoot   
	_XcmsSquareRoot   
	XcmsDisplayOfCCC   
	XcmsVisualOfCCC   
	XcmsScreenNumberOfCCC   
	XcmsScreenWhitePointOfCCC   
	XcmsClientWhitePointOfCCC   
	XcmsPrefixOfFormat   
	_XcmsGetElement   
	_XcmsGetProperty   
	XcmsQueryBlack   
	XcmsQueryBlue   
	XcmsQueryGreen   
	XcmsQueryRed   
	XcmsQueryWhite   
	XcmsQueryColor   
	XcmsQueryColors   
	XcmsSetWhitePoint   
	XcmsSetCompressionProc   
	XcmsSetWhiteAdjustProc   
	_XcmsSetGetColors   
	XcmsStoreColor   
	XcmsStoreColors   
	_XcmsCosine   
	_XcmsSine   
	_XcmsArcTangent   
	_XcmsRGB_to_XColor   
	_XColor_to_XcmsRGB   
	_XcmsResolveColor   
	_XcmsUnresolveColor   
	_XUnresolveColor   
	_XParseBaseFontNameList   
	XCreateFontSet   
	XFontsOfFontSet   
	XBaseFontNameListOfFontSet   
	XLocaleOfFontSet   
	XContextDependentDrawing   
	XExtentsOfFontSet   
	XFreeFontSet   
	XVaCreateNestedList   
	XGetIMValues   
	XCreateIC   
	XDestroyIC   
	XGetICValues   
	XSetICValues   
	XSetICFocus   
	XUnsetICFocus   
	XIMOfIC   
	XmbResetIC   
	XwcResetIC   
	XmbLookupString   
	XwcLookupString   
	_XIMCompileResourceList   
	_XCopyToArg   
	XOpenIM   
	XCloseIM   
	XDisplayOfIM   
	XLocaleOfIM   
	XSetLocaleModifiers   
	XSupportsLocale   
	_XlcValidModSyntax   
	_XlcDefaultMapModifiers   
	_XlcAddLoader   
	_XlcCurrentLC   
	XmbSetWMProperties   
	XmbDrawText   
	XmbDrawString   
	XmbDrawImageString   
	XmbTextEscapement   
	XmbTextExtents   
	XmbTextPerCharExtents   
	XwcDrawText   
	XwcDrawString   
	XwcDrawImageString   
	XwcTextEscapement   
	XwcTextExtents   
	XwcTextPerCharExtents   
	XFilterEvent   
	_XRegisterFilterByMask   
	_XRegisterFilterByType   
	_XUnregisterFilter   
	XDefaultString   
	_XlcDefaultLoader   
	_XrmInitParseInfo   
	XmbTextPropertyToTextList   
	XmbTextListToTextProperty   
	XwcTextPropertyToTextList   
	XwcFreeStringList   
	XwcTextListToTextProperty   
	_X11TransConnectDisplay   
	XGetAtomNames   
	XInitImage   
	XESetBeforeFlush   
	_XFreeAtomTable   
	_XUpdateAtomCache   
	XInternAtoms   
	_XKeyInitialize   
	XConvertCase   
	_XTranslateKey   
	_XTranslateKeySym   
	_XKeysymToModifiers   
	XExtendedMaxRequestSize   
	XReadBitmapFileData   
	_XAsyncErrorHandler   
	_XDeqAsyncHandler   
	_XGetAsyncReply   
	_XGetAsyncData   
	_XPollfdCacheInit   
	_XPollfdCacheAdd   
	_XPollfdCacheDel   
	_XRegisterInternalConnection   
	_XUnregisterInternalConnection   
	XInternalConnectionNumbers   
	XProcessInternalConnection   
	XAddConnectionWatch   
	XRemoveConnectionWatch   
	_XDeq   
	_XcmsCIEXYZ_ValidSpec   
	_XcmsCIEuvY_ValidSpec   
	XcmsSetCCCOfColormap   
	XDirectionalDependentDrawing   
	XContextualDrawing   
	XSetIMValues   
	XRegisterIMInstantiateCallback   
	XUnregisterIMInstantiateCallback   
	XCreateOC   
	XDestroyOC   
	XOMOfOC   
	XSetOCValues   
	XGetOCValues   
	XOpenOM   
	XCloseOM   
	XSetOMValues   
	XGetOMValues   
	XDisplayOfOM   
	XLocaleOfOM   
	_XlcRemoveLoader   
	_XOpenLC   
	_XCloseLC   
	_XlcCopyFromArg   
	_XlcCopyToArg   
	_XlcCountVaList   
	_XlcVaToArgList   
	_XlcCompileResourceList   
	_XlcGetValues   
	_XlcSetValues   
	XInitThreads   
	XLockDisplay   
	XUnlockDisplay   
	_X11TransFreeConnInfo   
	_X11TransOpenCOTSClient   
	_X11TransOpenCLTSClient   
	_X11TransSetOption  
	_X11TransConnect   
	_X11TransBytesReadable   
	_X11TransRead   
	_X11TransWrite   
	_X11TransReadv   
	_X11TransWritev   
	_X11TransDisconnect   
	_X11TransClose   
	_X11TransCloseForCloning   
	_X11TransIsLocal   
	_X11TransGetMyAddr   
	_X11TransGetPeerAddr   
	_X11TransGetConnectionNumber   
	_X11TransGetHostname   
	_X11TransConvertAddress   
	_XimCbDispatch   
	_XimLookupMBText   
	_XimLookupWCText   
	_XimRegisterFilter   
	_XimUnregisterFilter   
	_XimReregisterFilter   
	_XimRegisterServerFilter   
	_XimUnregisterServerFilter   
	_XimProtoCreateIC   
	_XimCheckDataSize   
	_XimSetHeader   
	_XimProtoIMFree   
	_XimProtoOpenIM   
	_XimICOfXICID   
	_XimSetEventMaskCallback   
	_XimSync   
	_XimProcSyncReply   
	_XimRespSyncReply   
	_XimSyncCallback   
	_XimForwardEvent   
	_XimForwardEventCallback   
	_XimRegisterTriggerKeysCallback   
	_XimGetWindowEventmask   
	_XimTriggerNotify   
	_XimFreeCommitInfo   
	_XimCommitCallback   
	_XimProcError   
	_XimErrorCallback   
	_XimError   
	_Ximctstombs   
	_Ximctstowcs   
	_XimProtoMbLookupString   
	_XimProtoWcLookupString   
	_XimRegProtoIntrCallback   
	_XimFreeProtoIntrCallback   
	_XimDispatchInit   
	_XimProtoEventToWire   
	_XimProtoWireToEvent   
	_XimExtension   
	_XimRegisterIMInstantiateCallback   
	_XimUnRegisterIMInstantiateCallback   
	_XimResetIMInstantiateCallback   
	_XimDestroyIMStructureList   
	_XimServerDestroy   
	_XInitIM   
	_XimLocalFilter   
	_XimLocalGetICValues   
	_XimLocalCreateIC   
	_XimCheckIfLocalProcessing   
	_XimLocalIMFree   
	_XimLocalGetIMValues   
	_XimLocalSetIMValues   
	_XimLocalOpenIM   
	_XimLocalMbLookupString   
	_XimLocalWcLookupString   
	_XimParseStringFile   
	_XimSetICValueData   
	_XimLocalSetICValues   
	_XimSetIMResourceList   
	_XimSetICResourceList   
	_XimSetInnerIMResourceList   
	_XimSetInnerICResourceList   
	_XimCheckCreateICValues   
	_XimGetResourceListRec   
	_XimSetIMMode   
	_XimCheckIMMode   
	_XimSetICMode   
	_XimCheckICMode   
	_XimSetLocalIMDefaults   
	_XimSetICDefaults   
	_XimDecodeLocalIMAttr   
	_XimDecodeLocalICAttr   
	_XimCheckLocalInputStyle   
	_XimEncodeLocalIMAttr   
	_XimEncodeLocalICAttr   
	_XimGetCurrentIMValues   
	_XimSetCurrentIMValues   
	_XimGetCurrentICValues   
	_XimSetCurrentICValues   
	_XimInitialResourceInfo   
	_XimDecodeIMATTRIBUTE   
	_XimDecodeICATTRIBUTE   
	_XimEncodeIMATTRIBUTE   
	_XimEncodeICATTRIBUTE   
	_XimGetAttributeID   
	_XimThaiFilter   
	_XimThaiCreateIC   
	_XimCheckIfThaiProcessing   
	_XimThaiOpenIM   
	_XimThaiIMFree   
	_XimThaiCloseIM   
	_XimXConf   
	_XimConnect   
	_XimShutdown   
	_XimFlush   
	_XimFilterWaitEvent   
	_XimFreeTransIntrCallback   
	_XimTransFilterWaitEvent   
	_XimTransInternalConnection   
	_XimTransFlush   
	_XimTransConf   
	_XlcParseCharSet   
	_XlcInitCTInfo   
	_XlcGetCSValues   
	_XlcGetCharSet   
	_XlcAddCharSet   
	_XlcCreateDefaultCharSet   
	_XlcSetConverter   
	_XlcOpenConverter   
	_XlcCloseConverter   
	_XlcConvert   
	_XlcResetConverter   
	_XlcGetResource   
	_XlcGetLocaleDataBase   
	_XlcDestroyLocaleDataBase   
	_XlcCreateLocaleDataBase   
	_XlcEucLoader   
	_XlcFileName   
	_XlcResolveLocaleName   
;REMOVED	_XlcResolveDBName   
	_XlcResolveI18NPath   
	_XlcGenericLoader   
	_XlcInitLoader   
	_XmbTextPropertyToTextList   
	_XwcTextPropertyToTextList   
	_XwcFreeStringList   
	_XGetLCValues   
	_XlcDestroyLC   
	_XlcCreateLC   
	_XrmDefaultInitParseInfo   
	_XlcSjisLoader   
	_Xlcmbtowc   
	_Xlcwctomb   
	_Xlcmbstowcs   
	_Xlcwcstombs   
	_Xmbtowc   
	_Xwctomb   
	_Xmbstowcs   
	_Xwcstombs   
	_Xwcscpy   
	_Xwcsncpy   
	_Xwcslen   
	_Xwcscmp   
	_Xwcsncmp   
	_XmbTextListToTextProperty   
	_XwcTextListToTextProperty   
;	_XlcUtfLoader   
	_XlcCompareISOLatin1   
	_XlcNCompareISOLatin1   
	_XmbDefaultTextEscapement   
	_XwcDefaultTextEscapement   
	_XmbDefaultTextExtents   
	_XwcDefaultTextExtents   
	_XmbDefaultTextPerCharExtents   
	_XwcDefaultTextPerCharExtents   
	_XmbDefaultDrawString   
	_XwcDefaultDrawString   
	_XmbDefaultDrawImageString   
	_XwcDefaultDrawImageString   
	_XomGenericOpenOM   
	_XInitOM   
	_XmbGenericDrawImageString   
	_XwcGenericDrawImageString   
	_XomGenericDrawString   
	_XmbGenericDrawString   
	_XwcGenericDrawString   
	_XmbGenericTextEscapement   
	_XwcGenericTextEscapement   
	_XomGenericTextExtents   
	_XmbGenericTextExtents   
	_XwcGenericTextExtents   
	_XmbGenericTextPerCharExtents   
	_XwcGenericTextPerCharExtents   
	_XomConvert   
	_XomInitConverter   
	_Xmblen     
	_XimGetResourceListRecByQuark   
	_XimSetIMValueData   
	_XimGetIMValueData   
	_XimGetICValueData   
	_XimMakeIMAttrIDList   
	_XimMakeICAttrIDList   
	_XimWrite   
	_XimRead   
	_XimRegisterDispatcher   
	_XimTransRegisterDispatcher   
	_XimTransCallDispatcher   
	_XimTransWrite   
	_XimTransRead   
	_XimXTransFreeConnInfo   
	_XimXTransOpenCOTSClient   
	_XimXTransOpenCLTSClient   
	_XimXTransSetOption   
	_XimXTransConnect   
	_XimXTransBytesReadable   
	_XimXTransRead   
	_XimXTransWrite   
	_XimXTransReadv   
	_XimXTransWritev   
	_XimXTransDisconnect   
	_XimXTransClose   
	_XimXTransCloseForCloning   
	_XimXTransIsLocal   
	_XimXTransGetMyAddr   
	_XimXTransGetPeerAddr   
	_XimXTransGetConnectionNumber   
	_XimXTransGetHostname   
	_Xdebug DATA  
	Xutf8TextPropertyToTextList 
	Xutf8TextListToTextProperty	 
	Xutf8LookupString
	XkbIgnoreExtension  
	XkbOpenDisplay  
	XkbQueryExtension  
	XkbUseExtension  
	XkbLibraryVersion  
	XkbSetXlibControls  
	XkbGetXlibControls  
	XkbSetAtomFuncs  
	XkbKeycodeToKeysym  
	XkbKeysymToModifiers  
	XkbLookupKeySym  
	XkbLookupKeyBinding  
	XkbTranslateKeyCode  
	XkbTranslateKeySym  
	XkbSetAutoRepeatRate  
	XkbGetAutoRepeatRate  
	XkbChangeEnabledControls  
	XkbDeviceBell  
	XkbForceDeviceBell  
	XkbDeviceBellEvent  
	XkbBell  
	XkbForceBell  
	XkbBellEvent  
	XkbSelectEvents  
	XkbSelectEventDetails  
	XkbNoteMapChanges  
	XkbNoteNameChanges  
	XkbGetIndicatorState  
	XkbGetIndicatorMap  
	XkbSetIndicatorMap  
	XkbGetNamedIndicator  
	XkbGetNamedDeviceIndicator  
	XkbSetNamedIndicator  
	XkbSetNamedDeviceIndicator  
	XkbLockModifiers  
	XkbLatchModifiers  
	XkbLockGroup  
	XkbLatchGroup  
	XkbSetServerInternalMods  
	XkbSetIgnoreLockMods  
	XkbVirtualModsToReal  
	XkbComputeEffectiveMap  
	XkbInitCanonicalKeyTypes  
	XkbAllocKeyboard  
	XkbFreeKeyboard  
	XkbAllocClientMap  
	XkbAllocServerMap  
	XkbFreeClientMap  
	XkbFreeServerMap  
	XkbAddKeyType  
	XkbAllocIndicatorMaps  
	XkbFreeIndicatorMaps  
	XkbGetMap  
	XkbGetUpdatedMap  
	XkbGetMapChanges  
	XkbRefreshKeyboardMapping  
	XkbGetKeyTypes  
	XkbGetKeySyms  
	XkbGetKeyActions  
	XkbGetKeyBehaviors  
	XkbGetVirtualMods  
	XkbGetKeyExplicitComponents  
	XkbGetKeyModifierMap  
	XkbAllocControls  
	XkbFreeControls  
	XkbGetControls  
	XkbSetControls  
	XkbAllocCompatMap  
	XkbFreeCompatMap  
	XkbGetCompatMap  
	XkbSetCompatMap  
	XkbAllocNames  
	XkbGetNames  
	XkbSetNames  
	XkbChangeNames  
	XkbFreeNames  
	XkbGetState  
	XkbSetMap  
	XkbChangeMap  
	XkbSetDetectableAutoRepeat  
	XkbGetDetectableAutoRepeat  
	XkbSetAutoResetControls  	
	XkbGetAutoResetControls  
	XkbCopyKeyType  
	XkbCopyKeyTypes  
	XkbResizeKeyType  
	XkbResizeKeySyms  
	XkbResizeKeyActions  
	XkbChangeTypesOfKey  
	XkbListComponents  
	XkbFreeComponentList  
	XkbGetKeyboard  
	XkbGetKeyboardByName  
	XkbAddDeviceLedInfo  
	XkbResizeDeviceButtonActions  
	XkbAllocDeviceInfo  
	XkbFreeDeviceInfo  
	XkbNoteDeviceChanges  
	XkbGetDeviceInfo  
	XkbGetDeviceInfoChanges  
	XkbGetDeviceButtonActions  
	XkbGetDeviceLedInfo  
	XkbSetDeviceInfo  
	XkbChangeDeviceInfo  
	XkbSetDeviceLedInfo  
	XkbSetDeviceButtonActions  
	XkbToControl  
	XkbSetDebuggingFlags  
	_XkbInternAtomFunc  
	_XkbGetAtomNameFunc  
	_XkbReloadDpy  
	_XKeycodeToKeysym  
	_XKeysymToKeycode  
	_XLookupKeysym  
	_XRefreshKeyboardMapping  
	_XLookupString 
	_XkbNoteCoreMapChanges  
	_XkbInitReadBuffer  
	_XkbSkipReadBufferData  
	_XkbCopyFromReadBuffer  
	_XkbReadCopyKeySyms  
	_XkbWriteCopyKeySyms  
	_XkbReadBufferCopyKeySyms  
	_XkbPeekAtReadBuffer  
	_XkbGetReadBufferPtr  
	_XkbFreeReadBuffer 
	_XkbGetReadBufferCountedString  
	_XkbGetCharset  
	_XkbGetConverters  
	XkbGetGeometry  
	XkbAddGeomShape  
	XkbAddGeomOutline  
	XkbComputeShapeBounds  
	XkbAddGeomDoodad  
	XkbAddGeomColor  
	XkbAddGeomOverlayRow  
	XkbAddGeomSection  
	XkbAddGeomRow  
	XkbAddGeomKey  
	XkbComputeSectionBounds  
	XkbAllocGeometry  
	XkbAddGeomProperty  
	XkbAddGeomOverlay  
	XkbComputeShapeTop  
	XkbFindOverlayForKey  
	XkbAllocGeomKeyAliases  
	XkbSetGeometry  
	XkbXlibControlsImplemented  
	XkbTranslateKey  
	XkbAddGeomOverlayKey  
	XkbNoteControlsChanges  
	XkbGetKeyVirtualModMap  
	XkbComputeRowBounds  
	XkbGetNamedGeometry  
	XkbKeyTypesForCoreSymbols  
	XkbApplyCompatMapToKey  
	XkbUpdateMapFromCore  
	XkbUpdateActionVirtualMods  
	XkbUpdateKeyTypeVirtualMods  
	XkbApplyVirtualModChanges  
	XkbFreeGeomProperties  
	XkbFreeGeomKeyAliases  
	XkbFreeGeomColors  
	XkbFreeGeomPoints  
	XkbFreeGeomOutlines  
	XkbFreeGeomShapes  
	XkbFreeGeomOverlayKeys  
	XkbFreeGeomOverlayRows  
	XkbFreeGeomOverlays  
	XkbFreeGeomKeys  
	XkbFreeGeomRows  
	XkbFreeGeomSections  
	XkbFreeGeomDoodads  
	XkbFreeGeometry  
	XkbAllocGeomProps  
	XkbAllocGeomColors  
	XkbAllocGeomShapes  
	XkbAllocGeomSections  
	XkbAllocGeomOverlays  
	XkbAllocGeomOverlayRows  
	XkbAllocGeomOverlayKeys  
	XkbAllocGeomDoodads  
	XkbAllocGeomSectionDoodads  
	XkbAllocGeomOutlines  
	XkbAllocGeomRows  
	XkbAllocGeomPoints  
	XkbAllocGeomKeys  
	XkbAddGeomKeyAlias  
	_XkeyTable  
	_Xevent_to_mask  
	_qfree  
	_XIOErrorFunction  
	_XErrorFunction  
	_XHeadOfDisplayList  
	XcmsCIELabColorSpace  
	XcmsCIELuvColorSpace  
	XcmsCIEXYZColorSpace  
	XcmsCIEuvYColorSpace  
	XcmsCIExyYColorSpace  
	XcmsTekHVCColorSpace  
	XcmsUNDEFINEDColorSpace  
	_XcmsDIColorSpacesInit  
	_XcmsDIColorSpaces  
	_XcmsDDColorSpacesInit  
	_XcmsDDColorSpaces  
	_XcmsSCCFuncSetsInit  
	_XcmsSCCFuncSets  
	_XcmsCIEXYZ_prefix  
	_XcmsCIEuvY_prefix  
	_XcmsCIExyY_prefix  
	_XcmsCIELab_prefix  
	_XcmsCIELuv_prefix  
	_XcmsTekHVC_prefix  
	_XcmsRGBi_prefix  
	_XcmsRGB_prefix  
	_XcmsRegColorSpaces  
	XcmsRGBiColorSpace  
	XcmsRGBColorSpace  
	XcmsLinearRGBFunctionSet  
	_X11TransSocketINETFuncs  
	_X11TransSocketTCPFuncs  
	_XimXTransSocketINETFuncs  
	_XimXTransSocketTCPFuncs  
	_XimImSportRec  
	_XimTransportRec  
	_XlcGenericMethods  
	_XlcPublicMethods  
#ifdef HAS_THREADS
	_XCreateMutex_fn DATA
	_XFreeMutex_fn DATA
	_XLockMutex_fn DATA
	_XUnlockMutex_fn DATA
	_Xglobal_lock DATA
#endif
#ifdef __UNIXOS2__
; OS/2 specific exports
  __XOS2RedirRoot	
  __XOS2RedirRoot1	
  _XGetScanlinePad
  _XGetBitsPerPixel
  _Xsetlocale  
  XkbGetPerClientControls
  XkbSetPerClientControls
  Xutf8DrawString
  Xutf8TextExtents
#endif
#endif

/* $Xorg: X11-def.cpp,v 1.3 2000/08/17 19:44:59 cpqbld Exp $ */
/* $XFree86: xc/lib/X11/X11-def.cpp,v 1.15 2003/06/10 17:03:51 dawes Exp $ */
