[comment {-*- tcl -*- doctools = compress/header.inc}]
[include common/trf_version.inc]
[manpage_begin [vset compress] n [vset trf_version]]
[titledesc "Data compression \"[vset compress]\""]
[include common/trf_header.inc]
[description]

The command [cmd [vset compress]] is one of several data compressions
provided by the package [package trf]. See [syscmd trf-intro] for an
overview of the whole package.
