# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Temp
version:      0.22
version_from: Temp.pm
installdirs:  perl
requires:
    Fcntl:                         1.03
    File::Path:                    0
    File::Spec:                    0.8
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
