LIBRARY XIE
VERSION LIBRARY_VERSION
EXPORTS
 XieAbort
 XieAllocatePhotofloGraph
 XieAwait
 XieCreateColorList
 XieCreateLUT
 XieCreatePhotoflo
 XieCreatePhotomap
 XieCreatePhotospace
 XieCreateROI
 XieDestroyColorList
 XieDestroyLUT
 XieDestroyPhotoflo
 XieDestroyPhotomap
 XieDestroyPhotospace
 XieDestroyROI
 XieExecuteImmediate
 XieExecutePhotoflo
 XieFloArithmetic
 XieFloBandCombine
 XieFloBandExtract
 XieFloBandSelect
 XieFloBlend
 XieFloCompare
 XieFloConstrain
 XieFloConvertFromIndex
 XieFloConvertFromRGB
 XieFloConvertToIndex
 XieFloConvertToRGB
 XieFloConvolve
 XieFloDither
 XieFloExportClientHistogram
 XieFloExportClientLUT
 XieFloExportClientPhoto
 XieFloExportClientROI
 XieFloExportDrawable
 XieFloExportDrawablePlane
 XieFloExportLUT
 XieFloExportPhotomap
 XieFloExportROI
 XieFloGeometry
 XieFloImportClientLUT
 XieFloImportClientPhoto
 XieFloImportClientROI
 XieFloImportDrawable
 XieFloImportDrawablePlane
 XieFloImportLUT
 XieFloImportPhotomap
 XieFloImportROI
 XieFloLogical
 XieFloMatchHistogram
 XieFloMath
 XieFloPasteUp
 XieFloPoint
 XieFloUnconstrain
 XieFreeEncodeJPEGBaseline
 XieFreeEncodeJPEGLossless
 XieFreePasteUpTiles
 XieFreePhotofloGraph
 XieFreeTechniques
 XieGetClientData
 XieInitialize
 XieModifyPhotoflo
 XiePurgeColorList
 XiePutClientData
 XieQueryColorList
 XieQueryPhotoflo
 XieQueryPhotomap
 XieQueryTechniques
 XieRedefinePhotoflo
 XieTecCIELabToRGB
 XieTecCIEXYZToRGB
 XieTecClipScale
 XieTecColorAllocAll
 XieTecColorAllocMatch
 XieTecColorAllocRequantize
 XieTecConvolveConstant
 XieTecDecodeG31D
 XieTecDecodeG32D
 XieTecDecodeG42D
 XieTecDecodeJPEGBaseline
 XieTecDecodeJPEGLossless
 XieTecDecodeTIFF2
 XieTecDecodeTIFFPackBits
 XieTecDecodeUncompressedSingle
 XieTecDecodeUncompressedTriple
 XieTecDitherOrderedParam
 XieTecEncodeG31D
 XieTecEncodeG32D
 XieTecEncodeG42D
 XieTecEncodeJPEGBaseline
 XieTecEncodeJPEGLossless
 XieTecEncodeServerChoice
 XieTecEncodeTIFF2
 XieTecEncodeTIFFPackBits
 XieTecEncodeUncompressedSingle
 XieTecEncodeUncompressedTriple
 XieTecGeomAntialiasByArea
 XieTecGeomAntialiasByLowpass
 XieTecGeomGaussian
 XieTecGeomNearestNeighbor
 XieTecHistogramGaussian
 XieTecHistogramHyperbolic
 XieTecRGBToCIELab
 XieTecRGBToCIEXYZ
 XieTecRGBToYCC
 XieTecRGBToYCbCr
 XieTecWhiteAdjustCIELabShift
 XieTecYCCToRGB
 XieTecYCbCrToRGB
/* $Xorg: XIE-def.cpp,v 1.3 2000/08/17 19:45:25 cpqbld Exp $ */
