Project = nvram
Install_Dir = /usr/sbin

CFILES = nvram.c
MANPAGES = nvram.8

Extra_Frameworks = -framework CoreFoundation -framework IOKit

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
