Project = hostinfo
Install_Dir = /usr/bin

CFILES = hostinfo.c
MANPAGES = hostinfo.8

Extra_CC_Flags = -Wall -Werror -mdynamic-no-pic
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
