##
# Makefile.fetch for tclapplescript
##
# Daniel A. Steffen <das@users.sourceforge.net>
##

include Makefile ../Fetch.make

CvsTag               = -r tclapplescript-1_0
Release              = 1.0
UrlFile              = TclAppleScript-$(Release)-Source
