##
# Makefile.fetch for trf
##
# Daniel A. Steffen <das@users.sourceforge.net>
##

include Makefile $(CURDIR)/../Fetch.make

CvsTag               = -D "2004-02-19 00:00:00 GMT"
SFProject            = tcltrf
UrlBase              = http://tcltkaqua.sourceforge.net/8.4.6/src
