LIBRARY XEXT
VERSION LIBRARY_VERSION
EXPORTS
 XMITMiscGetBugMode
 XMITMiscQueryExtension
 XMITMiscSetBugMode
 XMissingExtension
 XSetExtensionErrorHandler
 XShapeCombineMask
 XShapeCombineRectangles
 XShapeCombineRegion
 XShapeCombineShape
 XShapeGetRectangles
 XShapeInputSelected
 XShapeOffsetShape
 XShapeQueryExtension
 XShapeQueryExtents
 XShapeQueryVersion
 XShapeSelectInput
#if (defined(__CYGWIN__) && defined(HAS_SHM)) || defined(__UNIXOS2__)
 XShmAttach
 XShmCreateImage
 XShmCreatePixmap
 XShmDetach
;XShmDestroyImage
 XShmGetEventBase
 XShmGetImage
 XShmPixmapFormat
 XShmPutImage
 XShmQueryExtension
 XShmQueryVersion
#endif
 XSyncAwait
 XSyncChangeAlarm
 XSyncChangeCounter
 XSyncCreateAlarm
 XSyncCreateCounter
 XSyncDestroyAlarm
 XSyncDestroyCounter
 XSyncFreeSystemCounterList
 XSyncGetPriority
 XSyncInitialize
 XSyncIntToValue
 XSyncIntsToValue
 XSyncListSystemCounters
 XSyncMaxValue
 XSyncMinValue
 XSyncQueryAlarm
 XSyncQueryCounter
 XSyncQueryExtension
 XSyncSetCounter
 XSyncSetPriority
 XSyncValueAdd
 XSyncValueEqual
 XSyncValueGreaterOrEqual
 XSyncValueGreaterThan
 XSyncValueHigh32
 XSyncValueIsNegative
 XSyncValueIsPositive
 XSyncValueIsZero
 XSyncValueLessOrEqual
 XSyncValueLessThan
 XSyncValueLow32
 XSyncValueSubtract
 XTestFakeInput
 XTestFlush
 XTestGetInput
 XTestMovePointer
 XTestPressButton
 XTestPressKey
 XTestQueryInputSize
 XTestReset
 XTestStopInput
 XextAddDisplay
 XextCreateExtension
 XextDestroyExtension
 XextFindDisplay
 XextRemoveDisplay
 XmbufChangeBufferAttributes
 XmbufChangeWindowAttributes
 XmbufClearBufferArea
 XmbufCreateBuffers
 XmbufCreateStereoWindow
 XmbufDestroyBuffers
 XmbufDisplayBuffers
 XmbufGetBufferAttributes
 XmbufGetScreenInfo
 XmbufGetVersion
 XmbufGetWindowAttributes
 XmbufQueryExtension
 XdbeQueryExtension
 XdbeAllocateBackBufferName
 XdbeDeallocateBackBufferName
 XdbeSwapBuffers
 XdbeBeginIdiom
 XdbeEndIdiom
 XdbeGetVisualInfo
 XdbeFreeVisualInfo
 XdbeGetBackBufferAttributes
 XSecurityQueryExtension
 XSecurityAllocXauth
 XSecurityFreeXauth
 XSecurityGenerateAuthorization
 XSecurityRevokeAuthorization
 XagQueryVersion
 XagCreateAssociation
 XagCreateEmbeddedApplicationGroup
 XagCreateNonembeddedApplicationGroup
 XagDestroyApplicationGroup
 XagDestroyAssociation
 XagGetApplicationGroupAttributes
 XagQueryApplicationGroup
 XLbxQueryExtension
 XLbxGetEventBase
 XLbxQueryVersion
 XcupGetReservedColormapEntries
 XcupQueryVersion
 XcupStoreColors
#if !defined(__CYGWIN__) && !defined(__UNIXOS2__)
 XPanoramiXQueryVersion
 XPanoramiXAllocInfo
 XPanoramiXGetScreenCount
 XPanoramiXGetScreenSize
 XPanoramiXGetState
 XPanoramiXQueryExtension
#endif
 DPMSQueryExtension
 DPMSGetVersion
 DPMSCapable
 DPMSSetTimeouts
 DPMSGetTimeouts
 DPMSEnable
 DPMSDisable
 DPMSForceLevel
 DPMSInfo
 XeviQueryExtension
 XeviQueryVersion
 XeviGetVisualInfo
/* $Xorg: Xext-def.cpp,v 1.3 2000/08/17 19:45:53 cpqbld Exp $ */
/* $XFree86: xc/lib/Xext/Xext-def.cpp,v 1.9 2002/05/31 18:45:44 dawes Exp $ */
