[call [cmd arc] [arg attr]...]

[image figure-02-arc]
[include cat_open.inc]

Note however that it also has the compass rose of closed elements as
its corners, with the center of the arc's circle as the center of the
compass and the other points on the circle the arc is part of.

It handles the attributes

[list_begin definitions]
[include ../attr/anchor.inc]
[include ../attr/clockwise.inc]
[include ../attr/color.inc]
[include ../attr/counterclockwise.inc]
[include ../attr/fillcolor.inc]
[include ../attr/arc_from.inc]
[include ../attr/justify.inc]
[include ../attr/arc_radius.inc]
[include ../attr/stroke.inc]
[include ../attr/style.inc]
[include ../attr/text.inc]
[include ../attr/textcolor.inc]
[include ../attr/textfont.inc]
[include ../attr/arc_to.inc]
[list_end]
