[call [cmd box] [arg attr]...]

[image figure-02-box]
[include cat_closed.inc]

It handles the attributes

[list_begin definitions]
[include ../attr/anchor.inc]
[include ../attr/at.inc]
[include ../attr/color.inc]
[include ../attr/fillcolor.inc]
[include ../attr/height.inc]
[include ../attr/justify.inc]
[include ../attr/slant.inc]
[include ../attr/stroke.inc]
[include ../attr/style.inc]
[include ../attr/text.inc]
[include ../attr/textcolor.inc]
[include ../attr/textfont.inc]
[include ../attr/width.inc]
[include ../attr/with.inc]
[list_end]
