[call [cmd diamond] [arg attr]...]
[call [cmd <>] [arg attr]...]

[image figure-02-diamond]
[include cat_closed.inc]

It handles the attributes

[list_begin definitions]
[include ../attr/anchor.inc]
[include ../attr/diam_aspect.inc]
[include ../attr/at.inc]
[include ../attr/color.inc]
[include ../attr/fillcolor.inc]
[include ../attr/diam_height.inc]
[include ../attr/justify.inc]
[include ../attr/stroke.inc]
[include ../attr/style.inc]
[include ../attr/text.inc]
[include ../attr/textcolor.inc]
[include ../attr/textfont.inc]
[include ../attr/diam_width.inc]
[include ../attr/with.inc]
[list_end]
