[call [cmd text] [arg attr]...]

[image figure-02-text]
[include cat_closed.inc]

It handles the attributes

[list_begin definitions]
[include ../attr/anchor.inc]
[include ../attr/at.inc]
[include ../attr/text_height.inc]
[include ../attr/justify.inc]
[include ../attr/text.inc]
[include ../attr/textcolor.inc]
[include ../attr/textfont.inc]
[include ../attr/text_width.inc]
[include ../attr/with.inc]
[list_end]
