// usr/include
#include <___wctype.h>
#include <__wctype.h>
#include <__xlocale.h>
#include <_abort.h>
#include <_assert.h>
#include <_ctermid.h>
#include <_ctype.h>
#include <_inttypes.h>
#include <_langinfo.h>
#include <_locale.h>
#include <_mb_cur_max.h>
#include <_monetary.h>
#include <_printf.h>
#include <_regex.h>
#include <_static_assert.h>
#include <_stdio.h>
#include <_stdlib.h>
#include <_string.h>
#include <_strings.h>
#include <_time.h>
#include <_types.h>
#include <_types/_intmax_t.h>
#include <_types/_locale_t.h>
#include <_types/_nl_item.h>
#include <_types/_uint16_t.h>
#include <_types/_uint32_t.h>
#include <_types/_uint64_t.h>
#include <_types/_uint8_t.h>
#include <_types/_uintmax_t.h>
#include <_types/_wctrans_t.h>
#include <_types/_wctype_t.h>
#include <_wchar.h>
#include <_wctype.h>
#include <_xlocale.h>
#include <aio.h>
#include <alloca.h>
#include <arpa/inet.h>
#include <assert.h>
#include <bitstring.h>
#include <cpio.h>
#include <crt_externs.h>
#include <ctype.h>
#include <dirent.h>
#include <err.h>
#include <errno.h>
#include <execinfo.h>
#include <fcntl.h>
#include <fmtmsg.h>
#include <fnmatch.h>
#include <fstab.h>
#include <fts.h>
#include <ftw.h>
#include <getopt.h>
#include <glob.h>
#include <inttypes.h>
#include <iso646.h>
#include <langinfo.h>
#include <libc.h>
#include <libgen.h>
#include <limits.h>
#include <locale.h>
#include <memory.h>
#include <monetary.h>
#include <ndbm.h>
#include <nl_types.h>
#include <paths.h>
#include <poll.h>
#include <readpassphrase.h>
#include <regex.h>
#include <runetype.h>
#include <search.h>
#include <secure/_common.h>
#include <secure/_stdio.h>
#include <secure/_string.h>
#include <secure/_strings.h>
#include <semaphore.h>
#include <signal.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <struct.h>
#include <sys/acl.h>
#include <sys/rbtree.h>
#include <sys/statvfs.h>
#include <sysexits.h>
#include <syslog.h>
#include <tar.h>
#include <termios.h>
#include <time.h>
#include <ulimit.h>
#include <unistd.h>
#include <util.h>
#include <utime.h>
#include <utmpx.h>
#include <wchar.h>
#include <wctype.h>
#include <wordexp.h>
#include <xlocale.h>
#include <xlocale/___wctype.h>
#include <xlocale/_ctype.h>
#include <xlocale/_inttypes.h>
#include <xlocale/_langinfo.h>
#include <xlocale/_monetary.h>
#include <xlocale/_regex.h>
#include <xlocale/_stdio.h>
#include <xlocale/_stdlib.h>
#include <xlocale/_string.h>
#include <xlocale/_time.h>
#include <xlocale/_wchar.h>
#include <xlocale/_wctype.h>

// usr/local/include
#include <ar.h>
#include <libc_private.h>
#include <libkern/OSThermalNotification.h>
#include <os/assumes.h>
#include <os/debug_private.h>
#include <subsystem.h>
#include <thread_stack_pcs.h>

#include <darwintest.h>

T_DECL(fbounds_safety_includes, "sanity check that headers actually build") {
	T_PASS("All tests completed successfully.");
}
