.TH "GAMES" 6 "March 9, 1998" "Apple Computer, Inc."
.SH NAME
games \- terminal-based games
.SH DESCRIPTION
Terminal-based games
and their manual pages
are not included in the Mac OS X release.
In lieu of these,
the \fB/Applications/GrabBag\fR directory
contains a number of Mac OS X applications you might want to try.
.SH DEMONSTRATION PROGRAMS
The demos in \fB/Applications/GrabBag\fR
are designed to give aspiring programmers
a taste of what's possible with Mac OS X.
If you're interested in science,
music, art, signal processing,
games, animation, timing, optics, PostScript, chaos, electronics, chess,
and so on,
you should find something compelling in this collection of demos.    
.PP
Note that these demo programs
are not generally maintained,
and usually do not come with sources,
although the source code for some demos
is available in the directory \fB/Developer/Examples\fR.
