LIBRARY PEX5
VERSION LIBRARY_VERSION
EXPORTS
 PEXAccumulateState
 PEXAddToNameSet
 PEXAnnotationText
 PEXAnnotationText2D
 PEXApplicationData
 PEXBeginPickAll
 PEXBeginPickOne
 PEXBeginRendering
 PEXBeginStructure
 PEXBuildTransform
 PEXBuildTransform2D
 PEXCellArray
 PEXCellArray2D
 PEXChangeNameSet
 PEXChangePickDevice
 PEXChangePipelineContext
 PEXChangeRenderer
 PEXChangeSearchContext
 PEXChangeStructureRefs
 PEXCopyBytesToOC
 PEXCopyElements
 PEXCopyLookupTable
 PEXCopyNameSet
 PEXCopyPipelineContext
 PEXCopySearchContext
 PEXCopyStructure
 PEXCountOCs
 PEXCreateLookupTable
 PEXCreateNameSet
 PEXCreatePickMeasure
 PEXCreatePipelineContext
 PEXCreateRenderer
 PEXCreateSearchContext
 PEXCreateStructure
 PEXCreateWorkstation
 PEXDecodeOCs
 PEXDeleteBetweenLabels
 PEXDeleteElements
 PEXDeleteTableEntries
 PEXDeleteToLabel
 PEXDestroyStructures
 PEXElementSearch
 PEXEncodeOCs
 PEXEncodedAnnoText
 PEXEncodedAnnoText2D
 PEXEncodedText
 PEXEncodedText2D
 PEXEndPickAll
 PEXEndPickOne
 PEXEndRendering
 PEXEndStructure
 PEXEscape
 PEXEscapeWithReply
 PEXExecuteDeferredActions
 PEXExecuteStructure
 PEXExtendedCellArray
 PEXFetchElements
 PEXFetchElementsAndSend
 PEXFillArea
 PEXFillArea2D
 PEXFillAreaSet
 PEXFillAreaSet2D
 PEXFillAreaSetWithData
 PEXFillAreaWithData
 PEXFinishOCs
 PEXFreeEnumInfo
 PEXFreeFontInfo
 PEXFreeFontNames
 PEXFreeLookupTable
 PEXFreeNameSet
 PEXFreeOCData
 PEXFreePCAttributes
 PEXFreePDAttributes
 PEXFreePMAttributes
 PEXFreePickMeasure
 PEXFreePickPaths
 PEXFreePipelineContext
 PEXFreeRenderer
 PEXFreeRendererAttributes
 PEXFreeSCAttributes
 PEXFreeSearchContext
 PEXFreeStructurePaths
 PEXFreeTableEntries
 PEXFreeWorkstation
 PEXFreeWorkstationAttributes
 PEXGDP
 PEXGDP2D
 PEXGSE
 PEXGeoNormFillArea
 PEXGeoNormFillAreaSet
 PEXGeoNormQuadrilateralMesh
 PEXGeoNormSetOfFillAreaSets
 PEXGeoNormTriangleStrip
 PEXGetAncestors
 PEXGetDefinedIndices
 PEXGetDescendants
 PEXGetElementInfo
 PEXGetEnumTypeInfo
 PEXGetExtensionInfo
 PEXGetImpDepConstants
 PEXGetNameSet
 PEXGetOCAddr
 PEXGetPickDevice
 PEXGetPickMeasure
 PEXGetPipelineContext
 PEXGetPredefinedEntries
 PEXGetProtocolFloatFormat
 PEXGetRendererAttributes
 PEXGetRendererDynamics
 PEXGetSearchContext
 PEXGetSizeOCs
 PEXGetStructureInfo
 PEXGetStructuresInNetwork
 PEXGetTableEntries
 PEXGetTableEntry
 PEXGetTableInfo
 PEXGetWorkstationAttributes
 PEXGetWorkstationDynamics
 PEXGetWorkstationPostings
 PEXGetWorkstationViewRep
 PEXIdentityMatrix
 PEXIdentityMatrix2D
 PEXInitialize
 PEXInvertMatrix
 PEXInvertMatrix2D
 PEXLabel
 PEXListFonts
 PEXListFontsWithInfo
 PEXLoadFont
 PEXLookAtViewMatrix
 PEXMapDCToWC
 PEXMapWCToDC
 PEXMapXCToNPC
 PEXMapXCToNPC2D
 PEXMarkers
 PEXMarkers2D
 PEXMatchRenderingTargets
 PEXMatrixMult
 PEXMatrixMult2D
 PEXNPCToXCTransform
 PEXNPCToXCTransform2D
 PEXNURBCurve
 PEXNURBSurface
 PEXNoop
 PEXNormalizeVectors
 PEXNormalizeVectors2D
 PEXOrthoProjMatrix
 PEXPerspProjMatrix
 PEXPickAll
 PEXPickOne
 PEXPolarViewMatrix
 PEXPolyline
 PEXPolyline2D
 PEXPolylineSetWithData
 PEXPostStructure
 PEXQuadrilateralMesh
 PEXQueryEncodedTextExtents
 PEXQueryFont
 PEXQueryTextExtents
 PEXRedrawAllStructures
 PEXRedrawClipRegion
 PEXRemoveFromNameSet
 PEXRenderElements
 PEXRenderNetwork
 PEXRestoreModelClipVolume
 PEXRotate
 PEXRotate2D
 PEXRotateGeneral
 PEXScale
 PEXScale2D
 PEXSearchNetwork
 PEXSendOCs
 PEXSetATextAlignment
 PEXSetATextHeight
 PEXSetATextPath
 PEXSetATextStyle
 PEXSetATextUpVector
 PEXSetBFInteriorStyle
 PEXSetBFInteriorStyleIndex
 PEXSetBFReflectionAttributes
 PEXSetBFReflectionModel
 PEXSetBFSurfaceColor
 PEXSetBFSurfaceColorIndex
 PEXSetBFSurfaceInterpMethod
 PEXSetCharExpansion
 PEXSetCharHeight
 PEXSetCharSpacing
 PEXSetCharUpVector
 PEXSetColorApproxIndex
 PEXSetCurveApprox
 PEXSetDepthCueIndex
 PEXSetEchoColor
 PEXSetEdgeBundleIndex
 PEXSetEditingMode
 PEXSetElementPtr
 PEXSetElementPtrAtLabel
 PEXSetFacetCullingMode
 PEXSetFacetDistinguishFlag
 PEXSetGlobalTransform
 PEXSetGlobalTransform2D
 PEXSetHLHSRID
 PEXSetIndividualASF
 PEXSetInteriorBundleIndex
 PEXSetInteriorStyle
 PEXSetInteriorStyleIndex
 PEXSetLightSourceState
 PEXSetLineBundleIndex
 PEXSetLineColor
 PEXSetLineColorIndex
 PEXSetLineType
 PEXSetLineWidth
 PEXSetLocalTransform
 PEXSetLocalTransform2D
 PEXSetMarkerBundleIndex
 PEXSetMarkerColor
 PEXSetMarkerColorIndex
 PEXSetMarkerScale
 PEXSetMarkerType
 PEXSetModelClipFlag
 PEXSetModelClipVolume
 PEXSetModelClipVolume2D
 PEXSetOfFillAreaSets
 PEXSetParaSurfCharacteristics
 PEXSetPatternAttributes
 PEXSetPatternAttributes2D
 PEXSetPatternSize
 PEXSetPickID
 PEXSetPolylineInterpMethod
 PEXSetReflectionAttributes
 PEXSetReflectionModel
 PEXSetRenderingColorModel
 PEXSetSurfaceApprox
 PEXSetSurfaceColor
 PEXSetSurfaceColorIndex
 PEXSetSurfaceEdgeColor
 PEXSetSurfaceEdgeColorIndex
 PEXSetSurfaceEdgeFlag
 PEXSetSurfaceEdgeType
 PEXSetSurfaceEdgeWidth
 PEXSetSurfaceInterpMethod
 PEXSetTableEntries
 PEXSetTextAlignment
 PEXSetTextBundleIndex
 PEXSetTextColor
 PEXSetTextColorIndex
 PEXSetTextFontIndex
 PEXSetTextPath
 PEXSetTextPrecision
 PEXSetViewIndex
 PEXSetWorkstationBufferMode
 PEXSetWorkstationDisplayUpdateMode
 PEXSetWorkstationHLHSRMode
 PEXSetWorkstationViewPriority
 PEXSetWorkstationViewRep
 PEXSetWorkstationViewport
 PEXSetWorkstationWindow
 PEXStartOCs
 PEXText
 PEXText2D
 PEXTransformPoints
 PEXTransformPoints2D
 PEXTransformPoints2DH
 PEXTransformPoints4D
 PEXTransformVectors
 PEXTransformVectors2D
 PEXTranslate
 PEXTranslate2D
 PEXTriangleStrip
 PEXUnloadFont
 PEXUnpostAllStructures
 PEXUnpostStructure
 PEXUpdatePickMeasure
 PEXUpdateWorkstation
 PEXViewMappingMatrix
 PEXViewMappingMatrix2D
 PEXViewOrientationMatrix
 PEXViewOrientationMatrix2D
 PEXXCToNPCTransform
 PEXXCToNPCTransform2D
/* $Xorg: PEX5-def.cpp,v 1.3 2000/08/17 19:44:20 cpqbld Exp $ */
