---
abstract: 'A pure Perl HTTP proxy'
author:
  - "Philippe \"BooK\" Bruhat <book@cpan.org>"
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Proxy
provides:
  HTTP::Proxy:
    file: lib/HTTP/Proxy.pm
    version: 0.300
  HTTP::Proxy::BodyFilter:
    file: lib/HTTP/Proxy/BodyFilter.pm
    version: 0
  HTTP::Proxy::BodyFilter::complete:
    file: lib/HTTP/Proxy/BodyFilter/complete.pm
    version: 0
  HTTP::Proxy::BodyFilter::htmlparser:
    file: lib/HTTP/Proxy/BodyFilter/htmlparser.pm
    version: 0
  HTTP::Proxy::BodyFilter::htmltext:
    file: lib/HTTP/Proxy/BodyFilter/htmltext.pm
    version: 0
  HTTP::Proxy::BodyFilter::lines:
    file: lib/HTTP/Proxy/BodyFilter/lines.pm
    version: 0
  HTTP::Proxy::BodyFilter::save:
    file: lib/HTTP/Proxy/BodyFilter/save.pm
    version: 0
  HTTP::Proxy::BodyFilter::simple:
    file: lib/HTTP/Proxy/BodyFilter/simple.pm
    version: 0
  HTTP::Proxy::BodyFilter::tags:
    file: lib/HTTP/Proxy/BodyFilter/tags.pm
    version: 0
  HTTP::Proxy::Engine:
    file: lib/HTTP/Proxy/Engine.pm
    version: 0
  HTTP::Proxy::Engine::Legacy:
    file: lib/HTTP/Proxy/Engine/Legacy.pm
    version: 0
  HTTP::Proxy::Engine::NoFork:
    file: lib/HTTP/Proxy/Engine/NoFork.pm
    version: 0
  HTTP::Proxy::Engine::ScoreBoard:
    file: lib/HTTP/Proxy/Engine/ScoreBoard.pm
    version: 0
  HTTP::Proxy::Engine::Threaded:
    file: lib/HTTP/Proxy/Engine/Threaded.pm
    version: 0
  HTTP::Proxy::FilterStack:
    file: lib/HTTP/Proxy/FilterStack.pm
    version: 0
  HTTP::Proxy::HeaderFilter:
    file: lib/HTTP/Proxy/HeaderFilter.pm
    version: 0
  HTTP::Proxy::HeaderFilter::simple:
    file: lib/HTTP/Proxy/HeaderFilter/simple.pm
    version: 0
  HTTP::Proxy::HeaderFilter::standard:
    file: lib/HTTP/Proxy/HeaderFilter/standard.pm
    version: 0
requires:
  HTTP::Daemon: 1.25
  LWP::UserAgent: 2
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/book/HTTP-Proxy
version: 0.300
