.\" Man page for apropos
.\"
.\" Copyright (c) 1990, 1991, John W. Eaton.
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the man 1.0
.\" distribution.  
.\"
.\" John W. Eaton
.\" jwe@che.utexas.edu
.\" Department of Chemical Engineering
.\" The University of Texas at Austin
.\" Austin, Texas  78712
.\"
.TH apropos 1 "Jan 15, 1991"
.LO 1
.SH NAAM
apropos \- zoek een gegeven string in de whatis database
.SH SYNTAX
.BI apropos
string ...
.SH BESCHRIJVING
.B apropos
zoekt naar de opgegeven strings in een aantal database bestanden
die korte beschrijvingen van systeem\%commando's bevatten 
en stuurt het resultaat naar standaard uitvoer.
.SH "ZIE OOK"
whatis(1), man(1).
