#
# Unit test for command: locateFile
#

note "[locateFile A.itcl]"


if {[regexp {verbose.itcl$} [locateFile verbose.itcl]]} {
    pass "Found verbose.itcl as >[locateFile verbose.itcl]<"
} else {
    fail "Couldn't find verbose.itcl"
}
if {[regexp {lib/bug.exp$} [locateFile bug.exp lib]]} {
    pass "Found bug.exp as >[locateFile bug.exp lib]<"
} else {
    fail "Couldn't find bug.exp"
}
if {[regexp {testsuite/T/test_004.exp$} \
	[locateFile test_004.exp testsuite/T]]} {
    pass "Found test_004.exp as >[locateFile test_004.exp testsuite/T]<"
} else {
    fail "Couldn't find test_004.exp as\
	    >\[locateFile test_004.exp testsuite/T\]<"
}
if {[regexp {testsuite/T/test_004.exp$} \
	[locateFile test_004.exp testsuite]]} {
    pass "Found test_004.exp as >[locateFile test_004.exp testsuite]<"
} else {
    fail "Couldn't find test_004.exp as\
	    >\[locateFile test_004.exp testsuite\]<"
}
if {[regexp {testsuite/T/test_004.exp$} \
	[locateFile test_004.exp T]]} {
    pass "Found test_004.exp as >[locateFile test_004.exp T]<"
} else {
    fail "Couldn't find test_004.exp as\
	    >\[locateFile test_004.exp T\]<"
}
if {[regexp {testsuite/T/test_004.exp$} \
	[locateFile test_004.exp]]} {
    pass "Found test_004.exp as >[locateFile test_004.exp]<"
} else {
    fail "Couldn't find test_004.exp as\
	    >\[locateFile test_004.exp testsuite\]<"
}

