# -*-Tcl-*-
#
# Checking Type definition
#

verbose "auto_path: >[set auto_path]<"

verbose [Type A 100]
verbose [set A]
verbose $A
verbose [A value]

namespace eval TN {
    verbose [Type B 200]
    verbose [set B]
    verbose $B
    verbose [B value]
    verbose [::itcl::find objects]
}

verbose [::itcl::find objects]

namespace eval TN {
    verbose [::itcl::find objects]
}

proc Y {} {
    proc YY {} {
	puts "in YY"
    }
    set Tmp 100
    verbose {[Type C 200]}
    verbose {[set C]}
    verbose {$C}
    verbose {[C value]}
    verbose {[set C 400]}
    verbose {[set C]}
    verbose {Locals: >[info locals]<}
    verbose {Globals: >[info globals]<}
    verbose {Vars: >[info vars]<}
    verbose {Commands: >[lsort [split [info commands]]]<}
    verbose {[::itcl::find objects]}
    verbose {A: >[A value]<} 
}

verbose "################################ Doing Y"
Y
YY
rename Y ""
YY

verbose {[::itcl::find objects]}

verbose [Type Z text]
delete object Z
