Project = decomment
ProductType = tool
Install_Dir = /usr/local/bin

CFILES = decomment.c

Extra_CC_Flags = -Wall -mdynamic-no-pic
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
