.Dd January 30, 2009
.Dt JABBER_CONFIG_MIGRATOR.PL 1
.Os "Mac OS X Server"
.Sh NAME
.Nm jabber_config_migrator.pl
.Nd Migrate jabberd config data from 1.4 or 2.0 to 2.1
.Sh SYNOPSIS
.Nm jabber_config_migrator.pl
.Ar [ help | ... ]
.Sh DESCRIPTION
.Nm
Migrates jabberd config data from 1.4 or 2.0 to 2.1. Run with '-?' or '-h' for usage information.
.Nm
is provided to support other Mac OS X Server administration tools and is not intended for general command line use.
