/* $XFree86: xc/lib/XTrap/XTrap-def.cpp,v 1.1 2001/11/15 12:56:17 alanh Exp $ */
LIBRARY XTrap
VERSION LIBRARY_VERSION
EXPORTS
 XEAddEventCB
 XEAddEventCBs
 XEAddRequestCB
 XEAddRequestCBs
 XERemoveAllEventCBs
 XERemoveAllRequestCBs
 XERemoveEventCB
 XERemoveEventCBs
 XERemoveRequestCB
 XERemoveRequestCBs
 XEChangeTC
 XECreateTC
 XEFreeTC
 XESetCmdGateState
 XETrapSetColorReplies
 XETrapSetCommandKey
 XETrapSetCursor
 XETrapSetEvents
 XETrapSetGrabServer
 XETrapSetMaxPacket
 XETrapSetRequests
 XETrapSetStatistics
 XETrapSetTimestamps
 XETrapSetWinXY
 XETrapSetXInput
 XETrapDispatchXLib
 XEPrintAvail
 XEPrintAvailFlags
 XEPrintAvailPktSz
 XEPrintCfgFlags
 XEPrintCmdKey
 XEPrintCurPktSz
 XEPrintCurXY
 XEPrintCurrent
 XEPrintEvents
 XEPrintEvtStats
 XEPrintLastTime
 XEPrintMajOpcode
 XEPrintPlatform
 XEPrintRelease
 XEPrintReqStats
 XEPrintRequests
 XEPrintStateFlags
 XEPrintStatistics
 XEPrintTkFlags
 XEPrintTkRelease
 XEPrintTkState
 XEFlushConfig
 XEGetAvailableRequest
 XEGetCurrentRequest
 XEGetLastInpTimeRequest
 XEGetStatisticsRequest
 XEGetVersionRequest
 XEResetRequest
 XESimulateXEventRequest
 XEStartTrapRequest
 XEStopTrapRequest
 XEEventIDToString
 XEEventStringToID
 XEPlatformIDToString
 XEPlatformStringToID
 XERequestIDToExtString
 XERequestIDToString
 XERequestStringToID
 XETrapQueryExtension
 XETrapAppMainLoop
 XETrapAppPending
 XETrapAppWhileLoop
 XETrapDispatchEvent
 XETrapGetEventHandler
 XETrapSetEventHandler
 XETrapWaitForSomething
