# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Std
version:      v0.0.8
version_from: lib/Class/Std.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Scalar::Util:                  0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
