---
abstract: 'a sophisticated exporter for custom-built routines'
author:
  - 'Ricardo SIGNES, C<< <rjbs@cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Sub::Exporter
name: Sub-Exporter
no_index:
  directory:
    - inc
    - t
requires:
  Data::OptList: 0.1
  Params::Util: 0.14
  Sub::Install: 0.92
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/sub-exporter
version: 0.982
