.Dd July 25, 2003
.Dt GLIBTOOL 1
.Os GNU
.Sh NAME
.Nm glibtool ,
.Nm glibtoolize
.Nd generic shared library support
.Sh SYNOPSIS
.Nm glibtool
.Op arguments
.Nm glibtoolize
.Op arguments
.Sh DESCRIPTION
.Nm glibtool
and
.Nm glibtoolize
are scripts that provide generic shared library support to package
developers.
It is actually the GNU
.Nm libtool
and
.Nm libtoolize
scripts, renamed to avoid conflict with the Apple-provided
.Xr libtool 1 .
.Pp
As of version 1.5.22, better Mac OS X support is provided.
The
.Fl arch ,
.Fl framework
and
.Fl isysroot
options are now passed to the compiler/linker as would be expected.
Bundles can be built using the
.Fl "-undefined dynamic_lookup"
link option, if
the MACOSX_DEPLOYMENT_TARGET environment variable is set to
.Li 10.3
or greater.
.Pp
The rest of this manual page describes the additional features added to
.Nm glibtool
for Mac OS X.
More general documentation is listed below.
.Sh SEE ALSO
.Xr ar 1 ,
.Xr libtool 1 ,
.Xr ranlib 1
.Pp
.Pa "/Developer/ADC Reference Library/documentation/DeveloperTools/glibtool"
