--- #YAML:1.0
name:                Log-Log4perl
version:             1.15
abstract:            Log4j implementation for Perl
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    File::Spec:                    0.82
    Test::More:                    0.45
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <m@perlmeister.com>
