# And we use the jmr3904 linker script.
set_board_info ldscript "-Tjmr3904app.ld"

# Pass --board=jmr3904 to the standalone simulator
set_board_info sim,options "--board=jmr3904"
set_board_info gdb,target_sim_options "--board=jmr3904"

# Pass -G 0 when testing libjava
set_board_info libjava,options "-G 0"

set_board_info gcc,stack_size "8192"

# Otherwise we're the same as the standard MIPS simulator.
load_base_board_description "mips-sim";
