.\""Copyright (c) 2001 Apple Computer, Inc. All Rights Reserved.
.\"The contents of this file constitute Original Code as defined in and are 
.\"subject to the Apple Public Source License Version 1.2 (the 'License'). 
.\"You may not use this file except in compliance with the
.\"License. Please obtain a copy of the License at 
.\"http://www.apple.com/publicsource and read it before using this file.
.\"
.\"This Original Code and all software distributed under the License are 
.\"distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER 
.\"EXPRESS OR IMPLIED, AND APPLE
.\"HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY 
.\"WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
.\"QUIET ENJOYMENT OR NON-INFRINGEMENT. Please see the License for the 
.\"specific language governing rights and limitations under the License."
.Dd March 24, 2001
.Dt AUTODISKMOUNT 8
.Os Darwin
.Sh NAME
.Nm autodiskmount
.Nd fscks and mounts filesystems
.Sh SYNOPSIS
.Nm
.Op Fl adv
.Sh DESCRIPTION
.Nm 
fscks and mounts all recognized filesystems.
These currently include the cd9660, cddafs, hfs, msdos, udf, and ufs filesystems.
.Pp
.Nm
also notifies subscriber services (Carbon, Cocoa applications) of the appearance of filesystems and arbitrates unrecognized filesystems and device subscriptions.
.Pp
Options:
.Bl -tag -width -indent
.It Fl a
Mount removable media also.
.It Fl d
Prints debugging information. Does not run autodiskmount as a daemon.
.It Fl v
Lists already mounted media, after performing mounts.
.El
.Pp
The file
.Pa /etc/fstab
is consulted for user-defined mount points, indexed by filesystem,
in the mount point determination for a filesystem.
Each filesystem can be identified by its UUID or by its label,
using the constructs ``UUID'' or ``LABEL'', respectively.
The UUID
.Pa DCA19C980FD6A858
would be specified as
``UUID=DCA19C980FD6A858''.
The label
.Pa Volume Name
would be specified as ``LABEL=Volume\\040Name''.
.Pp
.Sh FILES
.Bl -tag -width /etc/fstab -compact
.It Pa /etc/fstab
filesystem table
.El
.Sh SEE ALSO 
.Xr cd9660.util 8 ,
.Xr fstab 5 ,
.Xr hfs.util 8 ,
.Xr msdos.util 8 ,
.Xr udf.util 8 ,
.Xr ufs.util 8
.Sh HISTORY
.Nm NeXTStep/Openstep
