Project = ping
Install_Dir = /sbin

CFILES = ping.c
MANPAGES = ping.8

Extra_CC_Flags = -mdynamic-no-pic -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make

Install_Program_Mode = 04555
