=head1 NAME

My::Module

=head1 SYNOPSIS

    use My::Module;

=head1 DESCRIPTION

This is the description for My::Module.

    This is verbatim

=head2 First Subsection

This is the first subsection.  foo->bar();

=head2 Second Subsection

This is the second subsection.  bar->baz();

=head1 THE END

This is the end.  Beautiful friend, the end.
