
verbose "Test test_001.exp: level [info level]"
verbose "Global tools: [uplevel #0 set szCurrentTestDirectory]"

appendQueue test_003.exp=1
prependQueue test_003.exp=2 test_003.exp=3
verbose "Context: [info context]"
runtest test_003.exp=R0
appendQueue test_003.exp=A0
prependQueue test_003.exp=A2 test_003.exp=A3

namespace Common {
    incr iCount
    verbose "Counter is $iCount"
    if {$iCount < 5} {
	prependQueue test_001.exp
    }
    pass "test_001.exp: iCount - $iCount"
}
