s,@DATADIR@,/usr/share,g
s,@TERMINFO@,/usr/share/terminfo,g
s,@NCURSES_MAJOR@,5,g
s,@NCURSES_MINOR@,7,g
s,@NCURSES_PATCH@,20081102,g
s,@NCURSES_OSPEED@,short,g
s,@CAPTOINFO@,captoinfo,
s,@CLEAR@,clear,
s,@INFOCMP@,infocmp,
s,@INFOTOCAP@,infotocap,
s,@TIC@,tic,
s,@TOE@,toe,
s,@TPUT@,tput,
