debian/install/etc/cups                             etc
debian/install/usr/bin/cups-calibrate               usr/bin
debian/install/usr/lib/cups                         usr/lib
debian/install/usr/share/cups/calibrate.ppm         usr/share/cups
debian/install/usr/share/cups/model/C/*             usr/share/cups/model/gimp-print
debian/install/usr/share/man/man8/cups-calibrate.8  usr/share/man/man8
samples/profile.jpg                                 usr/share/doc/cupsys-driver-gimpprint/samples
