#!/bin/sh

cd /var/jabberd/modules/proxy65 && /System/Library/Frameworks/Python.framework/Versions/Current/Extras/bin/mktap --uid=$7 --gid=$8 proxy65 --jid=proxy65.$1 --secret=$2 --rhost=$3 --rport=$4 --proxyips=$5:$6
cd /var/jabberd/modules/proxy65 && chmod 0640 proxy65.tap
cd /var/jabberd/modules/proxy65 && chown $7:$8 proxy65.tap

#echo --jid=proxy65.$1
#echo --secret=$2
#echo --rhost=$3
#echo --rport=$4
#echo --proxyips-ip:port=$5:$6
#echo --uid=$7
#echo --gid=$8
