# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/UWJ7kcRuTI/africa.  Olson data version 1
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Africa::Lagos;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Africa::Lagos::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY,
60547218384,
DateTime::TimeZone::NEG_INFINITY,
60547219200,
816,
0,
'LMT'
    ],
    [
60547218384,
DateTime::TimeZone::INFINITY,
60547214784,
DateTime::TimeZone::INFINITY,
3600,
0,
'WAT'
    ],
];

sub has_dst_changes { 0 }

sub _max_year { 2016 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

