#
# This test script prints the namespace variables
# pass the the test script when available varibale matches the expected
# and visa versa
#

proc checkVars {} {
    set lExpectedVars [list \
	    bTestCase \
	    iArgs lArgs \
	    szID szName \
	    szScriptName szTool \
	    szTestCase szTestCaseID szTestCaseArgs \
	    ]
    set lVars [uplevel info vars]
    note "Available Variable:"
    foreach v [lsort $lVars] {
	if {[lsearch [info globals] $v] < 0} {
	    note "[format %15s $v] = >[uplevel set $v]<"
	    if {[lsearch $lExpectedVars $v] >= 0} {
		pass "Available variable >$v< in list of expected"
	    } else {
		fail "Available variable >$v< NOT in list of expected"
	    }
	}
    }
    foreach v $lExpectedVars {
	    if {[lsearch $lVars $v] >= 0} {
		pass "Expected variable >$v< in list of available"
	    } else {
		fail "Expected variable >$v< NOT in list of available"
	    }
    }
}

checkVars
