--- #YAML:1.0
name:                DBI
version:             1.604
abstract:            Database independent interface for Perl
license:             ~
author:              
    - Tim Bunce (dbi-users@perl.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Spec:                    0
    Scalar::Util:                  0
    Storable:                      1
    Test::Simple:                  0.4
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
