.\" Copyright (c) 2001 Apple Computer, Inc. All Rights Reserved.
.Dd March 24, 2001
.Dt POLICYTOOL 1
.Os Mac OS X 
.Sh NAME
.Nm Policytool
.Nd graphical tool for managing Java policy files 
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This command creates and modifies the external policy configuration files that define your installation's Java security policy. It is documented in 
.Xr http://java.sun.com/j2se/1.3/docs/tooldocs/solaris/policytool.html . 
Please refer to those documentation files for more information.
.Sh SEE ALSO 
.Xr http://java.sun.com/j2se/1.3/docs/tooldocs/solaris/policytool.html . 
