# $FreeBSD: head/bin/sh/tests/Makefile 322438 2017-08-12 19:17:48Z jilles $

.include <bsd.own.mk>

TESTS_SUBDIRS+=	builtins
TESTS_SUBDIRS+=	errors
TESTS_SUBDIRS+=	execution
TESTS_SUBDIRS+=	expansion
TESTS_SUBDIRS+=	invocation
TESTS_SUBDIRS+=	parameters
TESTS_SUBDIRS+=	parser
TESTS_SUBDIRS+=	set-e

.include <bsd.test.mk>
