#
# pppdump Makefile for SVR4 systems
# $Id: Makefile.svr4,v 1.3 2001/01/20 03:35:54 callie Exp $
#

include ../svr4/Makedefs

CFLAGS= $(COPTS) -I../include/net
OBJS = pppdump.o bsd-comp.o deflate.o zlib.o

all:	pppdump

pppdump: $(OBJS)
	$(CC) -o pppdump $(OBJS)

clean:
	rm -f pppdump *~

install:
	$(INSTALL) -f $(BINDIR) pppdump
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppdump.8
