// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from stdin

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#ifdef __cplusplus
#define AWDKEYCHAINCKKSRATELIMITERTOPWRITERS_FUNCTION extern "C"
#else
#define AWDKEYCHAINCKKSRATELIMITERTOPWRITERS_FUNCTION extern
#endif

@interface AWDKeychainCKKSRateLimiterTopWriters : PBCodable <NSCopying>
{
    uint64_t _timestamp;
    NSString *_ratelimitertype;
    NSMutableArray<NSString *> *_writers;
    struct {
        int timestamp:1;
    } _has;
}


@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) uint64_t timestamp;

@property (nonatomic, retain) NSMutableArray<NSString *> *writers;
- (void)clearWriters;
- (void)addWriter:(NSString *)i;
- (NSUInteger)writersCount;
- (NSString *)writerAtIndex:(NSUInteger)idx;
+ (Class)writerType;

@property (nonatomic, readonly) BOOL hasRatelimitertype;
@property (nonatomic, retain) NSString *ratelimitertype;

// Performs a shallow copy into other
- (void)copyTo:(AWDKeychainCKKSRateLimiterTopWriters *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(AWDKeychainCKKSRateLimiterTopWriters *)other;

AWDKEYCHAINCKKSRATELIMITERTOPWRITERS_FUNCTION BOOL AWDKeychainCKKSRateLimiterTopWritersReadFrom(__unsafe_unretained AWDKeychainCKKSRateLimiterTopWriters *self, __unsafe_unretained PBDataReader *reader);

@end

