#define BOOTCAMP_FORMATTER_ENABLE_WIPEFS	1
#define HAVE_CTYPE_H				1
#define HAVE_ERRNO_H				1
#define HAVE_FCNTL_H				1
#define HAVE_GETOPT_H				1
#define HAVE_GETTIMEOFDAY			1
#define HAVE_LIBGEN_H				1
#define HAVE_LIMITS_H				1
#define HAVE_LOCALE_H				1
#define HAVE_MACHINE_ENDIAN_H		1
#define HAVE_MBSINIT				1
#define HAVE_SETXATTR				1
#define HAVE_STDARG_H				1
#define HAVE_STDDEF_H				1
#define HAVE_STDINT_H				1
#define HAVE_STDIO_H				1
#define HAVE_STDLIB_H				1
#define HAVE_STRING_H				1
#define HAVE_SYSLOG_H				1
#define HAVE_SYS_DISK_H				1
#define HAVE_SYS_IOCTL_H			1
#define HAVE_SYS_MOUNT_H			1
#define HAVE_SYS_PARAM_H			1
#define HAVE_SYS_STAT_H				1
#define HAVE_SYS_TYPES_H			1
#define HAVE_TIME_H					1
#define HAVE_UNISTD_H				1
#define HAVE_WCHAR_H				1

#include "param.h"
