---
abstract: 'Less indentation and newlines plus sub deparsing'
author:
  - 'mst - Matt S. Trout <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Dumper::Concise
name: Data-Dumper-Concise
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.200
