#	@(#)Makefile	8.1 (Berkeley) 6/4/93

PROG=	fingerd
MAN8=	fingerd.8
BINDIR= /usr/libexec

beforeinstall:
	-mkdir -p ${DESTDIR}/${BINDIR}

afterinstall:
	-mkdir -p ${DESTDIR}/System/Library/LaunchDaemons
	install -c -m 0644 ${.CURDIR}/finger.plist ${DESTDIR}/System/Library/LaunchDaemons

.include <bsd.prog.mk>
