.\" Copyright (c) 2012, Apple Inc.  All rights reserved.
.\"
.Dd June 28, 2012
.Dt LTOP 1
.Os "Mac OS X"
.Sh NAME
.Nm ltop
.Nd Display ledger information for processes on the system
.Sh SYNOPSIS
.Nm ltop
.Fl h
.Pp
.Nm ltop
.Fl p Ar pid
.Sh DESCRIPTION
The
.Nm ltop
command allows the user to print the resource ledger information maintained by kernel for each process. The ledger information provides insights into cpu time, memory usage of a process and also know the limits set on them.
.Sh SEE ALSO
.Xr top 1 
