---
name: PathTools
version: 3.24
author:
  - 'Maintained by Ken Williams <KWILLIAMS@cpan.org>'
abstract: Tools for working with paths and file specs across platforms
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  File::Basename: 0
  perl: 5.005
build_requires:
  ExtUtils::CBuilder: 0
  File::Path: 0
  Module::Build: 0.19
  Scalar::Util: 0
  Test: 0
dynamic_config: 1
provides:
  Cwd:
    file: Cwd.pm
    version: 3.24
  File::Spec:
    file: lib/File/Spec.pm
    version: 3.24
  File::Spec::Cygwin:
    file: lib/File/Spec/Cygwin.pm
    version: 1.1
  File::Spec::Epoc:
    file: lib/File/Spec/Epoc.pm
    version: 1.1
  File::Spec::Functions:
    file: lib/File/Spec/Functions.pm
    version: 1.3
  File::Spec::Mac:
    file: lib/File/Spec/Mac.pm
    version: 1.4
  File::Spec::OS2:
    file: lib/File/Spec/OS2.pm
    version: 1.2
  File::Spec::Unix:
    file: lib/File/Spec/Unix.pm
    version: 1.5
  File::Spec::VMS:
    file: lib/File/Spec/VMS.pm
    version: 1.4
  File::Spec::Win32:
    file: lib/File/Spec/Win32.pm
    version: 1.6
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
