# $FreeBSD: src/usr.bin/makewhatis/Makefile,v 1.3 2002/11/18 10:11:22 ru Exp $

PROG=		makewhatis
DPADD=		${LIBZ}
LDADD=		-lz
SCRIPTS=	makewhatis.local.sh
MAN=		makewhatis.8 makewhatis.local.8
SCRIPTSDIR=	/usr/libexec
BINDIR=		/usr/libexec

.include <bsd.prog.mk>
