.\" checkgid.1
.\"
.\" Copyright (c) 2004 Apple Computer, Inc.
.\"
.Dd September 10, 2004
.Dt CHECKGID 1
.Os
.Sh NAME
.Nm checkgid
.Nd "validate group identifiers"
.Sh SYNOPSIS
.Nm
.Ar gid
.Sh DESCRIPTION
Given one or more group identifers on the command line (e.g., "httpd" or "#-1"), figure out whether they'll be valid for the server to use at run-time.
.Pp
If a groupname isn't found, or we can't setgid() to it, return -1.  If all groups are valid, return 0.
.Pp
This may need to be run as the superuser for the setgid() to succeed; running it as any other user may result in a false negative.
.Sh SEE ALSO
.Xr httpd 1
