.\" Man stranica za apropos
.\"
.\" Copyright (c) 1990, 1991, John W. Eaton.
.\"
.\"   You may distribute under the terms of the GNU General Public
.\"   License as specified in the README file that comes with the man 1.0
.\"   distribution.  
.\"
.\" Mo¾ete distribuirati pod uvjetima GNU Opæe javne licence kako je
.\" odreðeno u datoteci README koja dolazi s distribucijom mana 1.0.
.\"
.\" John W. Eaton
.\" jwe@che.utexas.edu
.\" Department of Chemical Engineering
.\" The University of Texas at Austin
.\" Austin, Texas  78712
.\"
.\" 9. studenog 1998. preveo Matej Vela <mvela@public.srce.hr>, META.
.TH apropos 1 "15. sijeènja 1991."
.SH IME
apropos \- tra¾i niz u whatis bazi podataka
.SH SA®ETAK
.BI apropos kljuèna_rijeè
...
.SH OPIS
.B apropos
tra¾i kljuène rijeèi u skupu baza podataka koje sadr¾e kratke
opise naredbi sustava i prikazuje rezultate na standardnom izlazu.
.SH "TAKOÐER POGLEDAJTE"
.BR whatis (1),
.BR man (1).
