---
abstract: 'Execute code after a scope finished compilation'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Hooks-EndOfScope
no_index:
  directory:
    - inc
    - t
requires:
  Sub::Exporter: 0
  Variable::Magic: 0.34
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
