.\"
.\" Copyright (c) 1997 Doug Rabson
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: kmodstat.8,v 1.2 2002/04/18 18:48:42 lindak Exp $
.\"
.Dd April 17, 2002
.Dt KMODSTAT 8
.Os FreeBSD
.Sh NAME
.Nm kmodstat
.Nd display status of dynamically-loaded kernel modules
.Sh SYNOPSIS
.Nm kmodstat
.Op Fl i Ar id
.Op Fl n Ar name
.Sh DESCRIPTION
.Nm kmodstat
is deprecated; use
.Xr kextstat 8 ,
instead.
.Pp
The
.Nm kmodstat
utility displays the status of any kernel modules
that are dynamically linked into the kernel.
.Pp
The following options are available:
.Bl -tag -width indentXX
.\" ==========
.It Fl i Ar id
Display the status of only the kernel module with this ID.
.\" ==========
.It Fl n Ar name
Display the status of only the kernel module with this name.
.El
.Sh DIAGNOSTICS
The
.Nm kmodstat
utility exits with a status of 0 on success
and with a nonzero status if an error occurs.
.Sh SEE ALSO
.Xr kmodload 8 ,
.Xr kmodsyms 8 ,
.Xr kmodunload 8
.Sh HISTORY
The
.Nm kmodstat
command is based on the command kldstat, written by
.An Doug Rabson Aq dfr@FreeBSD.org
