File Index
xdmxconfig.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xaw/Form.h>
#include <X11/Xaw/Box.h>
#include <X11/Xaw/Command.h>
#include <X11/Xaw/SimpleMenu.h>
#include <X11/Xaw/SmeBSB.h>
#include <X11/Xaw/MenuButton.h>
#include <X11/Xaw/Viewport.h>
#include <X11/Xaw/Dialog.h>
#include <X11/keysym.h>
#include <X11/Xmu/SysUtil.h>
#include "Canvas.h"
#include "dmxparse.h"
#include "dmxprint.h"
#include "dmxlog.h"
Defines
#define DMX_INFO "xdmxconfig v0.9\nCopyright 2002 Red Hat Inc.\n"
#define DMX_MAIN_WIDTH 800
#define DMX_MAIN_HEIGHT 600
#define DMX_DATA_WIDTH 200
#define DMX_DATA_HEIGHT 200
#define DMX_CANVAS_WIDTH 400
#define DMX_CANVAS_HEIGHT 500
Enumerations
enum { dmxConfigStateOpen, dmxConfigStateSave }
Functions
int yyparse (void)
static void dmxConfigCanvasGCs (void)
static void dmxConfigGetDims (int *maxWidth, int *maxHeight)
static int scalex (int x)
static int scaley (int y)
static int unscalex (int x)
static int unscaley (int y)
static void dmxConfigDataUpdate (void)
static void dmxConfigCanvasUpdate (void)
static void dmxConfigCanvasDraw (Region region)
static void dmxConfigSelectCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigCopystrings (void)
static void dmxConfigGetValueString (char **d, Widget w)
static void dmxConfigSetupCnamemenu (void)
static void dmxConfigReadFile (void)
static void dmxConfigWriteFile (void)
static DMXConfigDisplayPtr dmxConfigFindDisplay (int x, int y)
static void dmxConfigSetPopupPosition (Widget popup)
static void dmxConfigPlaceMenu (Widget w, XEvent *event, String *params, Cardinal *num_params)
static void dmxConfigMove (int deltaX, int deltaY)
static void dmxConfigCanvasInput (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigCanvasResize (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigCanvasExpose (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigOpenCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigSaveCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigOkCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigCanCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigECCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigNCCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigDCCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigECOkCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigECCanCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigEDCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigNDCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigDDCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigAboutCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigAboutOkCallback (Widget w, XtPointer closure, XtPointer CallData)
static void dmxConfigQuitCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigQuitOkCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigQuitCanCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigEDOkCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigEDCanCallback (Widget w, XtPointer closure, XtPointer callData)
static void dmxConfigOkAction (Widget w, XEvent *event, String *params, Cardinal *num_params)
int main (int argc, char **argv)
Variables
FILE * yyin
DMXConfigEntryPtr dmxConfigEntry
static DMXConfigVirtualPtr dmxConfigCurrent
static DMXConfigVirtualPtr dmxConfigNewVirtual
static DMXConfigDisplayPtr dmxConfigCurrentDisplay
static DMXConfigDisplayPtr dmxConfigNewDisplay
static int dmxConfigGrabbed
static int dmxConfigGrabbedFine
static int dmxConfigGrabbedX
static int dmxConfigGrabbedY
static char * dmxConfigFilename
static GC dmxConfigGC
static GC dmxConfigGCRev
static GC dmxConfigGCHL
static int dmxConfigGCInit = 0
static Dimension dmxConfigWidgetWidth
static Dimension dmxConfigWidgetHeight
static Dimension dmxConfigWallWidth
static Dimension dmxConfigWallHeight
static double dmxConfigScaleX
static double dmxConfigScaleY
static int dmxConfigNotSaved
static enum { ... } dmxConfigState
static Widget canvas
static Widget cnamebox
static Widget cdimbox
static Widget openpopup
static Widget opendialog
static Widget namebox
static Widget dimbox
static Widget rtbox
static Widget origbox
static Widget okbutton
static Widget buttonpopup
static Widget ecbutton
static Widget dcbutton
static Widget ndbutton0
static Widget ndbutton1
static Widget edbutton
static Widget ddbutton
static Widget ecpopup
static Widget ecdialog0
static Widget ecdialog1
static Widget edpopup
static Widget eddialog0
static Widget eddialog1
static Widget eddialog2
static Widget aboutpopup
static Widget quitpopup
Define Documentation
#define DMX_CANVAS_HEIGHT 500
Referenced by main().
#define DMX_CANVAS_WIDTH 400
Referenced by main().
#define DMX_DATA_HEIGHT 200
Referenced by main().
#define DMX_DATA_WIDTH 200
Referenced by main().
#define DMX_INFO "xdmxconfig v0.9\nCopyright 2002 Red Hat Inc.\n"
Referenced by main().
#define DMX_MAIN_HEIGHT 600
Referenced by main().
#define DMX_MAIN_WIDTH 800
Referenced by main().
Enumeration Type Documentation
anonymous enum
Enumerator:
dmxConfigStateOpen
dmxConfigStateSave
Function Documentation
static void dmxConfigAboutCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References aboutpopup, and dmxConfigSetPopupPosition().
Referenced by main().
static void dmxConfigAboutOkCallback (Widget w, XtPointer closure, XtPointer CallData) [static]
References aboutpopup.
Referenced by main().
static void dmxConfigCanCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References openpopup.
Referenced by main().
static void dmxConfigCanvasDraw (Region region) [static]
References canvas, dmxConfigCanvasGCs(), dmxConfigCanvasUpdate(), dmxConfigGC, dmxConfigGCHL, dmxConfigGCRev, dmxConfigGetDims(), dmxConfigScaleX, dmxConfigScaleY, dmxConfigWidgetHeight, and dmxConfigWidgetWidth.
Referenced by dmxConfigCanvasExpose(), dmxConfigCanvasResize(), dmxConfigDCCallback(), dmxConfigDDCallback(), dmxConfigECOkCallback(), dmxConfigEDOkCallback(), dmxConfigReadFile(), and dmxConfigSelectCallback().
static void dmxConfigCanvasExpose (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigCanvasDraw().
Referenced by main().
static void dmxConfigCanvasGCs (void) [static]
References canvas, dmxConfigGC, dmxConfigGCHL, dmxConfigGCInit, and dmxConfigGCRev.
Referenced by dmxConfigCanvasDraw().
static void dmxConfigCanvasInput (Widget w, XtPointer closure, XtPointer callData) [static]
References display, dmxConfigCanvasUpdate(), dmxConfigFindDisplay(), dmxConfigGrabbed, dmxConfigGrabbedFine, dmxConfigGrabbedX, dmxConfigGrabbedY, dmxConfigMove(), unscalex(), and unscaley().
Referenced by main().
static void dmxConfigCanvasResize (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigCanvasDraw().
Referenced by main().
static void dmxConfigCanvasUpdate (void) [static]
References canvas, _DMXConfigSub::display, dmxConfigDataUpdate(), dmxConfigDisplay, dmxConfigGC, dmxConfigGCHL, dmxConfigGCRev, dmxConfigWallHeight, dmxConfigWallWidth, dmxConfigWidgetHeight, dmxConfigWidgetWidth, GC, _DMXConfigDisplay::name, _DMXConfigSub::next, _DMXConfigDisplay::rootXOrigin, _DMXConfigDisplay::rootYOrigin, scalex(), scaley(), _DMXConfigDisplay::scrnHeight, _DMXConfigDisplay::scrnWidth, _DMXConfigVirtual::subentry, and _DMXConfigSub::type.
Referenced by dmxConfigCanvasDraw(), dmxConfigCanvasInput(), and dmxConfigMove().
static void dmxConfigCopystrings (void) [static]
References _DMXConfigSub::display, dmxConfigDisplay, dmxConfigVirtual, _DMXConfigDisplay::name, _DMXConfigVirtual::name, _DMXConfigSub::next, _DMXConfigEntry::next, _DMXConfigVirtual::subentry, _DMXConfigSub::type, _DMXConfigEntry::type, and _DMXConfigEntry::virtual.
Referenced by dmxConfigReadFile(), and main().
static void dmxConfigDataUpdate (void) [static]
References cdimbox, cnamebox, dcbutton, ddbutton, dimbox, dmxConfigWallHeight, dmxConfigWallWidth, ecbutton, edbutton, _DMXConfigDisplay::name, _DMXConfigVirtual::name, namebox, ndbutton0, ndbutton1, origbox, _DMXConfigDisplay::rootHeight, _DMXConfigDisplay::rootWidth, _DMXConfigDisplay::rootX, _DMXConfigDisplay::rootXOrigin, _DMXConfigDisplay::rootXSign, _DMXConfigDisplay::rootY, _DMXConfigDisplay::rootYOrigin, _DMXConfigDisplay::rootYSign, rtbox, _DMXConfigDisplay::scrnHeight, _DMXConfigDisplay::scrnWidth, _DMXConfigDisplay::scrnX, _DMXConfigDisplay::scrnXSign, _DMXConfigDisplay::scrnY, and _DMXConfigDisplay::scrnYSign.
Referenced by dmxConfigCanvasUpdate().
static void dmxConfigDCCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigCanvasDraw(), dmxConfigFreeVirtual(), dmxConfigSetupCnamemenu(), dmxConfigVirtual, _DMXConfigEntry::next, _DMXConfigEntry::type, and _DMXConfigEntry::virtual.
Referenced by dmxConfigECCanCallback(), and main().
static void dmxConfigDDCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References _DMXConfigSub::display, dmxConfigCanvasDraw(), dmxConfigDisplay, dmxConfigFreeDisplay(), dmxConfigSetupCnamemenu(), _DMXConfigSub::next, _DMXConfigVirtual::subentry, and _DMXConfigSub::type.
Referenced by dmxConfigEDCanCallback(), and main().
static void dmxConfigECCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigSetPopupPosition(), ecdialog0, ecdialog1, ecpopup, _DMXConfigVirtual::height, _DMXConfigVirtual::name, and _DMXConfigVirtual::width.
Referenced by dmxConfigNCCallback(), and main().
static void dmxConfigECCanCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigDCCallback(), and ecpopup.
Referenced by main().
static void dmxConfigECOkCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigCanvasDraw(), dmxConfigGetValueString(), dmxConfigNotSaved, dmxConfigSetupCnamemenu(), ecdialog0, ecdialog1, ecpopup, _DMXConfigVirtual::height, _DMXConfigVirtual::name, and _DMXConfigVirtual::width.
Referenced by dmxConfigOkAction(), and main().
static void dmxConfigEDCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigSetPopupPosition(), eddialog0, eddialog1, eddialog2, edpopup, _DMXConfigDisplay::name, _DMXConfigDisplay::rootXOrigin, _DMXConfigDisplay::rootYOrigin, _DMXConfigDisplay::scrnHeight, _DMXConfigDisplay::scrnWidth, _DMXConfigDisplay::scrnXSign, _DMXConfigDisplay::scrnY, and _DMXConfigDisplay::scrnYSign.
Referenced by dmxConfigNDCallback(), and main().
static void dmxConfigEDCanCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigDDCallback(), and edpopup.
Referenced by main().
static void dmxConfigEDOkCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigCanvasDraw(), dmxConfigGetValueString(), dmxConfigNotSaved, dmxConfigSetupCnamemenu(), eddialog0, eddialog1, eddialog2, edpopup, _DMXConfigDisplay::name, _DMXConfigDisplay::rootXOrigin, _DMXConfigDisplay::rootYOrigin, _DMXConfigDisplay::scrnHeight, _DMXConfigDisplay::scrnWidth, _DMXConfigDisplay::scrnX, _DMXConfigDisplay::scrnXSign, _DMXConfigDisplay::scrnY, and _DMXConfigDisplay::scrnYSign.
Referenced by dmxConfigOkAction(), and main().
static DMXConfigDisplayPtr dmxConfigFindDisplay (int x, int y) [static]
References _DMXConfigSub::display, dmxConfigDisplay, _DMXConfigSub::next, _DMXConfigDisplay::rootXOrigin, _DMXConfigDisplay::rootYOrigin, scalex(), scaley(), _DMXConfigDisplay::scrnHeight, _DMXConfigDisplay::scrnWidth, _DMXConfigVirtual::subentry, and _DMXConfigSub::type.
Referenced by dmxConfigCanvasInput().
static void dmxConfigGetDims (int * maxWidth, int * maxHeight) [static]
References _DMXConfigSub::display, dmxConfigDisplay, dmxConfigVirtual, dmxConfigWallHeight, dmxConfigWallWidth, _DMXConfigVirtual::height, _DMXConfigEntry::next, _DMXConfigSub::next, _DMXConfigDisplay::rootXOrigin, _DMXConfigDisplay::rootYOrigin, _DMXConfigDisplay::scrnHeight, _DMXConfigDisplay::scrnWidth, _DMXConfigVirtual::subentry, _DMXConfigEntry::type, _DMXConfigSub::type, _DMXConfigEntry::virtual, and _DMXConfigVirtual::width.
Referenced by dmxConfigCanvasDraw().
static void dmxConfigGetValueString (char ** d, Widget w) [static]
Referenced by dmxConfigECOkCallback(), dmxConfigEDOkCallback(), and dmxConfigOkCallback().
static void dmxConfigMove (int deltaX, int deltaY) [static]
References dmxConfigCanvasUpdate(), dmxConfigNotSaved, dmxConfigWallHeight, dmxConfigWallWidth, _DMXConfigDisplay::rootXOrigin, and _DMXConfigDisplay::rootYOrigin.
Referenced by dmxConfigCanvasInput().
static void dmxConfigNCCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigAddEntry(), dmxConfigCreateVirtual(), dmxConfigCurrent, dmxConfigECCallback(), dmxConfigVirtual, _DMXConfigVirtual::height, and _DMXConfigVirtual::width.
Referenced by main().
static void dmxConfigNDCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigAddSub(), dmxConfigCreateDisplay(), dmxConfigCurrentDisplay, dmxConfigEDCallback(), dmxConfigSubDisplay(), _DMXConfigDisplay::scrnHeight, _DMXConfigDisplay::scrnWidth, and _DMXConfigVirtual::subentry.
Referenced by main().
static void dmxConfigOkAction (Widget w, XEvent * event, String * params, Cardinal * num_params) [static]
References dmxConfigECOkCallback(), dmxConfigEDOkCallback(), dmxConfigOkCallback(), ecdialog0, ecdialog1, eddialog0, eddialog1, eddialog2, and opendialog.
Referenced by main().
static void dmxConfigOkCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigFilename, dmxConfigGetValueString(), dmxConfigNotSaved, dmxConfigReadFile(), dmxConfigState, dmxConfigStateOpen, dmxConfigWriteFile(), opendialog, and openpopup.
Referenced by dmxConfigOkAction(), and main().
static void dmxConfigOpenCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigSetPopupPosition(), dmxConfigState, dmxConfigStateOpen, okbutton, and openpopup.
Referenced by main().
static void dmxConfigPlaceMenu (Widget w, XEvent * event, String * params, Cardinal * num_params) [static]
References buttonpopup, and dmxConfigSetPopupPosition().
Referenced by main().
static void dmxConfigQuitCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigNotSaved, dmxConfigSetPopupPosition(), and quitpopup.
Referenced by main().
static void dmxConfigQuitCanCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References quitpopup.
Referenced by main().
static void dmxConfigQuitOkCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References quitpopup.
Referenced by main().
static void dmxConfigReadFile (void) [static]
References canvas, dmxConfigCanvasDraw(), dmxConfigCopystrings(), dmxConfigFilename, dmxConfigSetupCnamemenu(), dmxConfigVirtual, dmxConfigVirtualPrint(), dmxInfo, dmxLog(), dmxWarning, _DMXConfigEntry::next, str, _DMXConfigEntry::type, _DMXConfigEntry::virtual, yydebug, yyin, and yyparse().
Referenced by dmxConfigOkCallback(), and main().
static void dmxConfigSaveCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigSetPopupPosition(), dmxConfigState, dmxConfigStateSave, okbutton, and openpopup.
Referenced by main().
static void dmxConfigSelectCallback (Widget w, XtPointer closure, XtPointer callData) [static]
References dmxConfigCanvasDraw(), and dmxConfigVirtualPrint().
Referenced by dmxConfigSetupCnamemenu().
static void dmxConfigSetPopupPosition (Widget popup) [static]
Referenced by dmxConfigAboutCallback(), dmxConfigECCallback(), dmxConfigEDCallback(), dmxConfigOpenCallback(), dmxConfigPlaceMenu(), dmxConfigQuitCallback(), and dmxConfigSaveCallback().
static void dmxConfigSetupCnamemenu (void) [static]
References cnamebox, dmxConfigSelectCallback(), dmxConfigVirtual, _DMXConfigVirtual::name, _DMXConfigEntry::next, _DMXConfigEntry::type, and _DMXConfigEntry::virtual.
Referenced by dmxConfigDCCallback(), dmxConfigDDCallback(), dmxConfigECOkCallback(), dmxConfigEDOkCallback(), dmxConfigReadFile(), and main().
static void dmxConfigWriteFile (void) [static]
References dmxConfigFilename, dmxConfigPrint(), dmxLog(), dmxWarning, and str.
Referenced by dmxConfigOkCallback().
int main (int argc, char ** argv)
References aboutpopup, buttonpopup, canvas, cdimbox, cnamebox, dcbutton, ddbutton, dimbox, DMX_CANVAS_HEIGHT, DMX_CANVAS_WIDTH, DMX_DATA_HEIGHT, DMX_DATA_WIDTH, DMX_INFO, DMX_MAIN_HEIGHT, DMX_MAIN_WIDTH, dmxConfigAboutCallback(), dmxConfigAboutOkCallback(), dmxConfigCanCallback(), dmxConfigCanvasExpose(), dmxConfigCanvasInput(), dmxConfigCanvasResize(), dmxConfigCopystrings(), dmxConfigDCCallback(), dmxConfigDDCallback(), dmxConfigECCallback(), dmxConfigECCanCallback(), dmxConfigECOkCallback(), dmxConfigEDCallback(), dmxConfigEDCanCallback(), dmxConfigEDOkCallback(), dmxConfigFilename, dmxConfigNCCallback(), dmxConfigNDCallback(), dmxConfigOkAction(), dmxConfigOkCallback(), dmxConfigOpenCallback(), dmxConfigPlaceMenu(), dmxConfigQuitCallback(), dmxConfigQuitCanCallback(), dmxConfigQuitOkCallback(), dmxConfigReadFile(), dmxConfigSaveCallback(), dmxConfigSetupCnamemenu(), ecbutton, ecdialog0, ecdialog1, ecpopup, edbutton, eddialog0, eddialog1, eddialog2, edpopup, namebox, ndbutton0, ndbutton1, okbutton, opendialog, openpopup, origbox, quitpopup, and rtbox.
static int scalex (int x) [static]
References dmxConfigScaleX.
Referenced by dmxConfigCanvasUpdate(), and dmxConfigFindDisplay().
static int scaley (int y) [static]
References dmxConfigScaleY.
Referenced by dmxConfigCanvasUpdate(), and dmxConfigFindDisplay().
static int unscalex (int x) [static]
References dmxConfigScaleX.
Referenced by dmxConfigCanvasInput().
static int unscaley (int y) [static]
References dmxConfigScaleY.
Referenced by dmxConfigCanvasInput().
int yyparse (void)
Variable Documentation
Widget aboutpopup [static]
Referenced by dmxConfigAboutCallback(), dmxConfigAboutOkCallback(), and main().
Widget buttonpopup
Referenced by dmxConfigPlaceMenu(), and main().
Widget canvas [static]
Referenced by dmxConfigCanvasDraw(), dmxConfigCanvasGCs(), dmxConfigCanvasUpdate(), dmxConfigReadFile(), and main().
Widget cdimbox
Referenced by dmxConfigDataUpdate(), and main().
Widget cnamebox [static]
Referenced by dmxConfigDataUpdate(), dmxConfigSetupCnamemenu(), and main().
Widget dcbutton
Referenced by dmxConfigDataUpdate(), and main().
Widget ddbutton
Referenced by dmxConfigDataUpdate(), and main().
Widget dimbox
Referenced by dmxConfigDataUpdate(), and main().
DMXConfigVirtualPtr dmxConfigCurrent [static]
Referenced by dmxConfigNCCallback().
DMXConfigDisplayPtr dmxConfigCurrentDisplay [static]
Referenced by dmxConfigNDCallback().
DMXConfigEntryPtr dmxConfigEntry
char* dmxConfigFilename [static]
Referenced by dmxConfigOkCallback(), dmxConfigReadFile(), dmxConfigWriteFile(), and main().
GC dmxConfigGC [static]
Referenced by dmxConfigCanvasDraw(), dmxConfigCanvasGCs(), and dmxConfigCanvasUpdate().
GC dmxConfigGCHL
Referenced by dmxConfigCanvasDraw(), dmxConfigCanvasGCs(), and dmxConfigCanvasUpdate().
int dmxConfigGCInit = 0 [static]
Referenced by dmxConfigCanvasGCs().
GC dmxConfigGCRev
Referenced by dmxConfigCanvasDraw(), dmxConfigCanvasGCs(), and dmxConfigCanvasUpdate().
int dmxConfigGrabbed [static]
Referenced by dmxConfigCanvasInput().
int dmxConfigGrabbedFine
Referenced by dmxConfigCanvasInput().
int dmxConfigGrabbedX [static]
Referenced by dmxConfigCanvasInput().
int dmxConfigGrabbedY
Referenced by dmxConfigCanvasInput().
DMXConfigDisplayPtr dmxConfigNewDisplay
DMXConfigVirtualPtr dmxConfigNewVirtual
int dmxConfigNotSaved [static]
Referenced by dmxConfigECOkCallback(), dmxConfigEDOkCallback(), dmxConfigMove(), dmxConfigOkCallback(), and dmxConfigQuitCallback().
double dmxConfigScaleX [static]
Referenced by dmxConfigCanvasDraw(), scalex(), and unscalex().
double dmxConfigScaleY
Referenced by dmxConfigCanvasDraw(), scaley(), and unscaley().
enum { ... } dmxConfigState [static]
Referenced by dmxConfigOkCallback(), dmxConfigOpenCallback(), and dmxConfigSaveCallback().
Dimension dmxConfigWallHeight
Referenced by dmxConfigCanvasUpdate(), dmxConfigDataUpdate(), dmxConfigGetDims(), and dmxConfigMove().
Dimension dmxConfigWallWidth [static]
Referenced by dmxConfigCanvasUpdate(), dmxConfigDataUpdate(), dmxConfigGetDims(), and dmxConfigMove().
Dimension dmxConfigWidgetHeight
Referenced by dmxConfigCanvasDraw(), and dmxConfigCanvasUpdate().
Dimension dmxConfigWidgetWidth [static]
Referenced by dmxConfigCanvasDraw(), and dmxConfigCanvasUpdate().
Widget ecbutton [static]
Referenced by dmxConfigDataUpdate(), and main().
Widget ecdialog0
Referenced by dmxConfigECCallback(), dmxConfigECOkCallback(), dmxConfigOkAction(), and main().
Widget ecdialog1
Referenced by dmxConfigECCallback(), dmxConfigECOkCallback(), dmxConfigOkAction(), and main().
Widget ecpopup [static]
Referenced by dmxConfigECCallback(), dmxConfigECCanCallback(), dmxConfigECOkCallback(), and main().
Widget edbutton
Referenced by dmxConfigDataUpdate(), and main().
Widget eddialog0
Referenced by dmxConfigEDCallback(), dmxConfigEDOkCallback(), dmxConfigOkAction(), and main().
Widget eddialog1
Referenced by dmxConfigEDCallback(), dmxConfigEDOkCallback(), dmxConfigOkAction(), and main().
Widget eddialog2
Referenced by dmxConfigEDCallback(), dmxConfigEDOkCallback(), dmxConfigOkAction(), and main().
Widget edpopup [static]
Referenced by dmxConfigEDCallback(), dmxConfigEDCanCallback(), dmxConfigEDOkCallback(), and main().
Widget namebox [static]
Referenced by dmxConfigDataUpdate(), and main().
Widget ndbutton0 [static]
Referenced by dmxConfigDataUpdate(), and main().
Widget ndbutton1
Referenced by dmxConfigDataUpdate(), and main().
Widget okbutton [static]
Referenced by dmxConfigOpenCallback(), dmxConfigSaveCallback(), and main().
Widget opendialog
Referenced by dmxConfigOkAction(), dmxConfigOkCallback(), and main().
Widget openpopup [static]
Referenced by dmxConfigCanCallback(), dmxConfigOkCallback(), dmxConfigOpenCallback(), dmxConfigSaveCallback(), and main().
Widget origbox
Referenced by dmxConfigDataUpdate(), and main().
Widget quitpopup
Referenced by dmxConfigQuitCallback(), dmxConfigQuitCanCallback(), dmxConfigQuitOkCallback(), and main().
Widget rtbox
Referenced by dmxConfigDataUpdate(), and main().
FILE* yyin